### ISSUE TITLE
Problems with a string

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#1039]
During a test run at master, i fell into following error :
```
Enabling service fstrim.timer
['/usr/bin/arch-chroot', '/mnt/archinstall', 'systemctl', 'enable', 'fstrim.timer'] exited with abnormal exit code [256]: b'Failed to enable unit, file fstrim.timer: Input/output error.\r\n'
Traceback (most recent call last):
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 154, in perform_installation
    if installation.minimal_installation(testing=enable_testing, multilib=enable_multilib):
  File "/home/werner/projects/archinstall/archinstall/lib/installer.py", line 669, in minimal_installation
    self.enable_periodic_trim()
  File "/home/werner/projects/archinstall/archinstall/lib/installer.py", line 459, in enable_periodic_trim
    self.enable_service("fstrim.timer")
  File "/home/werner/projects/archinstall/archinstall/lib/installer.py", line 464, in enable_service
    if (output := self.arch_chroot(f'systemctl enable {service}')).exit_code != 0:
  File "/home/werner/projects/archinstall/archinstall/lib/installer.py", line 478, in arch_chroot
    return self.run_command(cmd)
  File "/home/werner/projects/archinstall/archinstall/lib/installer.py", line 472, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
  File "/home/werner/projects/archinstall/archinstall/lib/general.py", line 409, in __init__
    self.create_session()
  File "/home/werner/projects/archinstall/archinstall/lib/general.py", line 460, in create_session
    with SysCommandWorker(self.cmd, callbacks=self._callbacks, peak_output=self.peak_output, environment_vars=self.environment_vars, remove_vt100_escape_codes_from_lines=self.remove_vt100_escape_codes_from_lines) as session:
  File "/home/werner/projects/archinstall/archinstall/lib/general.py", line 268, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'systemctl', 'enable', 'fstrim.timer'] exited with abnormal exit code [256]: b'Failed to enable unit, file fstrim.timer: Input/output error.\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/werner/projects/archinstall/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/home/werner/projects/archinstall/./archinstall/__init__.py", line 269, in run_as_a_module
    script.execute()
  File "/home/werner/projects/archinstall/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 273, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 126, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/home/werner/projects/archinstall/archinstall/lib/installer.py", line 152, in __exit__
    print(_("[!] A log file has been created here: {} {}").format(os.path.join(storage['LOG_PATH'], storage['LOG_FILE'])))
  File "/home/werner/projects/archinstall/archinstall/lib/translation.py", line 61, in format
    return self.message.format(*args)
IndexError: Replacement index 1 out of range for positional args tuple
```
Still don't know what causes the first error, but the last one is due to this statement
```
   print(_("[!] A log file has been created here: {} {}").format(os.path.join(storage['LOG_PATH'], storage['LOG_FILE'])))
```
There is only one argument to the string, **not two** ;-) More annoying than supossed, because it is in the exit handler of `Installer`
Now looking for the basis error

**Comment by wllacer** [comment]
Main problem seems related to a 'dirty installation'  (installing over a previous, probably incomplete, one)
I've smashed a couple of bugs which will be added to PR #1036, as this one is a bug hunting one
