### ISSUE TITLE
KeyError with select_disk

### ISSUE THREAD

**Issue by KLIM8D** [archlinux/archinstall#1076]
With the most recent commit ATM (0604ed4) I'm getting an KeyError with the following

```python
archinstall.select_disk(archinstall.all_blockdevices(partitions=False))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/klim/tmp/archinstall/archinstall/lib/user_interaction/disk_conf.py", line 68, in select_disk
    f"{index}: {drive} ({dict_o_disks[drive]['size'], dict_o_disks[drive].device, dict_o_disks[drive]['label']})"
  File "/home/klim/tmp/archinstall/archinstall/lib/disk/blockdevice.py", line 42, in __getitem__
    raise KeyError(f'{self} does not contain information: "{key}"')
KeyError: 'BlockDevice(/dev/sda, size=476.9GB, free_space=, bus_type=sata) does not contain information: "size"'
```

To me it looks like the method `__getitem__` is not properly implemented for `BlockDevice`

```python
>>> import archinstall
>>> disks=archinstall.all_blockdevices(partitions=False)
>>> disks
{'/dev/sda4': BlockDevice(None, size=80.0GB, free_space=, bus_type=None), '/dev/sda2': BlockDevice(None, size=0.1GB, free_space=, bus_type=None), '/dev/sda5': BlockDevice(None, size=16.0GB, free_space=, bus_type=None), '/dev/sda3': BlockDevice(None, size=232.3GB, free_space=, bus_type=None), '/dev/sda1': BlockDevice(None, size=0.5GB, free_space=, bus_type=None), '/dev/sda': BlockDevice(/dev/sda, size=476.9GB, free_space=, bus_type=sata), '/dev/sda6': BlockDevice(None, size=148.0GB, free_space=, bus_type=None)}
>>> disks['/dev/sda']
BlockDevice(/dev/sda, size=476.9GB, free_space=, bus_type=sata)
>>> disks['/dev/sda'].size
476.9
>>> disks['/dev/sda']['size']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/klim/tmp/archinstall/archinstall/lib/disk/blockdevice.py", line 42, in __getitem__
    raise KeyError(f'{self} does not contain information: "{key}"')
KeyError: 'BlockDevice(/dev/sda, size=476.9GB, free_space=, bus_type=sata) does not contain information: "size"'
>>> disks['/dev/sda'].info
{'MAJOR': '8', 'MINOR': '0', 'DEVNAME': 'sda', 'DEVTYPE': 'disk', 'DISKSEQ': '1', 'path': '/dev/sda', 'PATH': '/dev/sda', 'PTTYPE': None}
>>>
```

**Comment by Torxed** [comment]
Thank you for reporting this.
We've started to migrate to dataclasses and properties rather than relying on dictionaries.

`master` contains some of these changes and we've obviously missed to migrate some older code.
We should probably also introduce a deprecation layer here and support `["size"]` for a while longer.

I'll get this fixed before release!

**Comment by svartkanin** [comment]
@Torxed I can have a look at this one, I don't see any dataclasses for `Blockdevice` though, but it might be good to create one to store the information in a safer way

**Comment by svartkanin** [comment]
Ahh sorry maybe it is the `MapperDev` you meant
