### ISSUE TITLE
Fails when given an LVM volume for root (possibly other mountpoints).

### ISSUE THREAD

**Issue by jamincollins** [archlinux/archinstall#1113]
Fails when given an LVM volume for root (possibly other mountpoints).

Could not get PARTUUID for /dev/mapper/vgnvme-root using 'lsblk -J -o+PARTUUID /dev/mapper/vgnvme-root'                                                        

In this case, `archinstall` should simply use UUID.

```
lsblk -J -o+PARTUUID,UUID /dev/mapper/vgnvme-root
```

**Comment by Torxed** [comment]
We're aware, but it would require additional logic and we should handle these in a context and not directly.

This should be a bit easier to deal with now that BlockDevice is a class and we're migrating to dataclasses

**Comment by i2** [comment]
So just to confirm, even by doing manual partitioning and mounting at /mnt, installing Arch on LVM is not possible using archinstall, correct?

**Comment by Torxed** [comment]
> So just to confirm, even by doing manual partitioning and mounting at /mnt, installing Arch on LVM is not possible using archinstall, correct?
> 
> Update: Sorry just saw the milestone for v2.4.4 !

Try mounting to `/mnt/archinstall`, any luck?

**Comment by i2** [comment]
To walk-through, how this is done, can you please correct me if I'm wrong in these steps:
- I partition manually the way I want: LUKS+LVM and then mkfs.btrfs (or any other fs)
- mount it to /mnt/archinstall : done
- cp examples/guided.py .
- python guided.py
- modify configs through menu how I want it
- Drive(s) -> Ctrl+C -> confirm -> shows that moun-install is experimental -> confirm
![archinstall-error-1](https://user-images.githubusercontent.com/3228126/169597976-be7f3345-b319-4249-9810-2d230ec697c5.png)

When I go back to main menu, I can't proceed to install because of missing drive selection!
![archinstall-error-2](https://user-images.githubusercontent.com/3228126/169598091-db3afc42-9091-4136-86e4-febca3131139.png)

What do I do? Thanks!

**Comment by Torxed** [comment]
We'll correct that part, but for now save the chosen config and do:
```
# archinstall --config /path/config.json --disk-layout /path/disks.json --creds /path/creds.json --silent
```

That should bypass the requisits that the menu system imposes :) everything else looks good

**Comment by i2** [comment]
> ```
> # --disk-layout /path/disks.json
> ```

but I don't have a disk layout json file for this! I only have a mount point /mnt/archinstall .

**Comment by Torxed** [comment]
> > ```
> > # --disk-layout /path/disks.json
> > ```
> 
> but I don't have a disk layout json file for this! I only have a mount point /mnt/archinstall .

Yea sorry, I was about to fall asleep yesterday haha.
With `--silent` it should mute any questions and skip `--disk-layout` hopefully.
I can give it a try today as well but that should work.

**Comment by i2** [comment]
I get this error:
`I get this error:
`
t@archiso ~/archinstall (git)-[master] # python3 guided.py --config user_configuration.json --creds user_credentials.json --silent
Testing connectivity to the Arch Linux mirrors ...
Waiting for automatic mirror selection (reflector) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
argument of type 'NoneType' is not iterable
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/root/archinstall/guided.py", line 311, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/root/archinstall/guided.py", line 138, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/root/archinstall/archinstall/lib/installer.py", line 159, in __exit__
    raise args[1]
  File "/root/archinstall/guided.py", line 185, in perform_installation
    enable_testing = 'testing' in archinstall.arguments.get('additional-repositories', None)
TypeError: argument of type 'NoneType' is not iterable``

**Comment by Torxed** [comment]
I'll have a look after I push the release, because LVM's isn't supported yet.
But I want it to be :) I just need to spend some time on reworking some BTRFS logic and push the release first.
