### ISSUE TITLE
archinstall fails to save configuration and run installation if a profile is selected

### ISSUE THREAD

**Issue by XumPZup** [archlinux/archinstall#1274]
I successfully installed archlinux on virtualbox using the archinstaller yesterday selecting the desktop profile. Today I was doing the same and the installation failed to start. After some testing I discovered that the installer works successfully if I don't select any profile but if I select any of the profiles i get an error when saving the configurations or start the install process.
The following error appens when saving the configurations with a profile selected:
```
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 1483, in show                                                                                             
    self._paint_menu()                                                                                                                                                                         
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 1391, in _paint_menu                                                                                      
    displayed_menu_height += print_preview(displayed_menu_height, preview_max_num_lines)                                                                                                       
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 1222, in print_preview
    preview_string = get_preview_string()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 1165, in get_preview_string
    preview_string = self._preview_command(preview_argument) if preview_argument is not None else ""
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/save_conf.py", line 18, in preview
    json_config = config_output.user_config_to_json()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/configuration.py", line 58, in user_config_to_json
    return json.dumps({
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 165, in encode
    return super(JSON, self).encode(self._encode(obj))
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DeferredTranslation is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 275, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 292, in <module>
    ask_user_questions()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 101, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 304, in run
    if not self._process_selection(selection):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 316, in _process_selection
    return self.exec_option(config_name, selector)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 336, in exec_option
    result = selector.func(presel_val)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 162, in <lambda>
    lambda preset: save_config(self._data_store),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/save_conf.py", line 53, in save_config
    preview_command=preview).run()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/menu.py", line 171, in run
    ret = self._show()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/menu.py", line 153, in _show
    idx = self.show()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 1545, in show
    self._clear_menu()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 1404, in _clear_menu
    assert self._previous_displayed_menu_height is not None
```

The following error appens when running the installation with a profile selected:
```
This is your chosen configuration:
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 275, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 296, in <module>
    config_output.show()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/configuration.py", line 78, in show
    user_conig = self.user_config_to_json()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/configuration.py", line 58, in user_config_to_json
    return json.dumps({
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 165, in encode
    return super(JSON, self).encode(self._encode(obj))
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DeferredTranslation is not JSON serializable
```

**Comment by svartkanin** [comment]
This could be related to #1180

**Comment by svartkanin** [comment]
@XumPZup would you have some steps to reproduce this?
I can try to do it using the stack trace but it would help to know what triggered it :)

**Comment by XumPZup** [comment]
Virtualbox version: 6.1
arch-iso:  

Here's the configurations I selected:
`  Select Archinstall language                   SET: English`                                                                                                                                                                                                                                                                                                                                                                                                                                    
`  Select keyboard layout                          SET: us`                                                                                                                                                                                                                                                                                                                                                                                                                             
`  Select mirror region                               SET: ['Brazil']`                                                                                                                                                                                                                                                                                                                                                                                                                         
`  Select harddrives                                   SET: [BlockDevice(/dev/sda, size=32.0GB, free_space=, bus_type=sata)]  `                                                                                                                                                                                                                                                                                                                                                                                 
`  Select disk layout                                   SET: {'/dev/sda': {'wipe': True, 'partitions': [{'type': 'primary', 'start': '3MiB', 'size': '203MiB', 'boot': True, 'encrypted': False, 'wipe': True, 'mountpoint': '/boot', 'filesystem': {'format': 'fat32'}}, {'type': 'primary', 'start': '206MiB', 'encrypted': False, 'wipe': True, 'mountpoint': '/', 'filesystem': {'format': 'ext4', 'mount_options': []}, 'size': '100%'}]}} `                                                                
`  Set encryption password                        SET: None`                                                                                                                                                                                                                                                                                                                                   
`  Select bootloader                                   SET: grub-install`                                                                                                                                                                                                                                                                                                                             
`  Use swap                                               SET: True`                                                                                                                                                                                                                                                                                                                      
`  Specify hostname                                  SET: archlinux`                                                                                                                                                                                                                                                                                                                            
`  Set root password                                  SET: ***`                                                                                                                                                                                                                                                                                                                      
`  Specify user account                             SET: []`                                                                                                                                                                                                                                                                                                                     
`  Specify profile                                        SET: Profile(xorg)`                                                                                                                                                                                                                                                                                                                     
`  Select audio                                           SET: pulseaudio `                                                                                                                                                                                                                                                                                                                     
`  Select kernels                                        SET: ['linux']`                                                                                                                                                                                                                                                                                                               
`  Additional packages to install                SET: [] `                                                                                                                                                                                                                                                                                                                    
`  Configure network                                 SET: Copy ISO configuration`                                                                                                                                                                                                                                                                                                                              
`  Select timezone                                    SET: UTC`                                                                                                                                                                                                                                                                                                                 
`  Set automatic time sync (NTP)             SET: True`                                                                                                                                                                                                                                                                                                                        
`  Additional repositories to enable           SET: ['multilib']`

Notes: 
- at "Specify user account" the list appears empty but i specified a user and promote him to superuser
- Installation fails with profiles "xorg" and "desktop" (I Haven't tested "server" profile)
- when using the above configurations and changing profile to "minimal" runs the installation process with no issues

**Comment by XumPZup** [comment]
Using the latest Arch ISO the installation works successfully with all profiles.
I'm closing the issue
