### ISSUE TITLE
Manual network configuration not parsed correctly

### ISSUE THREAD

**Issue by asininemonkey** [archlinux/archinstall#1342]
Using the new 2.5.0 installer I've exported the network configuration as follows:

```
    "nic": [
        {
            "dhcp": true,
            "dns": null,
            "gateway": null,
            "iface": "enp2s0",
            "ip": null,
            "type": "manual"
        }
    ],
```

When passing this back to archinstall, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 254, in <module>
    post_process_arguments(arguments)
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 246, in post_process_arguments
    load_config()
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 210, in load_config
    handler.parse_arguments(arguments.get('nic'))
  File "/usr/lib/python3.10/site-packages/archinstall/lib/models/network_configuration.py", line 157, in parse_arguments
    nic_type = config.get('type', None)
AttributeError: 'list' object has no attribute 'get'
```

**Comment by svartkanin** [comment]
@Torxed can close this as its fixed
