### ISSUE TITLE
I can't install ISO from commit #1331

### ISSUE THREAD

**Issue by castillofrancodamian** [archlinux/archinstall#1343]
```
Esta es su configuración elegida:
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "Spanish",
    "audio": null,
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.0",
    "debug": false,
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "archlinux",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "es",
    "mirror-region": {
        "Brazil": {
            "http://archlinux.c3sl.ufpr.br/$repo/os/$arch": true,
            "http://archlinux.pop-es.rnp.br/$repo/os/$arch": true,
            "http://br.mirror.archlinux-br.org/$repo/os/$arch": true,
            "http://linorg.usp.br/archlinux/$repo/os/$arch": true,
            "http://mirror.ufscar.br/archlinux/$repo/os/$arch": true
        }
    },
    "mount_point": null,
    "nic": [
        {
            "dhcp": false,
            "dns": [
                "192.168.1.203"
            ],
            "gateway": "192.168.1.1",
            "iface": "enp0s3",
            "ip": "192.168.1.150/24",
            "type": "manual"
        }
    ],
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "htop",
        "nano",
        "neofetch",
        "screenfetch",
        "openssh"
    ],
    "plugin": null,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/minimal.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": false,
    "sys-encoding": "UTF-8",
    "sys-language": "es_AR",
    "timezone": "America/Argentina/Buenos_Aires",
    "version": "2.5.0"
}
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}

Presione Entrar para continuar.
 ! Formatting [BlockDevice(/dev/sda, size=8.0GB, free_space=1031kB+8053MB, bus_type=sata)] in 5....4....3....2....1....
Creating a new partition label on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=8.0GB, free_space=1031kB+8053MB, bus_type=sata), 1MiB->512MiB
Formatting /dev/sda1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/sda1
Marking partition Partition(path=/dev/sda1, size=0.5, PARTUUID=DE81-5A3D, fs=vfat) as bootable.
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 277, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 306, in <module>
    perform_filesystem_operations()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 126, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 44, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 127, in perform_filesystem_operations
    fs.load_layout(archinstall.arguments['disk_layouts'][drive.path])
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 173, in load_layout
    self.set(self.partuuid_to_index(partition['device_instance'].part_uuid), 'boot on')
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 64, in partuuid_to_index
    raise DiskError(f"Failed to convert PARTUUID {uuid} to a partition index number on blockdevice {self.blockdevice.device}")
archinstall.lib.exceptions.DiskError: Failed to convert PARTUUID f8d87a7f-ce6b-4295-ba84-94882c5d0ec4 to a partition index number on blockdevice /dev/sda
archinstall  3.03s user 4.56s system 5% cpu 2:14.25 total
1 root@archiso ~/archinstall-git # cat /var/log/archinstall/install.log
Hardware model detected: innotek GmbH VirtualBox; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
Memory statistics: 998336 available out of 2010980 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '703M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '8G', 'children': [{'name': 'sda1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '511M'}]}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202206', 'uuid': '2022-06-14-12-30-06-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'rom', 'size': '876.3M'}]}
Testing connectivity to the Arch Linux mirrors ...
Setting new font: 
Could not get free space on /dev/sr0: ['/usr/bin/parted', '-s', '--machine', '/dev/sr0', 'print', 'free'] exited with abnormal exit code [256]: b"Warning: Unable to open /dev/sr0 read-write (Read-only file system).  /dev/sr0 has been opened read-only.\r\nError: Can't have a partition outside the disk!\r\nBYT;\r\n/dev/sr0:919MB:scsi:2048:2048:unknown:VBOX CD-ROM:;\r\n"
Password strength: weak
Password strength: weak
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "Spanish",
    "audio": null,
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.0",
    "debug": false,
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "archlinux",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "es",
    "mirror-region": {
        "Brazil": {
            "http://archlinux.c3sl.ufpr.br/$repo/os/$arch": true,
            "http://archlinux.pop-es.rnp.br/$repo/os/$arch": true,
            "http://br.mirror.archlinux-br.org/$repo/os/$arch": true,
            "http://linorg.usp.br/archlinux/$repo/os/$arch": true,
            "http://mirror.ufscar.br/archlinux/$repo/os/$arch": true
        }
    },
    "mount_point": null,
    "nic": [
        {
            "dhcp": false,
            "dns": [
                "192.168.1.203"
            ],
            "gateway": "192.168.1.1",
            "iface": "enp0s3",
            "ip": "192.168.1.150/24",
            "type": "manual"
        }
    ],
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "htop",
        "nano",
        "neofetch",
        "screenfetch",
        "openssh"
    ],
    "plugin": null,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/minimal.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": false,
    "sys-encoding": "UTF-8",
    "sys-language": "es_AR",
    "timezone": "America/Argentina/Buenos_Aires",
    "version": "2.5.0"
}
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=8.0GB, free_space=1031kB+8053MB, bus_type=sata), 1MiB->512MiB
Adding partition using the following parted command: /dev/sda mkpart primary fat32 1MiB 512MiB
Formatting /dev/sda1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/sda1
Could not locate mount information for /dev/sda1: ['/usr/bin/findmnt', '--json', '-R', '/dev/sda1'] exited with abnormal exit code [256]: b''
Marking partition Partition(path=/dev/sda1, size=0.5, PARTUUID=DE81-5A3D, fs=vfat) as bootable.

```

**Comment by svartkanin** [comment]
There's a PR up that might (?) solve this problem https://github.com/archlinux/archinstall/pull/1333. 
If you wanna go through the hassle of trying that one out you can get the branch here https://github.com/svartkanin/archinstall/tree/cleanup-partition and try it with that one to see if it fixes things

**Comment by wllacer** [comment]
@svartkanin PR #1333 breaks even earlier, if a partition *already* exists on the disk, but performs if the target disk has no partitions (but retains the gpt label)
Master fails always.
The error at your PR
```
Press Enter to continue.
 ! Formatting [BlockDevice(/dev/loop0, size=8.0GB, free_space=5225kB+8077MB, bus_type=None)] in 5....4....3....2....1....
Creating a new partition label on /dev/loop0
Adding partition to BlockDevice(/dev/loop0, size=8.0GB, free_space=5225kB+8077MB, bus_type=None), 5MB->513MB
Could not find the new PARTUUID after adding the partition.
Previous partitions: []
New partitions: {None}
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/werner/projects/archinstall/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/home/werner/projects/archinstall/./archinstall/__init__.py", line 277, in run_as_a_module
    script.execute()
  File "/home/werner/projects/archinstall/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 306, in <module>
    perform_filesystem_operations()
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 126, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "/home/werner/projects/archinstall/archinstall/lib/disk/filesystem.py", line 44, in __exit__
    raise args[1]
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 127, in perform_filesystem_operations
    fs.load_layout(archinstall.arguments['disk_layouts'][drive.path])
  File "/home/werner/projects/archinstall/archinstall/lib/disk/filesystem.py", line 89, in load_layout
    partition['device_instance'] = self.add_partition(partition.get('type', 'primary'),
  File "/home/werner/projects/archinstall/archinstall/lib/disk/filesystem.py", line 283, in add_partition
    raise DiskError(f"Could not add partition using: {parted_string}")
archinstall.lib.exceptions.DiskError: Could not add partition using: /dev/loop0 mkpart primary fat32 5MB 513MB
```

**Comment by svartkanin** [comment]
@wllacer thanks for checking I'll have a look into it
