### ISSUE TITLE
KeyError: 'sys-encoding'

### ISSUE THREAD

**Issue by danfossi** [archlinux/archinstall#1349]
### user_configuration.json
```
{
    "archinstall-language": "Italian",
    "HSM": null,
    "audio": "pulseaudio",
    "bootloader": "grub-install",
    "config_version": "2.5.0",
    "debug": false,
    "harddrives": [
        "/dev/sda"
    ],
    "keyboard-layout": "it",
    "mirror-region": {
        "Italy": {
            "http://archlinux.mirror.garr.it/archlinux/$repo/os/$arch": true,
            "http://archlinux.mirror.server24.net/$repo/os/$arch": true,
            "https://archlinux.mirror.server24.net/$repo/os/$arch": true,
            "https://archmirror.it/repos/$repo/os/$arch": true
        }
    },
    "additional-repositories": [
        "multilib"
    ],
    "mount_point": null,
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "nm"
    },
    "packages": [
        "zsh"
   ],
    "plugin": null,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/minimal.py"
    },
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-language": "it_IT",
    "timezone": "Europe/Rome",
    "version": "2.5.0"
}
```
### Error:
```
'sys-encoding'
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 281, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 307, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 137, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 159, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 188, in perform_installation
    installation.set_locale(archinstall.arguments['sys-language'], archinstall.arguments['sys-encoding'].upper())
KeyError: 'sys-encoding'
```

**Comment by danfossi** [comment]
fixed adding:
`"sys-encoding": "utf-8"`
