### ISSUE TITLE
Updating archlinux-keyring

### ISSUE THREAD

**Issue by hard-tek** [archlinux/archinstall#1448]
I boot into Arch ISO from usb drive, type arch install and then checks for archlinux-keyring followed by a bunch of errors.

pacman -S  archlinux-keyring does not work 
pacman -Sy does nothing - all up to date

![IMG_0385](https://user-images.githubusercontent.com/1408367/187919060-1645a0b5-63b2-40e0-8096-1dbfcd0ef5c9.jpg)

**Comment by castillofrancodamian** [comment]
it happens to me too

```
root@archiso ~ # archinstall 
Testing connectivity to the Arch Linux mirrors ...
Updating archlinux-keyring ...
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 281, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 286, in <module>
    if not archinstall.update_keyring():
  File "/usr/lib/python3.10/site-packages/archinstall/lib/networking.py", line 46, in update_keyring
    if run_pacman("-Sy --noconfirm archlinux-keyring").exit_code == 0:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/pacman.py", line 28, in run_pacman
    return SysCommand(f'{default_cmd} {args}')
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 416, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 467, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 273, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/pacman', '-Sy', '--noconfirm', 'archlinux-keyring'] exited with abnormal exit code [256]: b'ng package integrity                   [######################] 100%\r\r\nerror: archlinux-keyring: signature from "Christian Hesse (Arch Linux Package Signing) <arch@eworm.de>" is marginal trust\r\n:: File /var/cache/pacman/pkg/archlinux-keyring-20220831-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).\r\nDo you want to delete it? [Y/n] \r\nerror: failed to commit transaction (invalid or corrupted package (PGP signature))\r\nErrors occurred, no packages were upgraded.\r\n\x1b[?25h'
1 root@archiso ~ #                                                                                                                                                  :(
```

**Comment by Torxed** [comment]
@castillofrancodamian what happens if you run `pacman -Sy archlinux-keyring` manually before running archinstall? Notice the `y`, it's important!

**Comment by Rew20** [comment]
It`s always the same keyring was changed on Aug/31 got to this solution:
https://github.com/archlinux/archinstall/issues/1389
This is realy annoying and after the disastrous grub issue I switched to Fedora,
Cheers

**Comment by castillofrancodamian** [comment]
@Torxed I see you need to update.

```
root@archiso ~ # pacman -Sy archlinux-keyring
:: Synchronizing package databases...
 core                                                                    157.7 KiB  86.2 KiB/s 00:02 [###########################################################] 100%
 extra                                                                  1845.5 KiB  2.80 MiB/s 00:01 [###########################################################] 100%
 community                                                                 6.9 MiB  4.60 MiB/s 00:01 [###########################################################] 100%
resolving dependencies...
looking for conflicting packages...

Packages (1) archlinux-keyring-20220831-1

Total Download Size:   1.10 MiB
Total Installed Size:  1.57 MiB
Net Upgrade Size:      0.02 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 archlinux-keyring-20220831-1-any                                       1130.1 KiB  1079 KiB/s 00:01 [###########################################################] 100%
(1/1) checking keys in keyring                                                                       [###########################################################] 100%
(1/1) checking package integrity                                                                     [###########################################################] 100%
error: archlinux-keyring: signature from "Christian Hesse (Arch Linux Package Signing) <arch@eworm.de>" is unknown trust
:: File /var/cache/pacman/pkg/archlinux-keyring-20220831-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```

**Comment by palaboy** [comment]
it happens to me just now any solution?

**Comment by hard-tek** [comment]
Managed to fix it but this is not OK. 

I see that the issue is few weeks old and not solved yet... I guess Arch devs have no interest in fixing vital issues and they want to lose users. 
This should be solved on day 1, not on the next release. 

Disappointed.

**Comment by Torxed** [comment]
> Managed to fix it but this is not OK.
> 
> I see that the issue is few weeks old and not solved yet... I guess Arch devs have no interest in fixing vital issues and they want to lose users. This should be solved on day 1, not on the next release.
> 
> Disappointed.

Thank you for your feedback, which however is not entirely relevant to archinstall in it's core. We're trying to mitigate the issue in this **package** while upstream adress the issue (where the issue originate!).

I get that this is frustrating, but you would **forced** to fix this manually either way. So the workaround globally within the arch ecosphere is to do what's been explained until we get a fix for it. Again, `archinstall` is a program, just like `ls` or `pacman`. We rely on the keyring just like everyone else and share your frustration.

I hope this answers your feedback.
