### ISSUE TITLE
Can' install on loop device image (Testing : Without-a-live-iso-imag)

### ISSUE THREAD

**Issue by ato2** [archlinux/archinstall#1449]
% archinstall -v
archinstall 2.5.1rc1
% losetup /dev/loop1
/dev/loop1: []: (/tmp/img/archinstall.img)
% sudo archinstall
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 298, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 301, in <module>
    ask_user_questions()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 107, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 336, in run
    if not self._process_selection(value):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 353, in _process_selection
    return self.exec_option(config_name, selector)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 373, in exec_option
    result = selector.func(presel_val)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 92, in <lambda>
    lambda preset: self._select_harddrives(preset),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 358, in _select_harddrives
    harddrives = select_harddrives(old_harddrives)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/system_conf.py", line 52, in select_harddrives
    hard_drives = all_blockdevices(partitions=False).values()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/helpers.py", line 253, in all_blockdevices
    instances[path] = BlockDevice(path, path_info)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 50, in __init__
    self._block_info = self._fetch_information()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 154, in _fetch_information
    lsblk_info = self._call_lsblk(self._path)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 111, in _call_lsblk
    output = SysCommand(f'lsblk --json -b -o+SIZE,PTTYPE,ROTA,TRAN,PTUUID {self._path}').decode('UTF-8')
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 435, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 486, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 275, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code, worker=self)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/lsblk', '--json', '-b', '-o+SIZE,PTTYPE,ROTA,TRAN,PTUUID', '/dev/loop2'] exited with abnormal exit code [8192]: b'{\r\n   "blockdevices": [\r\n\r\n   ]\r\n}\r\n'

% tail /var/log/archinstall/install.log
Could not get block device information using blkid() using command blkid -p -o export /dev/loop1
Could not get free space on /dev/loop1: ['/usr/bin/parted', '-s', '--machine', '/dev/loop1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/loop1: unrecognised disk label\r\nBYT;\r\n/dev/loop1:8590MB:loopback:512:512:unknown:Loopback device:;\r\n'

% sudo parted -s --machine /dev/loop1 print
Error: /dev/loop1: unrecognised disk label
BYT;
/dev/loop1:8590MB:loopback:512:512:unknown:Loopback device:;

**Comment by svartkanin** [comment]
This isnow fixed
