### ISSUE TITLE
Some times BlockDevice() gets initiated with a non existent block device

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1488]
```
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
'/dev/block'
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 316, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 141, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 160, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 195, in perform_installation
    if installation.minimal_installation(testing=enable_testing, multilib=enable_multilib):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 694, in minimal_installation
    if self.detect_encryption(partition):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 633, in detect_encryption
    return partition.partition
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/mapperdev.py", line 47, in partition
    block_device = BlockDevice(get_parent_of_partition('/dev/' / pathlib.Path(information['DEVNAME'])))
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 44, in __init__
    self.info = all_blockdevices(partitions=False)[path].info
KeyError: '/dev/block'
```

Problematic code: https://github.com/archlinux/archinstall/blob/53a2797af6ac0832bf7dd00dfe96b8ea1867db2e/archinstall/lib/disk/mapperdev.py#L33-L47

Pseudo logic to simplify:
```
result = /sys/class/block/{/dev/mapper/dm_device.name}/slaves/*
info = blkid -o export /dev/{save_name}

Breaks: /dev/{info.DEVNAME}
```

**Comment by SG-starr** [comment]
I have encountered the same bug in 2.5.2 version.

**Comment by Torxed** [comment]
> I have encountered the same bug in 2.5.2 version. I get "Exit code for blkid -p -o export was: 512 Not a loop device, trying uevent rules." every time I try installing via script.

That is ok. That's debug information for us when people send in screenshots/logs on other errors :)
You can safely ignore those if the program continues.

**Comment by SG-starr** [comment]
> > I have encountered the same bug in 2.5.2 version. I get "Exit code for blkid -p -o export was: 512 Not a loop device, trying uevent rules." every time I try installing via script.
> 
> That is ok. That's debug information for us when people send in screenshots/logs on other errors :) You can safely ignore those if the program continues.

Yes, the program seems to be working as it's intended, but this bug is a little bit confusing.

**Comment by svartkanin** [comment]
This should be resolved with all the recent changes
