### ISSUE TITLE
'/usr/bin/parted -s None mklabel gpt' did not exit gracefully (trace log above), exit code: 256

### ISSUE THREAD

**Issue by greyltc** [archlinux/archinstall#151]
I posted this problem to #archlinux irc just now.

```
This is your chosen configuration:
{
    "!root-password": "******",
    "filesystem": "btrfs",
    "harddrive": {
        "model": null,
        "path": "/dev/md126",
        "size": "232.8G"
    },
    "hostname": "REDACTED",
    "keyboard-language": "uk",
    "mirror-region": {
        "United Kingdom": {
            "https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch": true,
            "https://lon.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://mirror.bytemark.co.uk/archlinux/$repo/os/$arch": true,
            "https://mirror.netweaver.uk/archlinux/$repo/os/$arch": true,
            "https://mirrors.melbourne.co.uk/archlinux/$repo/os/$arch": true,
            "https://www.mirrorservice.org/sites/ftp.archlinux.org/$repo/os/$arch": true
        }
    },
    "nic": {
        "nic": "eno1"
    },
    "packages": [
        "vim",
        "ufw"
    ],
    "profile": null,
    "superusers": {
        "REDACTED": {
            "!password": "******"
        }
    },
    "timezone": "Europe/London",
    "users": {}
}

Press Enter to continue.
 ! Formatting BlockDevice(None) in 5....4....3....2....1....
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/archinstall/__main__.py", line 34, in <module>
    run_as_a_module()
  File "/usr/lib/python3.9/site-packages/archinstall/__main__.py", line 31, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.9/site-packages/archinstall/lib/profiles.py", line 143, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 342, in <module>
    perform_installation_steps()
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 247, in perform_installation_steps
    with archinstall.Filesystem(archinstall.arguments['harddrive'], archinstall.GPT) as fs:
  File "/usr/lib/python3.9/site-packages/archinstall/lib/disk.py", line 400, in __enter__
    if self.raw_parted(f'{self.blockdevice.device} mklabel gpt').exit_code == 0:
  File "/usr/lib/python3.9/site-packages/archinstall/lib/disk.py", line 432, in raw_parted
    x = sys_command(f'/usr/bin/parted -s {string}')
  File "/usr/lib/python3.9/site-packages/archinstall/lib/general.py", line 129, in __init__
    self.run()
  File "/usr/lib/python3.9/site-packages/archinstall/lib/general.py", line 259, in run
    raise SysCallError(message=f"{self.trace_log.decode('UTF-8')}\n'{self.raw_cmd}' did not exit gracefully (trace log above), exit code: {self.exit_code}", exit_code=self.exit_code)
archinstall.lib.exceptions.SysCallError: Error: Could not stat device None - No such file or directory.

'/usr/bin/parted -s None mklabel gpt' did not exit gracefully (trace log above), exit code: 256
```

The script puts a None in the drive selection list where instead it should have resolved the block device's path, `/dev/md126`:
```
 -- You can skip this step by leaving the option blank --
Select one of the above regions to download packages from (by number or full name): 50
0: /dev/loop0 (('618.3M', '/run/archiso/bootmnt/arch/x86_64/airootfs.sfs', None))
1: /dev/md126 (('232.8G', None, None))
2: /dev/sda (('232.8G', '/dev/sda', None))
3: /dev/sdb (('232.8G', '/dev/sdb', None))
4: /dev/sdc (('14.4G', '/dev/sdc', None))
5: /dev/sr0 (('1024M', None, None))
Select one of the above disks (by number or full path): 1
0: btrfs
1: ext4
2: f2fs
3: xfs
Select which filesystem your main partition should use (by number or name): 
```
and then feeds that None to the parted command which causes the error.

**Comment by greyltc** [comment]
```
# lsblk --json -l -n -o path,size,type,mountpoint,label,pkname,model
{
   "blockdevices": [
      {"path":"/dev/loop0", "size":"618.3M", "type":"loop", "mountpoint":"/run/archiso/airootfs", "label":null, "pkname":null, "model":null},
      {"path":"/dev/sda", "size":"232.8G", "type":"disk", "mountpoint":null, "label":null, "pkname":null, "model":"ST3250318AS"},
      {"path":"/dev/sdb", "size":"232.8G", "type":"disk", "mountpoint":null, "label":null, "pkname":null, "model":"ST3250318AS"},
      {"path":"/dev/sdc", "size":"14.4G", "type":"disk", "mountpoint":null, "label":null, "pkname":null, "model":"DataTraveler_2.0"},
      {"path":"/dev/sdc1", "size":"14.4G", "type":"part", "mountpoint":"/run/archiso/bootmnt", "label":"ARCH_202104", "pkname":"sdc", "model":null},
      {"path":"/dev/md126", "size":"232.8G", "type":"raid1", "mountpoint":null, "label":null, "pkname":"sdb", "model":null},
      {"path":"/dev/sr0", "size":"1024M", "type":"rom", "mountpoint":null, "label":null, "pkname":null, "model":"TSSTcorp_DVD+_-RW_TS-H653J"}
   ]
}
```

**Comment by greyltc** [comment]
and
```
root@archiso /dev/disk/by-uuid # lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0     7:0    0 618.3M  1 loop  /run/archiso/airootfs
sda       8:0    0 232.8G  0 disk  
└─md126   9:126  0 232.8G  0 raid1 
sdb       8:16   0 232.8G  0 disk  
└─md126   9:126  0 232.8G  0 raid1 
sdc       8:32   1  14.4G  0 disk  
└─sdc1    8:33   1  14.4G  0 part  /run/archiso/bootmnt
sr0      11:0    1  1024M  0 rom   
root@archiso /dev/disk/by-uuid # blkid
/dev/sda: TYPE="isw_raid_member"
/dev/sdb: TYPE="isw_raid_member"
/dev/sdc1: LABEL="ARCH_202104" UUID="6C3E-4AC1" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="03c78dd9-01"
/dev/loop0: TYPE="squashfs"
```

**Comment by greyltc** [comment]
This is an older Dell Optiplex 990 tower pc where I set up two drives as raid 1 in the built in raid config menu in the BIOS

**Comment by Torxed** [comment]
As confirmed, the patch works.
But later on there's an issue with `/dev/disk/by-partuuid` being un-reliable:

```
Adding bootloader systemd-bootctl to Partition(path=/dev/md126p1, fs=vfat, mounted=/mnt/boot)
Could not identify the UUID of Partition(path=/dev/md126p2, fs=btrfs, mounted=/mnt), there for /mnt/boot/loader/entries/arch.conf will be broken until fixed.
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/Torxed/archinstall/issues
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/archinstall/archinstall/__main__.py", line 34, in <module>
    run_as_a_module()
  File "/root/archinstall/archinstall/__main__.py", line 31, in run_as_a_module
    script.execute()
  File "/root/archinstall/archinstall/lib/profiles.py", line 143, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/archinstall/archinstall/examples/guided.py", line 345, in <module>
    perform_installation_steps()
  File "/root/archinstall/archinstall/examples/guided.py", line 286, in perform_installation_steps
    perform_installation(device=fs.find_partition('/'),
  File "/root/archinstall/archinstall/lib/disk.py", line 433, in __exit__
    raise args[1]
  File "/root/archinstall/archinstall/examples/guided.py", line 286, in perform_installation_steps
    perform_installation(device=fs.find_partition('/'),
  File "/root/archinstall/archinstall/examples/guided.py", line 341, in perform_installation
    installation.user_set_pw('root', root_pw)
  File "/root/archinstall/archinstall/lib/installer.py", line 89, in __exit__
    raise args[1]
  File "/root/archinstall/archinstall/examples/guided.py", line 311, in perform_installation
    installation.add_bootloader()
  File "/root/archinstall/archinstall/lib/installer.py", line 400, in add_bootloader
    raise RequirementError(f"Could not identify the UUID of {self.partition}, there for {self.mountpoint}/boot/loader/entries/arch.conf will be broken until fixed.")
archinstall.lib.exceptions.RequirementError: Could not identify the UUID of Partition(path=/dev/md126p2, fs=btrfs, mounted=/mnt), there for /mnt/boot/loader/entries/arch.conf will be broken until fixed.
python -m archinstall  49.46s user 21.54s system 8% cpu 13:28.98 total
```
And the issue (copying your output greyltc) is `/dev/disk/by-partuuid`:
```
root@archiso /dev/disk/by-partuuid # ls -al
total 0
drwxr-xr-x 2 root root  60 Dec  7  2019 .
drwxr-xr-x 7 root root 140 Dec  7  2019 ..
lrwxrwxrwx 1 root root  10 Mar 14 20:31 03c78dd9-01 -> ../../sdc1
```

We'll have to switch over to using `lsblk -o+UUID -J` or some other source instead.
But that appears to not report the partition UUID correctly, here there is a inconsitency of what's reported (non-raided system):
```
[root@archiso ~]# lsblk -o+UUID -J
{
   "blockdevices": [
      {"name":"sda", "maj:min":"8:0", "rm":false, "size":"30G", "ro":false, "type":"disk", "mountpoint":null, "uuid":null,
         "children": [
            {"name":"sda1", "maj:min":"8:1", "rm":false, "size":"100M", "ro":false, "type":"part", "mountpoint":null, "uuid":"493a479a-8abf-41cc-baaa-69407bcc0f92"},
            {"name":"sda2", "maj:min":"8:2", "rm":false, "size":"19.9G", "ro":false, "type":"part", "mountpoint":"/", "uuid":"3492b4ae-e77b-41d4-8b1d-487b0b4cd4ee"},
            {"name":"sda3", "maj:min":"8:3", "rm":false, "size":"10G", "ro":false, "type":"part", "mountpoint":"[SWAP]", "uuid":"0bb1e010-cc6a-466e-8d15-6814085fc13a"}
         ]
      },
      {"name":"sr0", "maj:min":"11:0", "rm":true, "size":"1024M", "ro":false, "type":"rom", "mountpoint":null, "uuid":null}
   ]
}
[root@archiso ~]# ls -l /dev/disk/by-partuuid/
total 0
lrwxrwxrwx 1 root root 10 Feb 21 00:13 7ceaf282-01 -> ../../sda1
lrwxrwxrwx 1 root root 10 Feb 21 00:13 7ceaf282-02 -> ../../sda2
lrwxrwxrwx 1 root root 10 Feb 21 00:13 7ceaf282-03 -> ../../sda3
```

**Comment by Torxed** [comment]
Correct logic should be checking for:
```
root@archiso /dev/disk # lsblk -o+PARTUUID -J
{
   "blockdevices": [
      {"name":"loop0", "maj:min":"7:0", "rm":false, "size":"618.3M", "ro":true, "type":"loop", "mountpoint":"/run/archiso/airootfs", "partuuid":null},
      {"name":"sda", "maj:min":"8:0", "rm":false, "size":"232.8G", "ro":false, "type":"disk", "mountpoint":null, "partuuid":null,
         "children": [
            {"name":"md126", "maj:min":"9:126", "rm":false, "size":"232.8G", "ro":false, "type":"raid1", "mountpoint":null, "partuuid":null,
               "children": [
                  {"name":"md126p1", "maj:min":"259:0", "rm":false, "size":"512M", "ro":false, "type":"part", "mountpoint":"/mnt/boot", "partuuid":"7eac1721-e88e-43c5-93c6-b3c64e6830b5"},
                  {"name":"md126p2", "maj:min":"259:1", "rm":false, "size":"232.3G", "ro":false, "type":"part", "mountpoint":"/mnt", "partuuid":"046ccb38-9cef-47bd-ab3a-81280d24406c"}
               ]
            }
         ]
      },
      {"name":"sdb", "maj:min":"8:16", "rm":false, "size":"232.8G", "ro":false, "type":"disk", "mountpoint":null, "partuuid":null,
         "children": [
            {"name":"md126", "maj:min":"9:126", "rm":false, "size":"232.8G", "ro":false, "type":"raid1", "mountpoint":null, "partuuid":null,
               "children": [
                  {"name":"md126p1", "maj:min":"259:0", "rm":false, "size":"512M", "ro":false, "type":"part", "mountpoint":"/mnt/boot", "partuuid":"7eac1721-e88e-43c5-93c6-b3c64e6830b5"},
                  {"name":"md126p2", "maj:min":"259:1", "rm":false, "size":"232.3G", "ro":false, "type":"part", "mountpoint":"/mnt", "partuuid":"046ccb38-9cef-47bd-ab3a-81280d24406c"}
               ]
            }
         ]
      },
      {"name":"sdc", "maj:min":"8:32", "rm":true, "size":"14.4G", "ro":false, "type":"disk", "mountpoint":null, "partuuid":null,
         "children": [
            {"name":"sdc1", "maj:min":"8:33", "rm":true, "size":"14.4G", "ro":false, "type":"part", "mountpoint":"/run/archiso/bootmnt", "partuuid":"03c78dd9-01"}
         ]
      },
      {"name":"sr0", "maj:min":"11:0", "rm":true, "size":"1024M", "ro":false, "type":"rom", "mountpoint":null, "partuuid":null}
   ]
}
```
```
root@archiso /dev/disk # lsblk -o+PARTUUID -J
{
   "blockdevices": [
      {"name":"loop0", "maj:min":"7:0", "rm":false, "size":"618.3M", "ro":true, "type":"loop", "mountpoint":"/run/archiso/airootfs", "partuuid":null},
      {"name":"sda", "maj:min":"8:0", "rm":false, "size":"232.8G", "ro":false, "type":"disk", "mountpoint":null, "partuuid":null,
         "children": [
            {"name":"md126", "maj:min":"9:126", "rm":false, "size":"232.8G", "ro":false, "type":"raid1", "mountpoint":null, "partuuid":null,
               "children": [
                  {"name":"md126p1", "maj:min":"259:0", "rm":false, "size":"512M", "ro":false, "type":"part", "mountpoint":"/mnt/boot", "partuuid":"7eac1721-e88e-43c5-93c6-b3c64e6830b5"},
                  {"name":"md126p2", "maj:min":"259:1", "rm":false, "size":"232.3G", "ro":false, "type":"part", "mountpoint":"/mnt", "partuuid":"046ccb38-9cef-47bd-ab3a-81280d24406c"}
               ]
            }
         ]
      },
      {"name":"sdb", "maj:min":"8:16", "rm":false, "size":"232.8G", "ro":false, "type":"disk", "mountpoint":null, "partuuid":null,
         "children": [
            {"name":"md126", "maj:min":"9:126", "rm":false, "size":"232.8G", "ro":false, "type":"raid1", "mountpoint":null, "partuuid":null,
               "children": [
                  {"name":"md126p1", "maj:min":"259:0", "rm":false, "size":"512M", "ro":false, "type":"part", "mountpoint":"/mnt/boot", "partuuid":"7eac1721-e88e-43c5-93c6-b3c64e6830b5"},
                  {"name":"md126p2", "maj:min":"259:1", "rm":false, "size":"232.3G", "ro":false, "type":"part", "mountpoint":"/mnt", "partuuid":"046ccb38-9cef-47bd-ab3a-81280d24406c"}
               ]
            }
         ]
      },
      {"name":"sdc", "maj:min":"8:32", "rm":true, "size":"14.4G", "ro":false, "type":"disk", "mountpoint":null, "partuuid":null,
         "children": [
            {"name":"sdc1", "maj:min":"8:33", "rm":true, "size":"14.4G", "ro":false, "type":"part", "mountpoint":"/run/archiso/bootmnt", "partuuid":"03c78dd9-01"}
         ]
      },
      {"name":"sr0", "maj:min":"11:0", "rm":true, "size":"1024M", "ro":false, "type":"rom", "mountpoint":null, "partuuid":null}
   ]
}
```
