### ISSUE TITLE
json.decoder.JSONDecodeError when formatting partitions larger than 2TB

### ISSUE THREAD

**Issue by DpoBoceka** [archlinux/archinstall#1567]
Trying to install on a server with 3.6TB storage:

```
root@archiso ~ # lsblk -l /dev/sda
NAME MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda    8:0    0  3.6T  0 disk
```

```
root@archiso ~ #  cat ./user_disk_layout.json
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "203MiB",
                "start": "3MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "206MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
```
The error output:
```
Press Enter to continue.
 ! Formatting [BlockDevice(/dev/sda, size=3726.0GB, free_space=4001GB, bus_type=sata)] in 5....4....3....2....1....
Creating a new partition label on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=3726.0GB, free_space=4001GB, bus_type=sata), 3MiB->203MiB
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 33, in <module>
    sys.exit(load_entry_point('archinstall==2.5.2', 'console_scripts', 'archinstall')())
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/__init__.py", line 307, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/examples/guided.py", line 311, in <module>
    perform_filesystem_operations()
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/examples/guided.py", line 126, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/filesystem.py", line 46, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/examples/guided.py", line 127, in perform_filesystem_operations
    fs.load_layout(archinstall.arguments['disk_layouts'][drive.path])
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/filesystem.py", line 91, in load_layout
    partition['device_instance'] = self.add_partition(partition.get('type', 'primary'),
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/filesystem.py", line 250, in add_partition
    self.blockdevice.flush_cache()
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/blockdevice.py", line 271, in flush_cache
    self._load_partitions()
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/blockdevice.py", line 131, in _load_partitions
    self._partitions[part_id] = Partition(root + part_id, block_device=self, part_id=part_id)
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/partition.py", line 101, in __init__
    self._partition_info = self._fetch_information()
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/partition.py", line 213, in _fetch_information
    sfdisk_info = self._call_sfdisk()
  File "/usr/lib/python3.10/site-packages/archinstall-2.5.2-py3.10.egg/archinstall/lib/disk/partition.py", line 200, in _call_sfdisk
    sfdisk_info = json.loads(output)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
```
root@archiso ~ # sfdisk --json /dev/sda
The size of this disk is 3.6 TiB (4000787030016 bytes). DOS partition table format cannot be used on drives for volumes larger than 2199023255040 bytes for 512-byte sectors. Use GUID partition table format (GPT).
{
   "partitiontable": {
      "label": "dos",
      "id": "0xdd4c2ebf",
      "device": "/dev/sda",
      "unit": "sectors",
      "sectorsize": 512,
      "partitions": [
         {
            "node": "/dev/sda1",
            "start": 6144,
            "size": 409600,
            "type": "c"
         }
      ]
   }
}

```

**Comment by svartkanin** [comment]
This is probably resolved by now
