### ISSUE TITLE
Archinstall no longer accessible with speakup

### ISSUE THREAD

**Issue by aaron-gh** [archlinux/archinstall#1601]
When using speakup, archinstall can no longer be navigated with the speakup screenreader.

Current behavior:

When navigating the arrow keys, the selected menu items are not read by speakup.

Expected behavior:

The highlighted item should be read by speakup.

Steps to reproduce:

    Boot the accessible installer, down arrow at the boot prompt and enter
    press capslock plus control plus 8 until "highlight tracking" is read
    type "archinstall" and use the arrow keys to navigate. Speech will either respond sometimes or not at all.

To see this working correctly, follow the above steps with an earlier version of archinstall, e.g. September 2022 is the version I used today to complete an install.

**Comment by svartkanin** [comment]
I think this is fixed in master already, if you can, would you mind trying that out?

**Comment by aaron-gh** [comment]
> I think this is fixed in master already, if you can, would you mind trying that out?

Hi,

I tried to build and then copy to an arch iso to try the install, using makepkg -s on an already installed system, but the pkgbuild seems to be fetching an old version, and failing SHA512 checksums.

I tried building with nuitka and it builds, but running ./archinstall after building says it cannot find the guided profile.

Am I missing a step?

thanks.

**Comment by svartkanin** [comment]
You don't have to build it, you just clone it from within the archiso 

```
git clone https://github...
cd archinstall
python -m archinstall
```
That should work fine

**Comment by dylanmtaylor** [comment]
Or you can download a built iso artifact from master

**Comment by aaron-gh** [comment]
After testing, it seems as though the keyboard navigation was indeed fixed.

However, the script still breaks. unsure if this is related. Don't see how it would be, but thought I'd report it here anyway just in case I'm missing something.

After selecting install, I get the following:

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/archinstall/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/root/archinstall/./archinstall/__init__.py", line 307, in run_as_a_module
    script.execute()
  File "/root/archinstall/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/archinstall/archinstall/examples/guided.py", line 311, in <module>
    perform_filesystem_operations()
  File "/root/archinstall/archinstall/examples/guided.py", line 126, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "/root/archinstall/archinstall/lib/disk/filesystem.py", line 46, in __exit__
    raise args[1]
  File "/root/archinstall/archinstall/examples/guided.py", line 127, in perform_filesystem_operations
    fs.load_layout(archinstall.arguments['disk_layouts'][drive.path])
  File "/root/archinstall/archinstall/lib/disk/filesystem.py", line 116, in load_layout
    if partition in disk_encryption.partitions:
AttributeError: 'NoneType' object has no attribute 'partitions'
python -m archinstall  8.81s user 4.79s system 4% cpu 5:18.06 total`

**Comment by svartkanin** [comment]
With the new menu WIth the new menu system https://github.com/archlinux/archinstall/pull/3997 this should hopefully be fixed. If there are still issues we can open a new issue with the concrete problem
