### ISSUE TITLE
Cannot install - when selecting Drive, get traceback error.

### ISSUE THREAD

**Issue by zlehnherr1** [archlinux/archinstall#1616]
When going to select disk, I get the following error:

> Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 301, in <module>
    ask_user_questions()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 107, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 336, in run
    if not self._process_selection(value):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 353, in _process_selection
    return self.exec_option(config_name, selector)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 373, in exec_option
    result = selector.func(presel_val)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 79, in <lambda>
    lambda preset: self._select_harddrives(preset),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 345, in _select_harddrives
    harddrives = select_harddrives(old_harddrives)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/system_conf.py", line 52, in select_harddrives
    hard_drives = all_blockdevices(partitions=False).values()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/helpers.py", line 275, in all_blockdevices
    instances[path] = BlockDevice(path, path_info)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 53, in __init__
    self._load_partitions()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 131, in _load_partitions
    self._partitions[part_id] = Partition(root + part_id, block_device=self, part_id=part_id)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 102, in __init__
    self._partition_info = self._fetch_information()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 214, in _fetch_information
    sfdisk_info = self._call_sfdisk()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 201, in _call_sfdisk
    sfdisk_info = json.loads(output)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>
[install (1).log](https://github.com/archlinux/archinstall/files/10365205/install.1.log)

**Comment by paolobettelini** [comment]
Had the same issue. archinstall is not able to decode the JSON produced by sfdisk.
I manually erased the other hard drives and then it worked.

**Comment by svartkanin** [comment]
There has been significant improvements done which aren't released yet. You can run a "pacman -S archinstall " or use the latest master

**Comment by paolobettelini** [comment]
@svartkanin I would like to note that I had the same issue yesterday with archinstall 2.5.6, which was the latest version found

**Comment by preland** [comment]
I had this issue as well using archinstall in a qemu vm. Even deleting the filesystem on the qcow drive did not fix the issue; i ended up creating a new drive and it worked fine after that.

If this had occurred on real hardware, I'm honestly not sure what I would've done

**Comment by svartkanin** [comment]
@paolobettelini version 2.5.6 is not master. Master is way ahead of that release

**Comment by svartkanin** [comment]
This is resolved in the latest release
