### ISSUE TITLE
I have this error when using archinstall 

### ISSUE THREAD

**Issue by nil-ref** [archlinux/archinstall#1624]
```
......
Enabling service fstrim.timer
['/usr/bin/arch-chroot', '/mnt/archinstall', 'mkinitcpio', '-P'] exited with abnormal exit code [256]: b'NG:\x1b(B\x1b[m \x1b[1mPossibly missing firmware for module: aic94xx\x1b(B\x1b[m\r\n\x1b[1m\x1b[33m==> WARNING:\x1b(B\x1b[m \x1b[1mPossibly missing firmware for module: bfa\x1b(B\x1b[m\r\n  \x1b[1m\x1b[34m->\x1b(B\x1b[m \x1b[1mRunning build hook: [filesystems]\x1b(B\x1b[m\r\n  \x1b[1m\x1b[34m->\x1b(B\x1b[m \x1b[1mRunning build hook: [fsck]\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mGenerating module dependencies\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mCreating zstd-compressed initcpio image: /boot/initramfs-linux-zen-fallback.img\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mImage generation successful\x1b(B\x1b[m\r\n'
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 316, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 141, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 160, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 195, in perform_installation
    if installation.minimal_installation(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 769, in minimal_installation
    self.mkinitcpio('-P')
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 663, in mkinitcpio
    return SysCommand(f'/usr/bin/arch-chroot {self.target} mkinitcpio {" ".join(flags)}').exit_code == 0
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 435, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 486, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 275, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code, worker=self)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'mkinitcpio', '-P'] exited with abnormal exit code [256]: b'NG:\x1b(B\x1b[m \x1b[1mPossibly missing firmware for module: aic94xx\x1b(B\x1b[m\r\n\x1b[1m\x1b[33m==> WARNING:\x1b(B\x1b[m \x1b[1mPossibly missing firmware for module: bfa\x1b(B\x1b[m\r\n  \x1b[1m\x1b[34m->\x1b(B\x1b[m \x1b[1mRunning build hook: [filesystems]\x1b(B\x1b[m\r\n  \x1b[1m\x1b[34m->\x1b(B\x1b[m \x1b[1mRunning build hook: [fsck]\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mGenerating module dependencies\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mCreating zstd-compressed initcpio image: /boot/initramfs-linux-zen-fallback.img\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mImage generation successful\x1b(B\x1b[m\r\n'
archinstall  26.80s user 52.81s system 10% cpu 12:38.61 total
```

This is my log:
```
root@archiso ~ # cat /var/log/archinstall/install.log
Hardware model detected: VMware, Inc. VMware Virtual Platform; UEFI mode: False
Processor model detected: AMD Ryzen 5 1600 Six-Core Processor
Memory statistics: 1316700 available out of 1985516 total installed
Virtualization detected: vmware; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '702.1M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '20G', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': None, 'uuid': 'FFFFFFFFFFFFFFFF', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '20G'}]}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202301', 'uuid': '2023-01-01-15-36-04-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '816.3M'}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Password strength: very weak
 * Passwords did not match *
Hardware model detected: VMware, Inc. VMware Virtual Platform; UEFI mode: False
Processor model detected: AMD Ryzen 5 1600 Six-Core Processor
Memory statistics: 1326584 available out of 1985516 total installed
Virtualization detected: vmware; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '702.1M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '20G', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': None, 'uuid': 'FFFFFFFFFFFFFFFF', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '20G'}]}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202301', 'uuid': '2023-01-01-15-36-04-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '816.3M'}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Marked partition as bootable because mountpoint was set to /boot.
Password strength: very weak
Not a valid directory: /tmp/config.json
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": null,
    "bootloader": "grub-install",
    "config_version": "2.5.1",
    "debug": false,
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "archlinux",
    "kernels": [
        "linux-zen"
    ],
    "keyboard-layout": "us",
    "mirror-region": {
        "China": {
            "http://mirror.lzu.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirror.redrock.team/archlinux/$repo/os/$arch": true,
            "http://mirrors.163.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.aliyun.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.bfsu.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.hit.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.nju.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.shanghaitech.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.wsyu.edu.cn/archlinux/$repo/os/$arch": true,
            "http://mirrors.zju.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirror.redrock.team/archlinux/$repo/os/$arch": true,
            "https://mirrors.aliyun.com/archlinux/$repo/os/$arch": true,
            "https://mirrors.bfsu.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.hit.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.nju.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.njupt.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.shanghaitech.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.sjtug.sjtu.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch": true,
            "https://mirrors.wsyu.edu.cn/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "iso"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/minimal.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": false,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "Asia/Taipei",
    "version": "2.5.1"
}
{
    "/dev/sda": {
        "partitions": [
            {
                "ESP": true,
                "PARTUUID": "ffffffff-01",
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "ntfs"
                },
                "mountpoint": "/",
                "size": 41940992,
                "start": 2048,
                "type": "primary",
                "wipe": false
            }
        ]
    }
}
Retrieving partition PARTUUID=None or UUID=ffffffff-01
uuid ffffffff-01 or None not found. Waiting 0s for next attempt
uuid ffffffff-01 or None not found. Waiting 1s for next attempt
uuid ffffffff-01 or None not found. Waiting 2s for next attempt
uuid ffffffff-01 or None not found. Waiting 3s for next attempt
uuid ffffffff-01 or None not found. Waiting 4s for next attempt
Could not find ffffffff-01/None in disk after 5 retries
Cache: {'1': Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs)}
Partitions: odict_items([('1', Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs))])
Retrieving partition PARTUUID=ffffffff-01 or UUID=None
Matched PARTUUID=ffffffff-01 against ffffffff-01
Re-using partition instance: Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs)
Marking partition Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs) as bootable.
Setting boot on on (parted) partition index 1
Mounting / to /mnt/archinstall/ using Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs)
Using mount order: [('/', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7f334d00a5f0>)]
Mounting Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs) to /mnt/archinstall/
Getting mount information for device path /mnt/archinstall
Filtering available mounts {PosixPath('/mnt/archinstall'): Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs, mounted=/mnt/archinstall)} to those under /mnt/archinstall
Available partitions: {PosixPath('/mnt/archinstall'): Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs, mounted=/mnt/archinstall)}
Waiting for automatic mirror selection (reflector) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Filtering available mounts {PosixPath('/mnt/archinstall'): Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs, mounted=/mnt/archinstall)} to those under /mnt/archinstall
Available partitions: {PosixPath('/mnt/archinstall'): Partition(path=/dev/sda1, size=20.0, PARTUUID=ffffffff-01, fs=ntfs, mounted=/mnt/archinstall)}
The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux-zen', 'grub']
Enabling periodic TRIM
Enabling service fstrim.timer
['/usr/bin/arch-chroot', '/mnt/archinstall', 'mkinitcpio', '-P'] exited with abnormal exit code [256]: b'NG:\x1b(B\x1b[m \x1b[1mPossibly missing firmware for module: aic94xx\x1b(B\x1b[m\r\n\x1b[1m\x1b[33m==> WARNING:\x1b(B\x1b[m \x1b[1mPossibly missing firmware for module: bfa\x1b(B\x1b[m\r\n  \x1b[1m\x1b[34m->\x1b(B\x1b[m \x1b[1mRunning build hook: [filesystems]\x1b(B\x1b[m\r\n  \x1b[1m\x1b[34m->\x1b(B\x1b[m \x1b[1mRunning build hook: [fsck]\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mGenerating module dependencies\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mCreating zstd-compressed initcpio image: /boot/initramfs-linux-zen-fallback.img\x1b(B\x1b[m\r\n\x1b[1m\x1b[32m==>\x1b(B\x1b[m \x1b[1mImage generation successful\x1b(B\x1b[m\r\n'
```

**Comment by svartkanin** [comment]
There have been a lot of changes and this may be resolved by now, if it happens again we can re-open it
