### ISSUE TITLE
"Drive(s)" menu doesn't work when using config file with `harddrives` key

### ISSUE THREAD

**Issue by Jackenmen** [archlinux/archinstall#1628]
Reproduction:
1. Create a file with these contents (you can replace `/dev/vda` with whatever block device name you have on your test machine):
```
{"harddrives": ["/dev/vda"]}
```
2. Run:
```
# archinstall --config repro.json
```
3. Choose the "Drive(s)" option.
4. See the error:
```
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 301, in <module>
    ask_user_questions()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 107, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 338, in run
    if not self._process_selection(value):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 355, in _process_selection
    return self.exec_option(config_name, selector)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 378, in exec_option
    result = selector.func(presel_val)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 79, in <lambda>
    lambda preset: self._select_harddrives(preset),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 345, in _select_harddrives
    harddrives = select_harddrives(old_harddrives)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/system_conf.py", line 60, in select_harddrives
    selected_harddrive = Menu(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/menu.py", line 190, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 716, in __init__
    convert_preselected_entries_to_indices(preselected_entries) if preselected_entries is not None else None
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/simple_menu.py", line 661, in convert_preselected_entries_to_indices
    raise ValueError('"preselected_entries" must either contain integers or strings.')
ValueError: "preselected_entries" must either contain integers or strings.
```

**Comment by svartkanin** [comment]
This is resolved in the latest release
