### ISSUE TITLE
How to set new encryption in JSON config?

### ISSUE THREAD

**Issue by rgrewe** [archlinux/archinstall#1665]
Could somebody give an example how to use the new encryption syntax within a preconfigured JSON config like https://github.com/archlinux/archinstall/blob/master/examples/disk_layouts-sample.json?

Is this even possible?

**Comment by Torxed** [comment]
Do we have a breaking change in the way `--disk-layout` works?

**Comment by rgrewe** [comment]
I am not sure.
Within our project we initialized the arguments via `archinstall.arguments = {...}`
We previously set encryption via `disk_layouts` as you mentioned, but now it seems we also need `disk_encryption` in the arguments.
For example here https://github.com/archlinux/archinstall/blob/v2.5.3/archinstall/lib/disk/filesystem.py#L114
It also needs to be an DiskEncryption object there.

I tried then something like this.
```
        "disk_encryption": archinstall.DiskEncryption(
            encryption_password="foo",
            encryption_type=archinstall.encryption.EncryptionType.Partition,
            partitions=[
                {   
                    "encrypted": True,
                    "generate-encryption-key-file": True,
                    "filesystem": {"format": "ext4", "mount_options": []},
                    "mountpoint": "/",
                    "size": "100%",
                    "start": "5120MiB",
                    "type": "primary",
                    "wipe": True
                }
            ],
            hsm_device=None
        ),
```
I had expected something like this here would be possible, plain JSON config.
```
        "disk_encryption": {
            "encryption_password": "foo",
            "encryption_type": archinstall.encryption.EncryptionType.Partition,
            "partitions": [
                {
                    "encrypted": True,
                    "generate-encryption-key-file": True,
                    "filesystem": {"format": "ext4", "mount_options": []},
                    "mountpoint": "/",
                    "size": "100%",
                    "start": "5120MiB",
                    "type": "primary",
                    "wipe": True
                }   
            ],
        },
```

**Comment by Torxed** [comment]
It should accept plain JSON, I'll have a look.
It's probably the re-work of the encryption menu not parsing JSON as it should.

**Comment by svartkanin** [comment]
Yeah the new encryption isn't saved atm, that has to be added

**Comment by rgrewe** [comment]
Hey guys! ^^
Can you give any ETA until this gets implemented? Would be nice. :-)

**Comment by svartkanin** [comment]
I'll try to get something in this week potentially

**Comment by svartkanin** [comment]
Yes absolutely, I do have that in mind :)
I'll see if I can find a non confusing way for it to be stored

**Comment by rgrewe** [comment]
@svartkanin 
I tested your PR also once. Created config files with archinstall and used them then as arguments with archinstall later.
I get an KeyError exception. Maybe it is the same bug as you have mentioned here. 
https://github.com/archlinux/archinstall/pull/1672#issuecomment-1461867535

I also added two print commands at https://github.com/svartkanin/archinstall/blob/save-enc-config/archinstall/lib/disk/filesystem.py#L115
First of `disk_encryption.all_partitions` and second of `partition`.
```
[{'encrypted': False, 'filesystem': {'format': 'ext4', 'mount_options': []}, 'mountpoint': '/', 'size': '100%', 'start': '513MiB', 'type': 'primary', 'wipe': True}]
{'encrypted': False, 'filesystem': {'format': 'ext4', 'mount_options': []}, 'mountpoint': '/', 'size': '100%', 'start': '513MiB', 'type': 'primary', 'wipe': True, 'device_instance': Partition(path=/dev/sda2, size=399.5, PARTUUID=6b8e38c3-d6a6-4d76-bc83-a068f51516d4, parent=/dev/sda, fs=crypto_LUKS)}
Formatting /dev/sda2 -> ext4
'device_instance'
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 308, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 320, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 137, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 162, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 141, in perform_installation
    installation.mount_ordered_layout(archinstall.arguments['disk_layouts'])
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 252, in mount_ordered_layout
    loopdev = f"{storage.get('ENC_IDENTIFIER', 'ai')}{pathlib.Path(partition['device_instance'].path).name}"
KeyError: 'device_instance'
```

**Comment by svartkanin** [comment]
Yes that's the bug, when neutralizing, the references are lost to the other partition objects.
