### ISSUE TITLE
Could not install GRUB to /dev/md126p1

### ISSUE THREAD

**Issue by thedgm** [archlinux/archinstall#1667]
```bash
# archinstall
...
grub-install: info: no LVM signature found.
grub-install: info: drive = -1.
grub-install: error: disk `md126,1' not found.

Could not install GRUB to /dev/md126p1: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-install', '--debug', '--target=i386-pc', '--recheck', '/dev/md126'] exited with abnormal exit code [256]: b"r mdraid09 devices on disk hostdisk//dev/sda.\r\ngrub-install: info: Scanning for dmraid_nv devices on disk hostdisk//dev/sda.\r\ngrub-install: info: Scanning for ldm devices on disk hostdisk//dev/sda.\r\ngrub-install: info: scanning hostdisk//dev/sda for LDM.\r\ngrub-install: info: no LDM signature found.\r\ngrub-install: info: Scanning for lvm devices on disk hostdisk//dev/sda.\r\ngrub-install: info: no LVM signature found.\r\ngrub-install: info: drive = -1.\r\ngrub-install: error: disk `md126,1' not found.\r\n"
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 932, in add_grub_bootloader
    SysCommand(f'/usr/bin/arch-chroot {self.target} grub-install --debug --target=i386-pc --recheck {boot_partition.parent}', peak_output=True)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 435, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 486, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 275, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code, worker=self)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-install', '--debug', '--target=i386-pc', '--recheck', '/dev/md126'] exited with abnormal exit code [256]: b"r mdraid09 devices on disk hostdisk//dev/sda.\r\ngrub-install: info: Scanning for dmraid_nv devices on disk hostdisk//dev/sda.\r\ngrub-install: info: Scanning for ldm devices on disk hostdisk//dev/sda.\r\ngrub-install: info: scanning hostdisk//dev/sda for LDM.\r\ngrub-install: info: no LDM signature found.\r\ngrub-install: info: Scanning for lvm devices on disk hostdisk//dev/sda.\r\ngrub-install: info: no LVM signature found.\r\ngrub-install: info: drive = -1.\r\ngrub-install: error: disk `md126,1' not found.\r\n"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 307, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 320, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 137, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 162, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 209, in perform_installation
    installation.add_bootloader(archinstall.arguments["bootloader"])
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 1030, in add_bootloader
    self.add_grub_bootloader(boot_partition, root_partition)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 934, in add_grub_bootloader
    raise DiskError(f"Could not install GRUB to {boot_partition.path}: {error}")
archinstall.lib.exceptions.DiskError: Could not install GRUB to /dev/md126p1: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-install', '--debug', '--target=i386-pc', '--recheck', '/dev/md126'] exited with abnormal exit code [256]: b"r mdraid09 devices on disk hostdisk//dev/sda.\r\ngrub-install: info: Scanning for dmraid_nv devices on disk hostdisk//dev/sda.\r\ngrub-install: info: Scanning for ldm devices on disk hostdisk//dev/sda.\r\ngrub-install: info: scanning hostdisk//dev/sda for LDM.\r\ngrub-install: info: no LDM signature found.\r\ngrub-install: info: Scanning for lvm devices on disk hostdisk//dev/sda.\r\ngrub-install: info: no LVM signature found.\r\ngrub-install: info: drive = -1.\r\ngrub-install: error: disk `md126,1' not found.\r\n"
archinstall  77.69s user 70.68s system 11% cpu 20:46.38 total
1 root@archiso ~ #  
```

Collected [install.log](https://github.com/archlinux/archinstall/files/10891353/install.log)

Gathering facts further:
```
root@archiso ~ # 
root@archiso ~ # lsblk -a
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0         7:0    0 688.5M  1 loop  /run/archiso/airootfs
sda           8:0    0 465.8G  0 disk  
├─md126       9:126  0 931.5G  0 raid5 
│ ├─md126p1 259:0    0   200M  0 part  /mnt/archinstall/boot
│ └─md126p2 259:1    0 931.3G  0 part  /mnt/archinstall
└─md127       9:127  0     0B  0 md    
sdb           8:16   0 465.8G  0 disk  
├─md126       9:126  0 931.5G  0 raid5 
│ ├─md126p1 259:0    0   200M  0 part  /mnt/archinstall/boot
│ └─md126p2 259:1    0 931.3G  0 part  /mnt/archinstall
└─md127       9:127  0     0B  0 md    
sdc           8:32   0 465.8G  0 disk  
├─md126       9:126  0 931.5G  0 raid5 
│ ├─md126p1 259:0    0   200M  0 part  /mnt/archinstall/boot
│ └─md126p2 259:1    0 931.3G  0 part  /mnt/archinstall
└─md127       9:127  0     0B  0 md    
sr0          11:0    1  1024M  0 rom   
root@archiso ~ # 
root@archiso ~ # lsblk --fs
NAME        FSTYPE          FSVER  LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop0       squashfs        4.0                                                     0   100% /run/archiso/airootfs
sda         isw_raid_member 1.2.02                                                           
├─md126                                                                                      
│ ├─md126p1 vfat            FAT32        7D43-8EB9                             126.6M    36% /mnt/archinstall/boot
│ └─md126p2 ext4            1.0          66a6a64d-3192-40d9-8752-5d1bce444dfa  867.2G     0% /mnt/archinstall
└─md127                                                                                      
sdb         isw_raid_member 1.2.02                                                           
├─md126                                                                                      
│ ├─md126p1 vfat            FAT32        7D43-8EB9                             126.6M    36% /mnt/archinstall/boot
│ └─md126p2 ext4            1.0          66a6a64d-3192-40d9-8752-5d1bce444dfa  867.2G     0% /mnt/archinstall
└─md127                                                                                      
sdc         isw_raid_member 1.2.02                                                           
├─md126                                                                                      
│ ├─md126p1 vfat            FAT32        7D43-8EB9                             126.6M    36% /mnt/archinstall/boot
│ └─md126p2 ext4            1.0          66a6a64d-3192-40d9-8752-5d1bce444dfa  867.2G     0% /mnt/archinstall
└─md127                                                                                      
sr0                                                                                          
root@archiso ~ #  
root@archiso ~ # cat /proc/mdstat 
Personalities : [raid6] [raid5] [raid4] 
md126 : active raid5 sda[2] sdb[1] sdc[0]
      976768000 blocks super external:/md127/0 level 5, 64k chunk, algorithm 0 [3/3] [UUU]
      [=====>...............]  resync = 27.3% (133569228/488384000) finish=124.0min speed=47651K/sec
      
md127 : inactive sda[2](S) sdb[1](S) sdc[0](S)
      7752 blocks super external:imsm
       
unused devices: <none>
root@archiso ~ # 
root@archiso ~ # lspci -tv
-[0000:00]-+-00.0  Intel Corporation 2nd Generation Core Processor Family DRAM Controller
           +-02.0  Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller
           +-16.0  Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1
           +-19.0  Intel Corporation 82579LM Gigabit Network Connection (Lewisville)
           +-1a.0  Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2
           +-1b.0  Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller
           +-1d.0  Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1
           +-1e.0-[01]--
           +-1f.0  Intel Corporation Q67 Express Chipset LPC Controller
           +-1f.2  Intel Corporation SATA Controller [RAID mode]
           \-1f.3  Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller
root@archiso ~ # 
root@archiso ~ # mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
dev on /dev type devtmpfs (rw,nosuid,relatime,size=3958696k,nr_inodes=989674,mode=755,inode64)
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755,inode64)
httpspace on /run/archiso/httpspace type tmpfs (rw,relatime,size=6002908k,mode=755,inode64)
copytoram on /run/archiso/copytoram type tmpfs (rw,relatime,size=6002908k,mode=755,inode64)
cowspace on /run/archiso/cowspace type tmpfs (rw,relatime,size=262144k,mode=755,inode64)
/dev/loop0 on /run/archiso/airootfs type squashfs (ro,relatime,errors=continue,threads=single)
airootfs on / type overlay (rw,relatime,lowerdir=/run/archiso/airootfs,upperdir=/run/archiso/cowspace/persistent_/x86_64/upperdir,workdir=/run/archiso/cowspace/persistent_/x86_64/workdir)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=34,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=2907)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,size=4001940k,nr_inodes=1048576,inode64)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-firstboot.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-sysctl.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /run/credentials/systemd-tmpfiles-setup-dev.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /etc/pacman.d/gnupg type ramfs (rw,relatime)
ramfs on /run/credentials/systemd-tmpfiles-setup.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /run/credentials/systemd-resolved.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=800384k,nr_inodes=200096,mode=700,inode64)
/dev/md126p2 on /mnt/archinstall type ext4 (rw,relatime,stripe=32)
/dev/md126p1 on /mnt/archinstall/boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
root@archiso ~ # ls -la /mnt/archinstall/boot 
total 66877
drwxr-xr-x  3 root root      512 Jan  1  1970 .
drwxr-xr-x 17 root root     4096 Mar  5 07:46 ..
drwxr-xr-x  6 root root      512 Mar  5 07:56 grub
-rwxr-xr-x  1 root root 10357796 Mar  5 07:47 initramfs-linux.img
-rwxr-xr-x  1 root root 38540258 Mar  5 07:47 initramfs-linux-fallback.img
-rwxr-xr-x  1 root root  7066624 Feb 15 00:22 intel-ucode.img
-rwxr-xr-x  1 root root 12511392 Mar  5 07:46 vmlinuz-linux
root@archiso ~ # 
```

**Comment by svartkanin** [comment]
There were a lot of changes recently and this should be resolved in the most recent release
