### ISSUE TITLE
Python error on Arch32

### ISSUE THREAD

**Issue by coreybruce** [archlinux/archinstall#1686]
Hey I just wanted to report a issue, I am using Arch32 on a old laptop and arch32 has archinstall-2.5.2-1.2 on the repos but I get this error when I try and run it 

```
root@archiso ~ # archinstall
Testing connectivity to the Arch Linux mirrors ...
Updating archlinux32-keyring ...
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 307, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 296, in <module>
    archinstall.installed_package('archlinux-keyring').version < latest_version_archlinux_keyring:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/packages/packages.py", line 115, in installed_package
    return LocalPackage(**package_info)
TypeError: LocalPackage.__init__() missing 21 required positional arguments: 'name', 'version', 'description', 'architecture', 'url', 'licenses', 'groups', 'depends_on', 'optional_deps', 'required_by', 'optional_for', 'conflicts_with', 'replaces', 'installed_size', 'packager', 'build_date', 'install_date', 'install_reason', 'install_script', 'validated_by', and 'provides
```

**Comment by NIYAZ04** [comment]
Pacman -Sy archinstall This command solved the problem for me ..

**Comment by webbb82** [comment]
this is still a issue a month later all for 6 bits of code
...hon3.10/site-packages/archinstall/lib/configuration.py Modified
 1 - if key == 'disk_encryption': turn this 
 2 + if key == 'disk_encryption' and self._config[key] into this

**Comment by Shenghongzhong** [comment]
Same here. 

pacman -Sy archinstall 

And run archinstall again

**Comment by softerdk** [comment]
Yes ditto here
pacman -Sy archinstall
And run archinstall again
then all is fine.

**Comment by coreybruce** [comment]
Working but I did notice a lot of there warning messages
 
![IMG20230424210853](https://user-images.githubusercontent.com/8393780/233980400-c109bc7f-65ca-436e-a4b3-d9ee7c5d3dc5.jpg)

**Comment by machielvdb** [comment]
For anyone still having this issue after using pacman -Sy archinstall, pacman -S dosfstools fixed it for me

**Comment by Torxed** [comment]
These errors feel very odd, as they appear to be isolated to the 32bit version.
Is the 32bit release not comaptabile with fat32?

**Comment by svartkanin** [comment]
I think this is fixed by now :)

**Comment by SkeJm** [comment]
unfortunately same issue right now:
`File "/usr/bin/archinstall", line 5, in <module>
from archinstall import run_as_a_module
File "/usr/lib/python/3.11/site-packages/archinstall/__init__.py", line 5, in <module>
from .lib.disk import *
ModuleNotFoundError: No module named 'archinstall.lib'`

**Comment by Torxed** [comment]
This looks like a really old Python version tho, something we no longer build against.

**Comment by svartkanin** [comment]
The minimum required version is 3.12.
