### ISSUE TITLE
Configuration File Error - NetworkConfigurationHandler not defined

### ISSUE THREAD

**Issue by bd-g** [archlinux/archinstall#1761]
## Description

When saving a configuration file, and attempted to launch archinstall with those files passed to `--config` and `--creds`, there appears to be a mismatch between some config naming and the internals. Looks like a class got renamed in the PyParted switch

## Version

Archinstall commit 00b0ae7ba439a5a420095175b3bedd52c569db51

## Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/testing/archinstall/archinstall/__main__.py", line 14, in <module>
    spec.loader.exec_module(archinstall)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/testing/archinstall/./archinstall/__init__.py", line 243, in <module>
    post_process_arguments(arguments)
  File "/media/testing/archinstall/./archinstall/__init__.py", line 238, in post_process_arguments
    load_config()
  File "/media/testing/archinstall/./archinstall/__init__.py", line 206, in load_config
    handler = NetworkConfigurationHandler()
NameError: name 'NetworkConfigurationHandler' is not defined. Did you mean: 'NetworkConfiguration'?
```

## Configuration Files Used

`user_configuration.json`

```
{
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": "pipewire",
    "bootloader": "Systemd-boot",
    "config_version": "2.5.4",
    "debug": false,
    "disk_config": {
        "config_type": "manual_partitioning",
        "device_modifications": [
            {
                "device": "/dev/nvme0n1",
                "partitions": [
                    {
                        "btrfs": [],
                        "flags": [
                            "Boot"
                        ],
                        "fs_type": "fat32",
                        "length": {
                            "sector_size": null,
                            "total_size": null,
                            "unit": "MiB",
                            "value": 512
                        },
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "{redacted}",
                        "start": {
                            "sector_size": null,
                            "total_size": null,
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [
                            {
                                "compress": false,
                                "mountpoint": "/",
                                "name": "@",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/home",
                                "name": "@home",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/var/log",
                                "name": "@log",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/var/cache/pacman/pkg",
                                "name": "@pkg",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/.snapshots",
                                "name": "@.snapshots",
                                "nodatacow": false
                            }
                        ],
                        "flags": [],
                        "fs_type": "btrfs",
                        "length": {
                            "sector_size": null,
                            "total_size": {
                                "sector_size": null,
                                "total_size": null,
                                "unit": "B",
                                "value": 1000204886016
                            },
                            "unit": "Percent",
                            "value": 100
                        },
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": null,
                        "obj_id": "{redacted}}",
                        "start": {
                            "sector_size": null,
                            "total_size": null,
                            "unit": "MiB",
                            "value": 513
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": {
        "encryption_type": "partition",
        "partitions": [
            "{redacted}}"
        ]
    },
    "hostname": "tmp-hostname",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {
        "United States": {
            "http://arch.hu.fo/archlinux/$repo/os/$arch": true,
            "http://arch.mirror.constant.com/$repo/os/$arch": true,
            "http://archmirror1.octyl.net/$repo/os/$arch": true,
            "http://arlm.tyzoid.com/$repo/os/$arch": true,
            "http://codingflyboy.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://coresite.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://dfw.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "http://distro.ibiblio.org/archlinux/$repo/os/$arch": true,
            "http://forksystems.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://ftp.osuosl.org/pub/archlinux/$repo/os/$arch": true,
            "http://iad.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "http://iad.mirrors.misaka.one/archlinux/$repo/os/$arch": true,
            "http://irltoolkit.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://mirror.arizona.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.clarkson.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.cs.vt.edu/pub/ArchLinux/$repo/os/$arch": true,
            "http://mirror.dal10.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirror.fcix.net/archlinux/$repo/os/$arch": true,
            "http://mirror.fossable.org/archlinux/$repo/os/$arch": true,
            "http://mirror.hackingand.coffee/arch/$repo/os/$arch": true,
            "http://mirror.lty.me/archlinux/$repo/os/$arch": true,
            "http://mirror.math.princeton.edu/pub/archlinux/$repo/os/$arch": true,
            "http://mirror.metrocast.net/archlinux/$repo/os/$arch": true,
            "http://mirror.mia11.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirror.phx1.us.spryservers.net/archlinux/$repo/os/$arch": true,
            "http://mirror.pit.teraswitch.com/archlinux/$repo/os/$arch": true,
            "http://mirror.sfo12.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirror.siena.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.stephanie.is/archlinux/$repo/os/$arch": true,
            "http://mirror.stjschools.org/arch/$repo/os/$arch": true,
            "http://mirror.umd.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.vtti.vt.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.wdc1.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirrors.acm.wpi.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.advancedhosters.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.bloomu.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.cat.pdx.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.gigenet.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.kernel.org/archlinux/$repo/os/$arch": true,
            "http://mirrors.lug.mtu.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.mit.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.radwebhosting.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.rit.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.rutgers.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.sonic.net/archlinux/$repo/os/$arch": true,
            "http://mirrors.vectair.net/archlinux/$repo/os/$arch": true,
            "http://mirrors.xmission.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.xtom.com/archlinux/$repo/os/$arch": true,
            "http://mnvoip.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://nnenix.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://ord.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "http://plug-mirror.rcac.purdue.edu/archlinux/$repo/os/$arch": true,
            "http://repo.ialab.dsu.edu/archlinux/$repo/os/$arch": true,
            "http://ridgewireless.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://southfront.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://uvermont.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://wcbmedia.io:8000/$repo/os/$arch": true,
            "http://www.gtlib.gatech.edu/pub/archlinux/$repo/os/$arch": true,
            "http://ziply.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://america.mirror.pkgbuild.com/$repo/os/$arch": true,
            "https://arch.hu.fo/archlinux/$repo/os/$arch": true,
            "https://arch.mirror.constant.com/$repo/os/$arch": true,
            "https://arch.mirror.ivo.st/$repo/os/$arch": true,
            "https://archmirror1.octyl.net/$repo/os/$arch": true,
            "https://arlm.tyzoid.com/$repo/os/$arch": true,
            "https://codingflyboy.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://coresite.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://dfw.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://forksystems.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://ftp.osuosl.org/pub/archlinux/$repo/os/$arch": true,
            "https://iad.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://iad.mirrors.misaka.one/archlinux/$repo/os/$arch": true,
            "https://irltoolkit.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://m.lqy.me/arch/$repo/os/$arch": true,
            "https://mirror.arizona.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.clarkson.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.dal10.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.fcix.net/archlinux/$repo/os/$arch": true,
            "https://mirror.hackingand.coffee/arch/$repo/os/$arch": true,
            "https://mirror.lty.me/archlinux/$repo/os/$arch": true,
            "https://mirror.mia11.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.phx1.us.spryservers.net/archlinux/$repo/os/$arch": true,
            "https://mirror.pit.teraswitch.com/archlinux/$repo/os/$arch": true,
            "https://mirror.sfo12.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.stephanie.is/archlinux/$repo/os/$arch": true,
            "https://mirror.stjschools.org/arch/$repo/os/$arch": true,
            "https://mirror.theash.xyz/arch/$repo/os/$arch": true,
            "https://mirror.tmmworkshop.com/archlinux/$repo/os/$arch": true,
            "https://mirror.umd.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.wdc1.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.zackmyers.io/archlinux/$repo/os/$arch": true,
            "https://mirror2.sandyriver.net/pub/archlinux/$repo/os/$arch": true,
            "https://mirrors.bloomu.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.kernel.org/archlinux/$repo/os/$arch": true,
            "https://mirrors.lug.mtu.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.mit.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.radwebhosting.com/archlinux/$repo/os/$arch": true,
            "https://mirrors.rit.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.sonic.net/archlinux/$repo/os/$arch": true,
            "https://mirrors.vectair.net/archlinux/$repo/os/$arch": true,
            "https://mirrors.xtom.com/archlinux/$repo/os/$arch": true,
            "https://mnvoip.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://nnenix.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://ord.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://plug-mirror.rcac.purdue.edu/archlinux/$repo/os/$arch": true,
            "https://repo.ialab.dsu.edu/archlinux/$repo/os/$arch": true,
            "https://ridgewireless.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://southfront.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://uvermont.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://ziply.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://zxcvfdsa.com/arch/$repo/os/$arch": true
        }
    },
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "firefox"
    ],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "All open-source (default)",
        "greeter": "gdm",
        "profile": {
            "details": [
                "Sway"
            ],
            "main": "Desktop"
        }
    },
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "America/New_York",
    "version": "2.5.4"
}
```

`user_credentials.json`

```
{
    "!users": [
        {
            "sudo": true,
            "username": "tmp"
        }
    ],
    "encryption_password": "{redacted}"
}
```

**Comment by bd-g** [comment]
Resolved by #1764
