### ISSUE TITLE
Installer aborting showing error 'ProfileConfiguration' object has no attribute 'is_desktop_type_profile'

### ISSUE THREAD

**Issue by stallonen** [archlinux/archinstall#1772]
Hello, I built an arch iso by using the provided build_iso script, and upon trying to install from the iso with the desktop profile, I am getting the error `'ProfileConfiguration' object has no attribute 'is_desktop_type_profile'`. 

Here's the traceback 

```
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 265, in run_as_a_module
    importlib.import_module(mod_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/scripts/guided.py", line 276, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.10/site-packages/archinstall/scripts/guided.py", line 135, in perform_installation
    with Installer(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 159, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/scripts/guided.py", line 184, in perform_installation
    handler.config_installer(installation)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/models/network_configuration.py", line 96, in config_installer
    if (profile := storage['arguments'].get('profile_config')) and profile.is_desktop_type_profile:
AttributeError: 'ProfileConfiguration' object has no attribute 'is_desktop_type_profile'
```

Here is the install log:- [logfile](https://0x0.st/HKC4.log)

**Comment by svartkanin** [comment]
Thanks for reporting, I raised a PR to fix the issue

**Comment by Torxed** [comment]
Fixed in the PR mentioned above :) Great work both of you!
