### ISSUE TITLE
Enabling service f, but service f doesn't exist 

### ISSUE THREAD

**Issue by stallonen** [archlinux/archinstall#1778]
installation exits with `Unable to start service f: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'systemctl', 'enable', 'f'] exited with abnormal exit code [1]: b''`

Here's the traceback 

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 577, in enable_service
    self.arch_chroot(f'systemctl enable {service}')
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 592, in arch_chroot
    return self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 586, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 448, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 499, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 275, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'systemctl', 'enable', 'f'] exited with abnormal exit code [1]: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 266, in run_as_a_module
    importlib.import_module(mod_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/scripts/guided.py", line 279, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.10/site-packages/archinstall/scripts/guided.py", line 135, in perform_installation
    with Installer(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 137, in __exit__
    raise exc_val
  File "/usr/lib/python3.10/site-packages/archinstall/scripts/guided.py", line 159, in perform_installation
    installation.minimal_installation(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 773, in minimal_installation
    self.enable_periodic_trim()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 568, in enable_periodic_trim
    self.enable_service("fstrim.timer")
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 579, in enable_service
    raise ServiceException(f"Unable to start service {service}: {error}")
archinstall.lib.exceptions.ServiceException: Unable to start service f: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'systemctl', 'enable', 'f'] exited with abnormal exit code [1]: b''
archinstall  59.25s user 37.90s system 27% cpu 5:48.21 total
```

Here is the log :- [logfile](https://bpa.st/TISAQ)

**Comment by Torxed** [comment]
Thank you for reporting this, I believe it is fixed in #1779.
