### ISSUE TITLE
Installer crashes at creating partitions 

### ISSUE THREAD

**Issue by stallonen** [archlinux/archinstall#1789]
Here is the traceback 

```
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 266, in run_as_a_module
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 274, in <module>
    fs_handler.perform_filesystem_operations()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/filesystem.py", line 55, in perform_filesystem_operations
    device_handler.partition(mod, partition_table=partition_table)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 489, in partition
    self._perform_partitioning(part_mod, modification.device, disk, requires_delete=requires_delete)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 333, in _perform_partitioning
    disk.commit()
  File "/usr/lib/python3.11/site-packages/parted/decorators.py", line 42, in new
    ret = fn(*args, **kwds)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/parted/disk.py", line 212, in commit
    return self.__disk.commit()
           ^^^^^^^^^^^^^^^^^^^^
_ped.IOException: Partition(s) 3 on /dev/sda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
```

Here's the [logfile](https://bpa.st/J6YBA) 

If this is a python 3.11 issue, can someone guide me on how to use python 3.10?

**Comment by svartkanin** [comment]
@stallonen is this the version from the latest master? 
Also did you run it multiple times or maybe perform any disk operations manually beforehand?

**Comment by stallonen** [comment]
> @stallonen is this the version from the latest master?
> Also did you run it multiple times or maybe perform any disk operations manually beforehand?


Yes, this is the version from the latest master. 
No, I didn't run it multiple times, the error popped out in the first time run, and no, I didn't perform any disk operations manually beforehand.

**Comment by svartkanin** [comment]
Would you mind restarting the device and try running it again

**Comment by Torxed** [comment]
It also looks like you're running v2.5.4, could you upgrade with `pacman -Syu archinstall`? Or maybe the log is just a bit outdated when we print the version?

**Comment by svartkanin** [comment]
@Torxed I think it's the latest master being run, it seems the actual `__version` hasn't been updated https://github.com/archlinux/archinstall/blob/master/archinstall/__init__.py#L33

**Comment by stallonen** [comment]
> Would you mind restarting the device and try running it again

I did so, and it worked! Any idea on why it might not have worked the first time?

**Comment by svartkanin** [comment]
Have you done any kernel updates recently? 
I saw this error sometimes when I run a system update on my laptop without rebooting afterwards

**Comment by stallonen** [comment]
> Have you done any kernel updates recently?
> I saw this error sometimes when I run a system update on my laptop without rebooting afterwards

No,I haven't. It seems like a one off issue. I have run the installer multiple times after the post, and each time it has worked perfectly.

**Comment by svartkanin** [comment]
Thanks for confirming, I think we can close the issue for the time being and reopen it if it happens again

**Comment by stallonen** [comment]
Yes, I am closing the issue with this comment.

**Comment by chrishoage** [comment]
Sorry to necro and old post, this just happened to me, and a reboot fixed it. 

I know this isn't super helpful, as there is no steps to reproduce. 

Just wanted to offer that this is still sometimes an issue. 

For anyone coming to this thread from a search engine, rebooting does seem to fix this bad state.
