### ISSUE TITLE
'Device' object has no attribute 'device_info'

### ISSUE THREAD

**Issue by stallonen** [archlinux/archinstall#1793]
Here is the traceback

```
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 266, in run_as_a_module
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 276, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 135, in perform_installation
    with Installer(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 137, in __exit__
    raise exc_val
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 173, in perform_installation
    installation.add_bootloader(archinstall.arguments["bootloader"])
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 1069, in add_bootloader
    self._add_grub_bootloader(boot_partition, root_partition)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 958, in _add_grub_bootloader
    f' --recheck {device.device_info.path}'
                  ^^^^^^^^^^^^^^^^^^

```

Here's the [log](https://bpa.st/JS2K6)

**Comment by svartkanin** [comment]
Yep that's a bug, thanks for reporting

**Comment by stallonen** [comment]
I just checked after locally applying PR1794, and it indeed fixes the bug. I am closing this issue.

**Comment by svartkanin** [comment]
Awesome thanks for verifying
