### ISSUE TITLE
Bootloader option is not saved to configuration causing a crash

### ISSUE THREAD

**Issue by peracchi** [archlinux/archinstall#1853]
Made an install on a Proxmox VM.

Saved json configs.

Tried to replay install using saved json configs with
`archinstall --config user_configuration.json --creds user_credentials.json --disk_layouts user_disk_layout.json --silent`
and failed.

I thought that was because disk was already partitioned and then
`sgdisk --zap-all /dev/sda`
and tried again. Same error.

The error:
```
==> Image generation successful
(12/14) Reloading system bus configuration...
  Skipped: Running in chroot.
(13/14) Warn about old perl modules
(14/14) Updating the info directory file...


Enabling service fstrim.timer
'bootloader'
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 312, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 306, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 137, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 163, in __exit__
    raise args[1]
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 209, in perform_installation
    installation.add_bootloader(archinstall.arguments["bootloader"])
                                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'bootloader'
```

**Comment by codefiles** [comment]
What is the bootloader in the `user_configuration.json` you are using?

A KeyError exception occurs when a dictionary key that does not exist is accessed. In v2.5.6 and master if `archinstall.arguments["bootloader']` does not exist this exception is raised when it is accessed.

**v2.5.6**

https://github.com/archlinux/archinstall/blob/cbd466412795a7aec15f0be2bce781a21042969e/examples/guided.py#L209

**master**

https://github.com/archlinux/archinstall/blob/5087c86263c39bb13585c326c14f1f890900f42f/archinstall/scripts/guided.py#L157

**Comment by peracchi** [comment]
I choosed "grub-install" as bootloader (it was the default option, I do not changed).

```
Set/Modify the below options

  Archinstall language           set: English (100%)
  Keyboard layout                set: us-acentos
  Mirror region                  set: ['Brazil']
  Locale language                set: en_US
  Locale encoding                set: utf-8
  Drive(s)                       set: 1 Drive(s)
  Disk layout                    set: 2 Partitions
  Disk encryption                set: Partition encryption
> Bootloader                     set: grub-install
  Swap                           set: True
  Hostname                       set: arch-vps
  Root password                  set: None
  User account                   set: 2 User(s)
  Profile                        set: Profile(minimal.py)
  Audio                          set: None
  Kernels                        set: ['linux']
  Additional packages            set: ['git', 'nano', 'openssh', 'qemu-guest-agent', 'vim']
  Network configuration          set: Copy ISO configuration
  Timezone                       set: America/Sao_Paulo
  Automatic time sync (NTP)      set: True
  Optional repositories          set: []

  Save configuration
  Install
  Abort
(Press "/" to search)
```



Below are the contents of the files generated and saved when I made the first install using **archinstall**.

**user_configuration.json**
```
{
    "config_version": "2.5.6",
    "debug": false,
    "disk_encryption": {
        "encryption_type": "partition",
        "partitions": {
            "/dev/sda": [
                {
                    "encrypted": false,
                    "filesystem": {
                        "format": "ext4",
                        "mount_options": []
                    },
                    "mountpoint": "/",
                    "size": "100%",
                    "start": "206MiB",
                    "type": "primary",
                    "wipe": true
                }
            ]
        }
    },
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "arch-vps",
    "keyboard-layout": "us-acentos",
    "mirror-region": {
        "Brazil": {
            "http://archlinux.c3sl.ufpr.br/$repo/os/$arch": true,
            "http://linorg.usp.br/archlinux/$repo/os/$arch": true,
            "http://mirror.ufscar.br/archlinux/$repo/os/$arch": true,
            "https://mirror.ufscar.br/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "iso"
    },
    "no_pkg_lookups": false,
    "offline": false,
    "packages": [
        "git",
        "nano",
        "openssh",
        "qemu-guest-agent",
        "vim"
    ],
    "profile": {
        "path": "/usr/lib/python3.11/site-packages/archinstall/profiles/minimal.py"
    },
    "script": "guided",
    "silent": false,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "America/Sao_Paulo",
    "version": "2.5.6"
}
```

**user_credentials.json**
```
{
    "!users": [
        {
            "sudo": true,
            "username": "admin"
        },
        {
            "sudo": true,
            "username": "peracchi"
        }
    ],
    "encryption_password": "my-secret-password-for-disk-encryption"
}
```

**user_disk_layout.json**
```
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "203MiB",
                "start": "3MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "206MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
```

**Comment by Torxed** [comment]
We should probably do a `.get("bootloader", DEFAULT_BOOTLOADER)` here.

**Comment by codefiles** [comment]
There are use cases where installing a bootloader may not be desired. Maybe rather than set defaults do the following.

```python
if bootloader := archinstall.arguments.get('bootloader', None):
	installation.add_bootloader(bootloader)
```

It looks like the bootloader that was shown in the guided installer was not saved to the config file. That is the root cause.

**Comment by peracchi** [comment]
> It looks like the bootloader that was shown in the guided installer was not saved to the config file. That is the root cause.

Yes, I manually added `"bootloader": "grub-install",` to `user_configuration.json` and the installation worked.

But I discovered another problem: I can't login because apparently user's passwords were not saved to `user_credentials.json` and not used on installation process.

**Comment by codefiles** [comment]
> But I discovered another problem: I can't login because apparently user's passwords were not saved to `user_credentials.json` and not used on installation process.

Yep. I advise creating a new issue for that and rewording the title of this one.

**Comment by svartkanin** [comment]
This should be resolved
