### ISSUE TITLE
Archinstall error choose driver

### ISSUE THREAD

**Issue by maxfact** [archlinux/archinstall#1855]
Good evening
when i try to install archlinux with archinstall, i get to choose disks and i get this error:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 312, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 291, in <module>
    ask_user_questions()
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 103, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/menu/abstract_menu.py", line 340, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/menu/abstract_menu.py", line 357, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/menu/abstract_menu.py", line 377, in exec_option
    result = selector.func(presel_val)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/menu/global_menu.py", line 79, in <lambda>
    lambda preset: self._select_harddrives(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/menu/global_menu.py", line 355, in _select_harddrives
    harddrives = select_harddrives(old_harddrives)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/user_interaction/system_conf.py", line 52, in select_harddrives
    hard_drives = all_blockdevices(partitions=False).values()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/helpers.py", line 294, in all_blockdevices
    instances[path] = BlockDevice(path, path_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/blockdevice.py", line 53, in __init__
    self._load_partitions()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/blockdevice.py", line 131, in _load_partitions
    self._partitions[part_id] = Partition(root + part_id, block_device=self, part_id=part_id)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/partition.py", line 102, in __init__
    self._partition_info = self._fetch_information()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/partition.py", line 220, in _fetch_information
    sfdisk_info = self._call_sfdisk()
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/partition.py", line 207, in _call_sfdisk
    sfdisk_info = json.loads(output)
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I used the latest arch iso downloaded from the site

**Comment by svartkanin** [comment]
There has been alot of updates and I suspect that using the latest master will kot have this bug anymore

**Comment by maxfact** [comment]
Thanks for the reply

Could you try archinstall in beta version?
If yes, what should be done?

**Comment by Torxed** [comment]
> Thanks for the reply
> 
> Could you try archinstall in beta version? If yes, what should be done?

You can try the latest master with the following CI/CD ISO build: https://github.com/archlinux/archinstall/actions/runs/5209362961

**Comment by maxfact** [comment]
> > Thanks for the reply
> > Could you try archinstall in beta version? If yes, what should be done?
> 
> You can try the latest master with the following CI/CD ISO build: https://github.com/archlinux/archinstall/actions/runs/5209362961

Thanks, now i try

**Comment by OverLey42** [comment]
> > > Thanks for the reply
> > > Could you try archinstall in beta version? If yes, what should be done?
> > 
> > 
> > You can try the latest master with the following CI/CD ISO build: https://github.com/archlinux/archinstall/actions/runs/5209362961
> 
> Thanks, now i try

any luck with this method?

**Comment by maxfact** [comment]
> > > > Thanks for the reply
> > > > Could you try archinstall in beta version? If yes, what should be done?
> > > 
> > > 
> > > You can try the latest master with the following CI/CD ISO build: https://github.com/archlinux/archinstall/actions/runs/5209362961
> > 
> > 
> > Thanks, now i try
> 
> any luck with this method?

Hello, for now no luck but I think for my inexperience ;)

**Comment by datsfilipe** [comment]
> > Thanks for the reply
> > Could you try archinstall in beta version? If yes, what should be done?
> 
> You can try the latest master with the following CI/CD ISO build: [archlinux/archinstall/actions/runs/5209362961](https://github.com/archlinux/archinstall/actions/runs/5209362961)

Any progress on it? I tried using this `.iso` file and for me the `archinstall` command didn't work, I got the following error when running it:

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 49, in load_devices
    disk = Disk(device)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/parted/decorators.py", line 42, in new
    ret = fn(*args, **kwds)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/parted/disk.py", line 52, in __init__
    self.__disk = _ped.Disk(device.getPedDevice())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ped.DiskLabelException: The backup GPT table is corrupt, but the primary appears OK, so that will be used.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 8, in <module>
    from .lib import disk
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 603, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 38, in __init__
    self.load_devices()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 54, in load_devices
    debug(f'Unable to get disk from device: {device}')
  File "/usr/lib/python3.11/site-packages/archinstall/lib/output.py", line 262, in debug
    log(*msgs, level=level, fg=fg, bg=bg, reset=reset, font=font)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/output.py", line 304, in log
    with log_file.open('a') as fp:
         ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/archinstall/install.log'
```

obs: sry if it's a stupid comment, I'm just a regular arch user.

**Comment by svartkanin** [comment]
This is most likely resolved with the newest version
