### ISSUE TITLE
first time archinstall breaks (bad file descriptor, failed to copy permissions, etc)

### ISSUE THREAD

**Issue by ldr** [archlinux/archinstall#2047]
I *think* it's not the same as https://github.com/archlinux/archinstall/issues/2046 but I'm not really sure ?

Here are the logs: [archinstall-crash.tmux.txt](https://github.com/archlinux/archinstall/files/12566741/archinstall-crash.tmux.txt)

Today wanted to do my first archinstall on my new workstation (have done the old fashioned ways many times)

When installation is ongoing I see several things, like:
`Failed to write /etc/machine-id: Bad file descriptor`
and
`Failed to copy permissions from /etc/group to /etc/.#group7db53da4abca2c9a: No such file or directory`
then
`Failed to resolve group ..` but is understandable if previous steps already broke

it ends with:
```
['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', 'install'] exited with abnormal exit code [1]:
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 740, in _add_systemd_bootloader
    SysCommand(f"/usr/bin/arch-chroot {self.target} bootctl {' '.join(bootctl_options)} install")
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 199, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', 'install'] exited with abnormal exit code [1]:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 291, in run_as_a_module
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 256, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 117, in perform_installation
    with Installer(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 157, in perform_installation
    installation.add_bootloader(archinstall.arguments["bootloader"])
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 1115, in add_bootloader
    self._add_systemd_bootloader(boot_partition, root_partition, efi_partition)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 743, in _add_systemd_bootloader
    SysCommand(f"/usr/bin/arch-chroot {self.target} bootctl --no-variables {' '.join(bootctl_options)} install")
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 199, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', 'install'] exited with abnormal exit code [1]:
archinstall  26.56s user 20.31s system 13% cpu 5:38.25 total
```

I did try several workarounds that are mentioned in the other ticket, like putting in the testing repo in /etc/pacman.conf, manually installing the systemd 254.3, do not define a user in archinstall, but all times in breaks in the same way.

Hope someone can help me out a bit, thanks !!

**Comment by bertbesser** [comment]
Mentioned the other issue b/c for my both happen at the same time.

**Comment by williamKhine** [comment]
been having the same error message today.
![IMG_3829](https://github.com/archlinux/archinstall/assets/61590966/b6bec13f-9693-408f-8280-b7caeab9aaee)

**Comment by gallodelfierro** [comment]
![fuckthisshit](https://github.com/archlinux/archinstall/assets/144567213/821738db-af39-49b5-ba0a-790a8ca68035)

this shit is annoying

**Comment by SMGttv** [comment]
If I understand correctly, this is an issue with systemd. Both with the bootctl install command and creating users and adding new user to groups. This also stops a manual installation so it's not an archinstall specific issue. One fix suggested was to downgrade systemd to 254.1. Didn't test it as it got late and I was over it at that point.

**Comment by bertbesser** [comment]
Hi. 254.1 was installed already on my latest flash drive. I downgraded to 253.1, which then showed the same behavior.

**Comment by deepkerch** [comment]
A temporary solution to all your problems that worked for me.

```
vim /etc/pacman.conf

- [core]
- Include = /etc/pacman.d/mirrorlist
+ [core]
+ SigLevel = PackageRequired
+ Server = https://archive.archlinux.org/repos/2023/09/01/$repo/os/$arch

pacman -Syy
```

**Comment by SMGttv** [comment]
Hey that worked! Out of curiosity, what is causing the issue?

**Comment by deepkerch** [comment]
I wasn't much interested in the nature of the problem, but a cursory reading of the issues led me to the fact that there was a bug in the systemd release.

**Comment by ldr** [comment]
Hey @deepkerch that worked! Also nice, didn't know that was possible :) Thanks !!

So this is the same as the other tickets after all, will close this one.

**Comment by bertbesser** [comment]
Yes, it worked. Thanks @deepkerch.
