### ISSUE TITLE
With efistub, efibootmgr invocation fails due to misuse of --part arg

### ISSUE THREAD

**Issue by andrey-utkin** [archlinux/archinstall#2082]
I chose efiboot bootloader and the installation failed.
efibootmgr manual says `--part` expects the partition number.

```
['/usr/bin/efibootmgr', '--disk', '/dev/sda', '--part', '/dev/sda1', '--create', '--label', 'Arch Linux (linux)', '--loader', '/vmlinuz-linux', '--unicode', 'initrd=\\intel-ucode.img initrd=\\initramfs-linux.img root=PARTUUID=3cefb7aa-88ac-4eaa-a246-caef9e2bbbb3 rw rootfstype=ext4 ', '--verbose'] exited with abnormal exit code [37]: invalid numeric value /dev/sda1


[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 291, in run_as_a_module
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 256, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 117, in perform_installation
    with Installer(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 157, in perform_installation
    installation.add_bootloader(archinstall.arguments["bootloader"])
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 1119, in add_bootloader
    self._add_efistub_bootloader(boot_partition, root_partition)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 1078, in _add_efistub_bootloader
    SysCommand(cmd)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 199, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/efibootmgr', '--disk', '/dev/sda', '--part', '/dev/sda1', '--create', '--label', 'Arch Linux (linux)', '--loader', '/vmlinuz-linux', '--unicode', 'initrd=\\intel-ucode.img initrd=\\initramfs-linux.img root=PARTUUID=3cefb7aa-88ac-4eaa-a246-caef9e2bbbb3 rw rootfstype=ext4 ', '--verbose'] exited with abnormal exit code [37]: invalid numeric value /dev/sda1


[root@sysrescue ~]#
```

**Comment by Torxed** [comment]
Perhaps we can change this: https://github.com/archlinux/archinstall/blob/c75ae97f007f7f7d1d8921e1bd38bcc01b6035f1/archinstall/lib/installer.py#L1087-L1088

To this:
```py
 f'--disk {parent_dev_path} ' \ 
 f'--part {str(boot_partition.safe_dev_path).lstrip(str(parent_dev_path))} ' \ 
```

**Comment by codefiles** [comment]
I do not think that would work.

```
>>> '/dev/sda1'.lstrip('/dev/sda')
'1'
>>> '/dev/nvme0n1p1'.lstrip('/dev/nvme0n1')
'p1'
```

There is the _partn_ column in `lsblk` for partition number but it is not in `LsblkInfo` and therefore also not in `PartitionModification`.

```
lsblk -o +partn
```

It could be added to those and in `_fetch_part_info()` then `boot_partition.partn` would work.

**Comment by Torxed** [comment]
That's a better way forward!
