### ISSUE TITLE
Broken when archinstall is installed with pip

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#2171]
This is the output of `archinstall` when installed with pip rather than with pacman:

```
Checking version...
Traceback (most recent call last):
  File "/home/scripttest/archinstall/.venv/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/home/scripttest/archinstall/archinstall/__init__.py", line 312, in run_as_a_module
    main()
  File "/home/scripttest/archinstall/archinstall/__init__.py", line 298, in main
    _check_new_version()
  File "/home/scripttest/archinstall/archinstall/__init__.py", line 284, in _check_new_version
    upgrade = Pacman.run("-Qu archinstall").decode()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scripttest/archinstall/archinstall/lib/pacman/__init__.py", line 45, in run
    return SysCommand(f'{default_cmd} {args}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scripttest/archinstall/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/home/scripttest/archinstall/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/home/scripttest/archinstall/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: error: package 'archinstall' was not foun
d
warning: 'archinstall' is a file, you might want to use -p/--file.

```

Running `pacman -Qu archinstall` will result in an error and an exit code of 1 since archinstall will not be found in the local package database when it is not installed with pacman.

https://github.com/archlinux/archinstall/blob/c4c5cc42248645142828d09ec0322cdefa49209a/archinstall/__init__.py#L284

**Comment by svartkanin** [comment]
Thanks for spotting! I'll raise a fix shortly
