### ISSUE TITLE
Can't run archinstall after install.

### ISSUE THREAD

**Issue by sh1d0re** [archlinux/archinstall#2185]
Environment:
UTM [Virtual enviornment]: ArchOS arm64 (From the UTM gallery. I tried the ArchBoot version of the OS, but once the ArchBoot settings were done and restarted, it took me back to the first ArchBoot settings. Perhaps forgot to click the bed.)
HostPC: Macbook Apple Silicon [M1]

What I did:
`pacman -Sy archinstall`
`archinstall`

The Error after that:
```Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 8, in <
module>
    from .lib import disk
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/__init__.py", lin
e 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py
", line 649, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py
", line 39, in __init__
    self.load_devices()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py
", line 59, in load_devices
    if get_lsblk_info(device.path).type == 'rom':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py",
 line 1133, in get_lsblk_info
    if infos := _fetch_lsblk_info(dev_path):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py",
 line 1116, in _fetch_lsblk_info
    raise err
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py",
 line 1105, in _fetch_lsblk_info
    result = SysCommand(f'lsblk --json -b -o+{lsblk_fields} {dev_path}')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 365,
 in __init__
    self.create_session()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 414,
 in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 197,
 in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/lsblk', '--json', '-b', '-o+
name,path,pkname,size,log-sec,pttype,ptuuid,rota,tran,partn,partuuid,parttype,uu
id,fstype,fsver,fsavail,fsuse%,type,mountpoint,mountpoints,fsroots', '/dev/vda']
 exited with abnormal exit code [1]: lsblk: unknown column: partn,partuuid,partt
ype,uuid,fstype,fsver,fsavail,fsuse%,type,mountpoint,mountpoints,fsroot
```

I also used the pacman -S option, knowing it does not change anything, did not work. It worked on the archboot version of the OS, but as usual, it had the boot loop issue. I want a solution to either fix the boot loop issue, or solving this python error that occured. I really am aware that I am using ARM64 as my CPU architecture, and a weird enviornment to use arch OS.

Sorry for the long issue and the low-level terminology. I am waiting for a reply. Thank you.

**Comment by svartkanin** [comment]
The error seems to be cut off a bit.
What happens if you run `lsblk -J -O`?

**Comment by sh1d0re** [comment]
It gives me a whole info output about the block devices. Since there is so much, ill send the cut-out output.
```{
   "blockdevices": [
      {
         "alignment": 0,
         "disc-aln": 0,
         "dax": false,
         "disc-gran": "0B",
         "disc-max": "0B",
         "disc-zero": false,
         "fsavail": null,
         "fsroots": [
             null
         ],
         "fssize": null,
         "fstype": null,
         "fsused": null,
         "fsuse%": null,
         "fsver": null,
         "group": "optical",
         "hctl": "0:0:0:0",
         "hotplug": true,
         "kname": "sr0",
         "label": null,
         "log-sec": 512,
         "maj:min": "11:0",
         "min-io": 512,
         "mode": "brw-rw----",
         "model": "QEMU CD-ROM",
         "name": "sr0",
         "opt-io": 0,
         "owner": "root",
         "partflags": null,
         "partlabel": null,
         "parttype": null,
         "parttypename": null,
         "partuuid": null,
         "path": "/dev/sr0",
         "phy-sec": 512,
         "pkname": null,
         "pttype": null,
         "ptuuid": null,
         "ra": 128,
         "rand": false,
         "rev": "2.5+",
         "rm": true,
         "ro": false,
         "rota": true,
         "rq-size": 2,
         "sched": "mq-deadline",
         "serial": "1-0000:00:03.0-4.1",
         "size": "1024M",
         "start": null,
         "state": "running",
         "subsystems": "block:scsi:usb:pci",
         "mountpoint": null,
         "mountpoints": [
             null
         ]```

**Comment by svartkanin** [comment]
This is not possible to debug without the full installation log, as we also had a lot of changes since it's likely that this has been fixed
