### ISSUE TITLE
Archinstall KeyError:17

### ISSUE THREAD

**Issue by krister-dahl** [archlinux/archinstall#2191]
Hi! First a screenshot of my disclayout.
![IMG_20231023_175652__01](https://github.com/archlinux/archinstall/assets/95381698/995ffcf0-67dc-49ae-b6c4-c0f9b5be80d8)
Dual boot environment with Win10 and Ubuntu and intention of installing Arch on sdc.
When running archinstall from bootable medium I get:

root@archiso" # archinstall
Traceback (most recent call last):
File "/usr/bin/archinstall", line 5, in <module>
from archinstall import run_as_a_module
File "/usr/lib/python3.11/site-packages/arch install/__init__.py", line 8, in <module>
from.lib import disk
File "/usr/lib/python3.11/site-packages/arch 
install/lib/disk/__init__.py", line 1, in <module>
from .device_handler import device_handler, disk_layouts
File "/usr/lib/python3.11/site-packages/arch install/lib/disk/device_handler.py", line 649, in <module>device_handler = DeviceHandler()

File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 39, in __init__
self.load_devices()
File "/usr/lib/python3.11/site-packages/arch install/lib/disk/device_handler.py", line 71, in load_devices
device_info = _DeviceInfo.from_disk(disk)
File "/usr/lib/python3.11/site-packages/arch install/lib/disk/device_model.py", line 409, in from_disk
device_type = parted.devices[device.type]
KeyError: 17

I have tried the last 3 isoreleases with same result.

**Comment by lastata** [comment]
I have the same issue too. Disk config: 2x RAID0 (2 tb for each), 2 NVMe 's( one with windows11, second is the target), a dvd drive and a plug-in slot for a another HDD.

**Comment by codefiles** [comment]
The `parted.devices` dict does not contain a `17` key. [1] This is defined in parted as `PED_DEVICE_MD`, [2] a RAID device.

### Example

```python
import parted

for key, value in parted.devices.items():
    print(key, value)
```

**Output**

```
0 unknown
1 scsi
2 ide
3 dac960
4 cpqarray
5 file
6 ataraid
7 i2o
8 ubd
9 dasd
10 viodasd
11 sx8
12 dm
13 xvd
14 sdmmc
15 virtblk
19 nvme
```

### References

[1] https://github.com/dcantrell/pyparted/blob/d5870bb7a5d512c17c92a4e4fe7e9a8e7c8c3528/src/parted/__init__.py#L109-L126
[2] https://git.savannah.gnu.org/gitweb/?p=parted.git;a=blob;f=include/parted/device.in.h;h=bcee2dd4d104c871e372b40fb822c7435fd1cd2a;hb=HEAD#l51

**Comment by Torxed** [comment]
Raid devices have historically always been problematic. And has been on the back burner for a while: https://github.com/archlinux/archinstall/issues/671
