### ISSUE TITLE
Archinstall failure archlinux-2024.01.01-x86_64.iso

### ISSUE THREAD

**Issue by Steve-Plante** [archlinux/archinstall#2323]
Encountered the following error on bare metal install. I was able to complete archinstall  previously using an older .iso (archlinux-2023.10.14-x86_64.iso)

install.log is attached.

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 329, in run_as_a_module
    main()
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 324, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 254, in <module>
    fs_handler.perform_filesystem_operations()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/filesystem.py", line 55, in perform_filesystem_operations
    device_handler.format(mod, enc_conf=self._enc_config)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 319, in format
    lsblk_info = self._fetch_part_info(part_mod.safe_dev_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 416, in _fetch_part_info
    raise DiskError(f'Unable to determine new uuid: {path}')
archinstall.lib.exceptions.DiskError: Unable to determine new uuid: /dev/sda2
[install.log](https://github.com/archlinux/archinstall/files/13835855/install.log)

**Comment by svartkanin** [comment]
Duplicate https://github.com/archlinux/archinstall/issues/2305

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Where did you get the old ISO, I only find them till 11.01.2023?
