### ISSUE TITLE
target not found: plasma-wayland-session

### ISSUE THREAD

**Issue by TheMrGeeBee** [archlinux/archinstall#2427]
`Hardware model detected: VMware, Inc. VMware Virtual Platform; UEFI mode: False
Processor model detected: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Memory statistics: 15781428 available out of 16343984 total installed
Virtualization detected: vmware; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": true,
        "size": "776 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": true,
        "size": "204800 MiB",
        "tran": "spi",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "iso9660",
        "fsuse_percentage": "100%",
        "fsver": "Joliet Extension",
        "log_sec": 2048,
        "mountpoint": "/run/archiso/bootmnt",
        "mountpoints": [
            "/run/archiso/bootmnt"
        ],
        "name": "sr0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sr0",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "8cc6f18c",
        "rota": true,
        "size": "942 MiB",
        "tran": "sata",
        "type": "rom",
        "uuid": "2024-03-01-15-06-37-00"
    }
]
Hardware model detected: VMware, Inc. VMware Virtual Platform; UEFI mode: False
Processor model detected: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Memory statistics: 15788388 available out of 16343984 total installed
Virtualization detected: vmware; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": true,
        "size": "776 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": true,
        "size": "204800 MiB",
        "tran": "spi",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "iso9660",
        "fsuse_percentage": "100%",
        "fsver": "Joliet Extension",
        "log_sec": 2048,
        "mountpoint": "/run/archiso/bootmnt",
        "mountpoints": [
            "/run/archiso/bootmnt"
        ],
        "name": "sr0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sr0",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "8cc6f18c",
        "rota": true,
        "size": "942 MiB",
        "tran": "sata",
        "type": "rom",
        "uuid": "2024-03-01-15-06-37-00"
    }
]
Checking version...
New version available: [?25larchinstall 2.7.1-1 -> 2.7.2-1
[?25h
Password strength: weak
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/kde.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.11/site-packages/archinstall/default_profiles/servers/tomcat.py
Password strength: weak
Saving all configuration files to /root
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pulseaudio"
    },
    "bootloader": "Grub",
    "config_version": "2.7.1",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/sda",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "27554005-fb90-4f80-914b-8b8aef32a6d3",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 203
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 3
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "ext4",
                        "mount_options": [],
                        "mountpoint": "/",
                        "obj_id": "54ac3545-eeea-441d-8422-5eefd237a0c4",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 214532358144
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 216006656
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "archlinux",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "us",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Sweden": [
                "https://mirror.osbeck.com/archlinux/$repo/os/$arch",
                "https://mirror.bahnhof.net/pub/archlinux/$repo/os/$arch",
                "https://ftp.myrveln.se/pub/linux/archlinux/$repo/os/$arch",
                "https://ftp.lysator.liu.se/pub/archlinux/$repo/os/$arch",
                "https://ftp.acc.umu.se/mirror/archlinux/$repo/os/$arch",
                "http://mirror.bahnhof.net/pub/archlinux/$repo/os/$arch",
                "http://ftpmirror.infania.net/mirror/archlinux/$repo/os/$arch",
                "http://ftp.myrveln.se/pub/linux/archlinux/$repo/os/$arch",
                "http://ftp.lysator.liu.se/pub/archlinux/$repo/os/$arch",
                "http://ftp.acc.umu.se/mirror/archlinux/$repo/os/$arch"
            ]
        }
    },
    "network_config": {
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "All open-source",
        "greeter": "sddm",
        "profile": {
            "custom_settings": {
                "Kde": {}
            },
            "details": [
                "Kde"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Europe/Stockholm",
    "uki": false,
    "version": "2.7.1"
}
Unmounting all existing partitions: /dev/sda
Wiping partitions and metadata: /dev/sda
Creating partitions: /dev/sda
	Type: primary
	Filesystem: fat32
	Geometry: 6144 start sector, 415744 length
	Type: primary
	Filesystem: ext4
	Geometry: 421888 start sector, 419008512 length
Unmounting all existing partitions: /dev/sda
Formatting filesystem: /usr/bin/mkfs.fat -F32 /dev/sda1
partition information found: {'name': 'sda1', 'path': '/dev/sda1', 'pkname': 'sda', 'size': '203 MiB', 'log_sec': 512, 'pttype': 'dos', 'ptuuid': '7fbab314', 'rota': True, 'tran': None, 'partn': 1, 'partuuid': '7fbab314-01', 'parttype': '0xb', 'uuid': '14D4-7456', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Formatting filesystem: /usr/bin/mkfs.ext4 -F /dev/sda2
partition information found: {'name': 'sda2', 'path': '/dev/sda2', 'pkname': 'sda', 'size': '204510 MiB', 'log_sec': 512, 'pttype': 'dos', 'ptuuid': '7fbab314', 'rota': True, 'tran': None, 'partn': 2, 'partuuid': '7fbab314-02', 'parttype': '0x83', 'uuid': 'febcd8ed-7af3-4353-9672-beeec752e1e7', 'fstype': 'ext4', 'fsver': '1.0', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Starting installation
Mounting partitions in order
Mounting /dev/sda2: mount /dev/sda2 /mnt/archinstall
Mounting /dev/sda1: mount /dev/sda1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Archinstall will not install any ucode.
The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'grub']
Enabling periodic TRIM
Enabling service fstrim.timer
A new package mirror-list has been created: /mnt/archinstall/etc/pacman.d/mirrorlist
Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Grub to /dev/sda1
Installing packages: ['grub']
kernel parameters: zswap.enabled=0 rootfstype=ext4
GRUB boot partition: /dev/sda1
GRUB boot partition: /dev/sda1
Installing packages: ['networkmanager']
Installing packages: ['network-manager-applet']
Enabling service NetworkManager.service
Creating user mrgeebee
Setting password for mrgeebee
Enabling sudo permissions for mrgeebee
Installing audio server: Pulseaudio
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
Installing packages: ['nano', 'vim', 'openssh', 'htop', 'wget', 'iwd', 'wireless_tools', 'wpa_supplicant', 'smartmontools', 'xdg-utils']
Installing profile Kde...
Installing packages: ['plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland']
Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: nstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra                   0.0   B  0.00   B/s --:-- [----------------------]   0%
 extra                   7.0 MiB  10.7 MiB/s 00:00 [##################----]  83%
 extra                   8.3 MiB  27.4 MiB/s 00:00 [######################] 100%
[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Pacstrap failed. See /var/log/archinstall/install.log or above message for error details: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/archinstall/lib/pacman/__init__.py", line 50, in ask
    func(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 329, in run_as_a_module
    main()
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 324, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 256, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 118, in perform_installation
    with Installer(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 109, in __exit__
    raise exc_val
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 187, in perform_installation
    profile_handler.install_profile_config(installation, profile_config)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/profile/profiles_handler.py", line 234, in install_profile_config
    profile.install(install_session)
  File "/usr/lib/python3.11/site-packages/archinstall/default_profiles/desktop.py", line 84, in install
    install_session.add_additional_packages(profile.packages)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 1245, in add_additional_packages
    return self.pacman.strap(packages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/pacman/__init__.py", line 82, in strap
    self.ask(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/pacman/__init__.py", line 56, in ask
    raise RequirementError(f'{bail_message}: {err}')
archinstall.lib.exceptions.RequirementError: Pacstrap failed. See /var/log/archinstall/install.log or above message for error details: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'plasma-meta', 'konsole', 'kwrite', 'dolphin', 'ark', 'plasma-wayland-session', 'egl-wayland', '--noconfirm'] exited with abnormal exit code [1]: ==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
[?25l:: Synchronizing package databases...
 core
[1F core is up to date[K[1E extra
[1F extra is up to date[K[1Eerror: target not found: plasma-wayland-session
[?25h==> ERROR: Failed to install packages to new root

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
`

**Comment by TheMrGeeBee** [comment]
Error in the kde.py script, plasma-wayland-session doesn't exists but wayland-workspace doe's.
