### ISSUE TITLE
"No module named 'parted'" even when parted is clearly installed.

### ISSUE THREAD

**Issue by sp404sx** [archlinux/archinstall#2480]
```
Traceback (most recent call last):    
    File "usr/bin/archinstall", line 5, in <module>
        from archinstall import run_as_a_module
    File "usr/lib/python3.12/site-packages/archinstall/__init__.py", line 11, in <module>
        from .lib import disk
    File "usr/lib/python3.12/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
        from .device_handler import device_handler, disk_layouts
    File "usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 9, in  <module>
        from parted import ( # type: ignore
ModuleNotFoundError: No module named 'parted'
```

Getting this whenever I try running 'archinstall'. Tried on 2 machines, the same thing happens. Parted is installed, it says so whenever I try installing it again.

**Comment by killertofus** [comment]
Syy python-pyparted && Syy python-simple-term-menu

**Comment by sp404sx** [comment]
Thanks.

**Comment by killertofus** [comment]
you're welcome
