### ISSUE TITLE
Traceback 

### ISSUE THREAD

**Issue by Pu1kX43** [archlinux/archinstall#2522]
Got this error  after clicking enter

![20240528_222552](https://github.com/archlinux/archinstall/assets/171091548/bfa1ae91-1036-4a0a-9c11-6bb7df6c6c9a)

 Configurations if needed
archinstall language: english
keyboard_layout: eng
mirror region: Poland
harddrive: external /dev/nvme0n1, btrfs, encryption, 2 partitions (boot and root)
bootloader: grub
swap: true
root password: set
user account specified, with password and superuser
profile: desktop, kde
audio: pipewire
kernel: linux
additional packages: firefox
configure network: copy from installation media
timezone: European

**Comment by svartkanin** [comment]
Can you please share the log file

**Comment by Pu1kX43** [comment]
> Can you please share the log file

Press Enter to continue.
! Formatting /dev/numeon1 in
5....4....3....2....1....
Unmounting all existing partitions: deu/numeOnl
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/arch install/__init__.py", line 332, in run_as_a_module main()
File "/usr/lib/python3.12/site-packages/arch install/__init__.py", line 327, in main importlib. import_module(mod_name)
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module return _bootstrap._gcd_import (namel level:1, package, level)
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360,
in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/usr/lib/python3.12/site-packages/arch install/scripts/guided.py", line 245, in <module> fs_handler.perform_filesystem_operations()
File "/usr/lib/python3.12/site-packages/arch install/lib/disk/filesystem.py", line 54, in perform_filesystem_operations device_handler.partition (mod, partition_table-partition_table)
File
"/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 501, in partition
self._umount_all_existing (modification.device_path)
File "/usr/lib/python3.12/site-packages/arch install/lib/disk/device_handler.py", line 483, in _umount_all_existing
self.umount(partition.path, recursive=True)
File "/usr/lib/python3.12/site-packages/arch install/lib/disk/device_handler.py", line 584, in umount
SysCommand(f' {command} {mountpoint}')
File "/usr/lib/python3.12/site-packages/arch install/lib/general.py", line 365, in __init__
self.create session()
File
"/usr/lib/python3.12/site-packages/arch install/lib/general.py", line 414, in create_session with SysCommandWorker (
File "/usr/lib/python3.12/site-packages/arch install/lib/general.py", line 197, in _exit_
raise SysCallError(
rchinstall.lib.exceptions. SysCallError: ['/usr/bin/umount', '-R', '[SWAP]'] exited with abnormal exit code [1]: umount: [SWAP]: not found
rchinstall experienced the above error. If you think this is a bug, please report it to
ttps://github.com/archlinux/arch install and include the log file "/var/log/arch install/install.log".
int: To extract the log from a live ISO
url -F' file-e/var/log/arch install/install.log' https://0x0.st
rchinstall 4.42s user 2.78s system 0% cpu 15:33.86 total 
Did you mean this?

**Comment by Pu1kX43** [comment]
> Can you please share the log file
 here it is : https://0x0.st/XN2T.log

**Comment by svartkanin** [comment]
This should be fixed with https://github.com/archlinux/archinstall/pull/2498
It's in master but not released yet

**Comment by Pu1kX43** [comment]
I no longer need need any help, I got to ufi settings and booted usb again
but it worked.
