### ISSUE TITLE
Archinstall failed

### ISSUE THREAD

**Issue by belerefontis** [archlinux/archinstall#2581]
### Which ISO version are you using?

2024-07-01

### The installation log

```json
Mounting /dev/nvme0n1p2: mount /dev/nvme0n1p2 /mnt/arch_btrfs
Partition /dev/nvme0n1p2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Hardware model detected: ASUS System Product Name; UEFI mode: True
Processor model detected: AMD Ryzen 5 5600G with Radeon Graphics
Memory statistics: 28994688 available out of 30590728 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c9)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "795 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0xc",
                "partuuid": "00034da4-01",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "00034da4",
                "rota": false,
                "size": "238474 MiB",
                "tran": null,
                "type": "part",
                "uuid": "1B03-2414"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "00034da4",
        "rota": false,
        "size": "238475 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "6b323b61-8690-4084-9e6e-979701ec50ae",
                "path": "/dev/nvme0n1p1",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "83d5fde8-3357-4b79-92cd-b070b68d641c",
                "rota": false,
                "size": "1024 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "6AF5-01AE"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "btrfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p2",
                "partn": 2,
                "parttype": "4f68bce3-e8cd-4db1-96e7-fbcaf984b709",
                "partuuid": "57ed92c0-5e9c-48b9-82a9-46baf864be02",
                "path": "/dev/nvme0n1p2",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "83d5fde8-3357-4b79-92cd-b070b68d641c",
                "rota": false,
                "size": "475914 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "98942a1b-e957-4b42-816f-9964167d4c4a"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "83d5fde8-3357-4b79-92cd-b070b68d641c",
        "rota": false,
        "size": "476940 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Password strength: very weak
Password strength: very weak
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 353, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 328, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 225, in <module>
    ask_user_questions()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 98, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 140, in <lambda>
    lambda preset: ask_additional_packages_to_install(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/interactions/general_conf.py", line 144, in ask_additional_packages_to_install
    valid, invalid = validate_package_list(packages)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/packages/packages.py", line 100, in validate_package_list
    valid_packages = {package for package in packages if find_package(package)}
                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/packages/packages.py", line 63, in find_package
    data = package_search(package)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/packages/packages.py", line 52, in package_search
    response = _make_request(BASE_URL_PKG_SEARCH, {'name': package})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/packages/packages.py", line 26, in _make_request
    return urlopen(full_url, context=ssl_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

### describe the problem

I have installed Arch on this system multiple times without a problem. The last time I had a successful installation was 3 days ago. Upon installing today, after running the archinstall script and selecting additional packages I wanted to include with the installation, I got the attached error log.
[http://0x0.st/X9Dl.log](url)

**Comment by belerefontis** [comment]
The installation proceeded when I repeated the process, skipping the part in adding additional packages.

**Comment by correctmost** [comment]
How many additional packages did you specify?

It looks like you encountered rate limiting: `urllib.error.HTTPError: HTTP Error 429: Too Many Requests`

**Comment by belerefontis** [comment]
Should have been around 15-20 packages. The weird thing is that the same amount of packages were specified in earlier installations without noticing a problem.

**Comment by GuestSneezeOSDev** [comment]
type `sudo dd if=/dev/zero of=/dev/sda bs=1M status=progress
` then try `archinstall`

**Comment by svartkanin** [comment]
The menu has been updated to no longer call any APIs for additional packages so this shouldn't happen anymore
