### ISSUE TITLE
Pacman: `Partition / too full` (`/mnt/archinstall` airootfs out of space)

### ISSUE THREAD

**Issue by jtagcat** [archlinux/archinstall#2613]
### Which ISO version are you using?

2024-08-01

### The installation log

```json
Hardware model detected: Intel(R) Client Systems NUC8i7BEH; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
Memory statistics: 31232912 available out of 32733996 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation CoffeeLake-U GT3e [Iris Plus Graphics 655] (rev 01)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "801 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "e3eacfb7-34aa-4202-aa18-79a0534a0e76",
        "rota": false,
        "size": "953869 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "iso9660",
                "fsuse_percentage": null,
                "fsver": "Joliet Extension",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "0x0",
                "partuuid": "9db1a03c-01",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "dos",
                "ptuuid": "9db1a03c",
                "rota": true,
                "size": "961 MiB",
                "tran": null,
                "type": "part",
                "uuid": "2024-08-01-14-36-07-00"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb2",
                "partn": 2,
                "parttype": "0xef",
                "partuuid": "9db1a03c-02",
                "path": "/dev/sdb2",
                "pkname": "sdb",
                "pttype": "dos",
                "ptuuid": "9db1a03c",
                "rota": true,
                "size": "166 MiB",
                "tran": null,
                "type": "part",
                "uuid": "D8FE-794C"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": "iso9660",
        "fsuse_percentage": null,
        "fsver": "Joliet Extension",
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "9db1a03c",
        "rota": true,
        "size": "14755 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": "2024-08-01-14-36-07-00"
    },
    {
        "children": [],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "c156ae70-4b2e-41d7-b8da-5dc2b46fdcd3",
        "rota": false,
        "size": "244198 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Suggesting multi-disk-layout for devices: /dev/sda, /dev/nvme0n1
/root: /dev/nvme0n1
/home: /dev/sda
Error finding index of No Encryption: ['LUKS']
Password strength: strong
Password strength: strong
Password strength: strong
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [
        "multilib"
    ],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Systemd-boot",
    "config_version": "2.8.1",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/nvme0n1",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "e4551347-74d8-44d9-a8d4-f002a8076331",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": "/",
                        "obj_id": "ed314072-47ef-4c7b-b94f-4bafa49826cc",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 254984675328
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1074790400
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            },
            {
                "device": "/dev/sda",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": "/home",
                        "obj_id": "cf7750c3-ce60-4c98-b395-dfc0c4842231",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1000202788864
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": {
        "encryption_type": "luks",
        "lvm_volumes": [],
        "partitions": [
            "cf7750c3-ce60-4c98-b395-dfc0c4842231",
            "ed314072-47ef-4c7b-b94f-4bafa49826cc"
        ]
    },
    "hostname": "lavie",
    "kernels": [
        "linux",
        "linux-zen"
    ],
    "locale_config": {
        "kb_layout": "et-nodeadkeys",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Estonia": [
                "https://repo.br.ee/arch/$repo/os/$arch",
                "https://mirrors.xtom.ee/archlinux/$repo/os/$arch",
                "https://mirror.cspacehostings.com/archlinux/$repo/os/$arch",
                "http://repo.br.ee/arch/$repo/os/$arch",
                "http://mirrors.xtom.ee/archlinux/$repo/os/$arch",
                "http://mirror.cspacehostings.com/archlinux/$repo/os/$arch"
            ],
            "Worldwide": [
                "https://mirror.rackspace.com/archlinux/$repo/os/$arch",
                "https://geo.mirror.pkgbuild.com/$repo/os/$arch",
                "http://mirror.rackspace.com/archlinux/$repo/os/$arch"
            ]
        }
    },
    "network_config": {
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "syncthing"
    ],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "All open-source",
        "greeter": "lightdm-slick-greeter",
        "profile": {
            "custom_settings": {
                "Sway": {
                    "seat_access": "polkit"
                }
            },
            "details": [
                "Sway"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Europe/Tallinn",
    "uki": false,
    "version": "2.8.1"
}
Unmounting all existing partitions: /dev/nvme0n1
Unmounting all existing partitions: /dev/sda
Wiping partitions and metadata: /dev/nvme0n1
Creating partitions: /dev/nvme0n1
	Type: primary
	Filesystem: fat32
	Geometry: 2048 start sector, 2097152 length
	Type: primary
	Filesystem: btrfs
	Geometry: 2099200 start sector, 498016944 length
Wiping partitions and metadata: /dev/sda
Creating partitions: /dev/sda
	Type: primary
	Filesystem: btrfs
	Geometry: 2048 start sector, 1953521072 length
Formatting filesystem: mkfs.fat -F 32 /dev/nvme0n1p1
partition information found: {'name': 'nvme0n1p1', 'path': '/dev/nvme0n1p1', 'pkname': 'nvme0n1', 'size': '1024 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': 'fc5e6344-b674-42c2-b704-aaa786cc5d56', 'rota': False, 'tran': 'nvme', 'partn': 1, 'partuuid': '21b677b4-3a99-491c-9125-5e67c3756e90', 'parttype': 'c12a7328-f81f-11d2-ba4b-00a0c93ec93b', 'uuid': 'A868-8EA9', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Luks2 encrypting: /dev/nvme0n1p2
cryptsetup format: /usr/bin/cryptsetup --batch-mode --verbose --type luks2 --pbkdf argon2id --hash sha512 --key-size 512 --iter-time 10000 --key-file /tmp/nvme0n1p2.disk_pw --use-urandom luksFormat /dev/nvme0n1p2
cryptsetup luksFormat output: Existing 'crypto_LUKS' superblock signature on device /dev/nvme0n1p2 will be wiped.
Existing 'crypto_LUKS' superblock signature on device /dev/nvme0n1p2 will be wiped.
Key slot 0 created.
Command successful.
Unlocking luks2 device: /dev/nvme0n1p2
cryptsetup open output: 
luks2 formatting mapper dev: /dev/mapper/ainstnvme0n1p2
Formatting filesystem: mkfs.btrfs -f /dev/mapper/ainstnvme0n1p2
luks2 locking device: /dev/nvme0n1p2
Closing crypt device ainstnvme0n1p2
partition information found: {'name': 'nvme0n1p2', 'path': '/dev/nvme0n1p2', 'pkname': 'nvme0n1', 'size': '243172 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': 'fc5e6344-b674-42c2-b704-aaa786cc5d56', 'rota': False, 'tran': 'nvme', 'partn': 2, 'partuuid': '84ee25ed-f2c8-4059-8bb7-4cfa2539a4b7', 'parttype': '4f68bce3-e8cd-4db1-96e7-fbcaf984b709', 'uuid': 'b2c7aee6-15fb-4966-8e9e-6f1e3a2db9c4', 'fstype': 'crypto_LUKS', 'fsver': '2', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Creating subvolumes: /dev/nvme0n1p2
Unlocking luks2 device: /dev/nvme0n1p2
cryptsetup open output: 
Mounting /dev/mapper/ainstnvme0n1p2: mount -o compress=zstd /dev/mapper/ainstnvme0n1p2 /mnt/arch_btrfs
Partition /dev/mapper/ainstnvme0n1p2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Closing crypt device ainstnvme0n1p2
Luks2 encrypting: /dev/sda1
cryptsetup format: /usr/bin/cryptsetup --batch-mode --verbose --type luks2 --pbkdf argon2id --hash sha512 --key-size 512 --iter-time 10000 --key-file /tmp/sda1.disk_pw --use-urandom luksFormat /dev/sda1
cryptsetup luksFormat output: Existing 'crypto_LUKS' superblock signature on device /dev/sda1 will be wiped.
Existing 'crypto_LUKS' superblock signature on device /dev/sda1 will be wiped.
Key slot 0 created.
Command successful.
Unlocking luks2 device: /dev/sda1
cryptsetup open output: 
luks2 formatting mapper dev: /dev/mapper/ainstsda1
Formatting filesystem: mkfs.btrfs -f /dev/mapper/ainstsda1
luks2 locking device: /dev/sda1
Closing crypt device ainstsda1
partition information found: {'name': 'sda1', 'path': '/dev/sda1', 'pkname': 'sda', 'size': '953867 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': 'c13e1f6b-1948-486f-bb04-24f312c2ace2', 'rota': False, 'tran': None, 'partn': 1, 'partuuid': 'bb6307e8-26de-4a49-8980-a17feb0b402b', 'parttype': '0fc63daf-8483-4772-8e79-3d69d8477de4', 'uuid': '92886953-4b9e-4aac-a624-19f80f4ad29a', 'fstype': 'crypto_LUKS', 'fsver': '2', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Creating subvolumes: /dev/sda1
Unlocking luks2 device: /dev/sda1
cryptsetup open output: 
Mounting /dev/mapper/ainstsda1: mount -o compress=zstd /dev/mapper/ainstsda1 /mnt/arch_btrfs
Partition /dev/mapper/ainstsda1 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Closing crypt device ainstsda1
Starting installation...
Mounting ordered layout
Unlocking luks2 device: /dev/sda1
cryptsetup open output: 
Unlocking luks2 device: /dev/nvme0n1p2
cryptsetup open output: 
Mounting partition layout
Mounting /dev/nvme0n1p1: mount /dev/nvme0n1p1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
Creating key-file: /dev/sda1
Adding additional key-file /mnt/archinstall/etc/cryptsetup-keys.d/ainstsda1.key
Adding crypttab entry for key /etc/cryptsetup-keys.d/ainstsda1.key
Setting mirrors
Mirrorlist: 

## Estonia
Server = https://repo.br.ee/arch/$repo/os/$arch


## Estonia
Server = https://mirrors.xtom.ee/archlinux/$repo/os/$arch


## Estonia
Server = https://mirror.cspacehostings.com/archlinux/$repo/os/$arch


## Estonia
Server = http://repo.br.ee/arch/$repo/os/$arch


## Estonia
Server = http://mirrors.xtom.ee/archlinux/$repo/os/$arch


## Estonia
Server = http://mirror.cspacehostings.com/archlinux/$repo/os/$arch


## Worldwide
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch


## Worldwide
Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch


## Worldwide
Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

The multilib flag is set. This system will be installed with the multilib repository enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'linux-zen', 'btrfs-progs', 'btrfs-progs', 'intel-ucode']
Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'base', 'base-devel', 'linux-firmware', 'linux', 'linux-zen', 'btrfs-progs', 'btrfs-progs', 'intel-ucode', '--noconfirm'] exited with abnormal exit code [1]:       btrfs-progs-6.10-1  intel-ucode-20240531-1  linux-6.10.4.arch2-1
               linux-firmware-20240703.e94a2a3b-1  linux-zen-6.10.4.zen2-1

Total Download Size:    745.66 MiB
Total Installed Size:  1492.81 MiB

:: Proceed with installation? [Y/n] 
error: Partition / too full: 194244 blocks needed, 61395 blocks free
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.
[?25h==> ERROR: Failed to install packages to new root

Pacstrap failed. See /var/log/archinstall/install.log or above message for error details: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'base', 'base-devel', 'linux-firmware', 'linux', 'linux-zen', 'btrfs-progs', 'btrfs-progs', 'intel-ucode', '--noconfirm'] exited with abnormal exit code [1]:       btrfs-progs-6.10-1  intel-ucode-20240531-1  linux-6.10.4.arch2-1
               linux-firmware-20240703.e94a2a3b-1  linux-zen-6.10.4.zen2-1

Total Download Size:    745.66 MiB
Total Installed Size:  1492.81 MiB

:: Proceed with installation? [Y/n] 
error: Partition / too full: 194244 blocks needed, 61395 blocks free
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.
[?25h==> ERROR: Failed to install packages to new root

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/lib/pacman/__init__.py", line 50, in ask
    func(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'base', 'base-devel', 'linux-firmware', 'linux', 'linux-zen', 'btrfs-progs', 'btrfs-progs', 'intel-ucode', '--noconfirm'] exited with abnormal exit code [1]:       btrfs-progs-6.10-1  intel-ucode-20240531-1  linux-6.10.4.arch2-1
               linux-firmware-20240703.e94a2a3b-1  linux-zen-6.10.4.zen2-1

Total Download Size:    745.66 MiB
Total Installed Size:  1492.81 MiB

:: Proceed with installation? [Y/n] 
error: Partition / too full: 194244 blocks needed, 61395 blocks free
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.
[?25h==> ERROR: Failed to install packages to new root


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 353, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 328, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 247, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 117, in perform_installation
    with Installer(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 137, in perform_installation
    installation.minimal_installation(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 842, in minimal_installation
    self.pacman.strap(self._base_packages)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/pacman/__init__.py", line 82, in strap
    self.ask(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/pacman/__init__.py", line 56, in ask
    raise RequirementError(f'{bail_message}: {err}')
archinstall.lib.exceptions.RequirementError: Pacstrap failed. See /var/log/archinstall/install.log or above message for error details: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'base', 'base-devel', 'linux-firmware', 'linux', 'linux-zen', 'btrfs-progs', 'btrfs-progs', 'intel-ucode', '--noconfirm'] exited with abnormal exit code [1]:       btrfs-progs-6.10-1  intel-ucode-20240531-1  linux-6.10.4.arch2-1
               linux-firmware-20240703.e94a2a3b-1  linux-zen-6.10.4.zen2-1

Total Download Size:    745.66 MiB
Total Installed Size:  1492.81 MiB

:: Proceed with installation? [Y/n] 
error: Partition / too full: 194244 blocks needed, 61395 blocks free
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.
[?25h==> ERROR: Failed to install packages to new root


Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

### describe the problem

`/mnt/archinstall/boot` was mounted correctly to nvme0n1, but `/mnt/archinstall` was backed by airootfs (at 256M size).

**Comment by jtagcat** [comment]
Reproducible with btrfs, not reproducible with ext4.

**Comment by Torxed** [comment]
I believe we fixed this by making sure the boot partition is not mounted before root.

I haven't found time to release the version yet but hopefully I'll find a free slot tonight

**Comment by theredcmdcraft** [comment]
Having the same error. Here's my log: https://0x0.st/8ieG.log

`df -HT` returns the following:
https://0x0.st/8ied.txt

**Comment by codefiles** [comment]
@theredcmdcraft 

The disk configuration in the log shows the `mountpoint` for the root partition is unset (`null`) when it should be set to `"/"`.

```
                        "dev_path": "/dev/sdb2",
                        ...
                        "mountpoint": null,
```

Same symptom as the initial report, different bug. Another reason the disk configuration should be validated before proceeding with the installation. Without a root mount point the installer should not proceed.

**Comment by theredcmdcraft** [comment]
> @theredcmdcraft 
> 
> The disk configuration in the log shows the `mountpoint` for the root partition is unset (`null`) when it should be set to `"/"`.
> 
> 
> 
> ```
> 
>     "disk_config": {
> 
>         "config_type": "manual_partitioning",
> 
>         ...
> 
>                         "dev_path": "/dev/sdb2",
> 
>                         ...
> 
>                         "mountpoint": null,
> 
> ```
> 
> 
> 
> Same symptom as the initial report, different bug. Another reason the disk configuration should be validated before proceeding with the installation. Without a root mount point the installer should not proceed.

Yep thankyou that was my issue. I had partitions on the disk, and set it to reformat it, but i did not see that the moint point are missing. My bad sorry
