### ISSUE TITLE
crash when selecting profile

### ISSUE THREAD

**Issue by madfresh** [archlinux/archinstall#2625]
### Which ISO version are you using?

2024-08-01

### The installation log

```json
Hardware model detected: To Be Filled By O.E.M. To Be Filled By O.E.M.; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Memory statistics: 14668592 available out of 16051668 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "801 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext2",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0x83",
                "partuuid": "880c70ca-01",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "880c70ca",
                "rota": false,
                "size": "487 MiB",
                "tran": null,
                "type": "part",
                "uuid": "db581bad-d6ca-4b9a-abd0-be2e746587fd"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0x5",
                "partuuid": "880c70ca-02",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "880c70ca",
                "rota": false,
                "size": "0 MiB",
                "tran": null,
                "type": "part",
                "uuid": null
            },
            {
                "children": [
                    {
                        "children": [],
                        "fsavail": null,
                        "fsroots": [],
                        "fstype": "ext4",
                        "fsuse_percentage": null,
                        "fsver": "1.0",
                        "log_sec": 512,
                        "mountpoint": null,
                        "mountpoints": [],
                        "name": "debian--vg-root",
                        "partn": null,
                        "parttype": null,
                        "partuuid": null,
                        "path": "/dev/mapper/debian--vg-root",
                        "pkname": "sda5",
                        "pttype": null,
                        "ptuuid": null,
                        "rota": false,
                        "size": "456392 MiB",
                        "tran": null,
                        "type": "lvm",
                        "uuid": "23c83aaa-cf9f-4d34-8923-3c5837dd0e34"
                    },
                    {
                        "children": [],
                        "fsavail": null,
                        "fsroots": [],
                        "fstype": "swap",
                        "fsuse_percentage": null,
                        "fsver": "1",
                        "log_sec": 512,
                        "mountpoint": null,
                        "mountpoints": [],
                        "name": "debian--vg-swap_1",
                        "partn": null,
                        "parttype": null,
                        "partuuid": null,
                        "path": "/dev/mapper/debian--vg-swap_1",
                        "pkname": "sda5",
                        "pttype": null,
                        "ptuuid": null,
                        "rota": false,
                        "size": "980 MiB",
                        "tran": null,
                        "type": "lvm",
                        "uuid": "d4ad2519-4c1f-4569-a745-a3762264c0a9"
                    }
                ],
                "fsavail": null,
                "fsroots": [],
                "fstype": "LVM2_member",
                "fsuse_percentage": null,
                "fsver": "LVM2 001",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda5",
                "partn": 5,
                "parttype": "0x8e",
                "partuuid": "880c70ca-05",
                "path": "/dev/sda5",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "880c70ca",
                "rota": false,
                "size": "457373 MiB",
                "tran": null,
                "type": "part",
                "uuid": "k2Vce2-MBl8-LbGJ-POmd-tDzB-UWSF-Mxrole"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "880c70ca",
        "rota": false,
        "size": "457862 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "eedcca36-7a0b-4ecd-92e8-4334ad09b8b5",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "214ee315-4d5c-42e6-a896-165f97dc3949",
                "rota": true,
                "size": "14995 MiB",
                "tran": null,
                "type": "part",
                "uuid": "0EE0-8720"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "214ee315-4d5c-42e6-a896-165f97dc3949",
        "rota": true,
        "size": "14996 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": null
    }
]

Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 224, in <module>
    ask_user_questions()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 97, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 114, in <lambda>
    lambda preset: self._select_profile(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 433, in _select_profile
    profile_config = ProfileMenu(store, preset=current_profile).run()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/profile/profile_menu.py", line 58, in run
    super().run(allow_reset=allow_reset)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/profile/profile_menu.py", line 31, in <lambda>
    lambda x: self._select_profile(x),
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/profile/profile_menu.py", line 70, in _select_profile
    profile = select_profile(preset)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/profile/profile_menu.py", line 192, in select_profile
    select_result = profile_selection.do_on_select()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py", line 34, in do_on_select
    self.set_current_selection(choice.value)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ServerProfile' object has no attribute 'set_current_selection'. Did you mean: 'current_selection'?

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

#### Description of the issue

I was installing on real hardware 

Then select profile happened and archinstall crashed

**Comment by alexpyattaev** [comment]
The bug appears to be triggered when you choose components for server install. Pressing Enter on any of the options triggers it. Go to Profile->Type->Server->hit enter to reproduce.

**Comment by Torxed** [comment]
Thanks, we'll have a look. Desktop profiles appear to be working so it might be specifically related to the server stuff.

**Comment by svartkanin** [comment]
Fix for this is up

**Comment by alexpyattaev** [comment]
Thanks!
