### ISSUE TITLE
systemd-udevd is not runniong (udevadm settle)

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#2634]
### Which ISO version are you using?

2024-08-26 (build)

### The installation log

```
File "/build/archinstall/src/archinstall-2.8.4/archinstall/__init__.py", line 12, in <module>
    from .lib import disk
  File "/build/archinstall/src/archinstall-2.8.4/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/build/archinstall/src/archinstall-2.8.4/archinstall/lib/disk/device_handler.py", line 788, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/build/archinstall/src/archinstall-2.8.4/archinstall/lib/disk/device_handler.py", line 41, in __init__
    self.load_devices()
  File "/build/archinstall/src/archinstall-2.8.4/archinstall/lib/disk/device_handler.py", line 50, in load_devices
    SysCommand('udevadm settle')
  File "/build/archinstall/src/archinstall-2.8.4/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/build/archinstall/src/archinstall-2.8.4/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/build/archinstall/src/archinstall-2.8.4/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/udevadm', 'settle'] exited with abnormal exit code [1]: systemd-udevd is not running.
```

### describe the problem

During `python -m build .` the following will happen if built using a container (which is the default behavior or Arch packaging).

### To reproduce

```
$ cd /tmp/
$ git clone https://gitlab.archlinux.org/archlinux/packaging/packages/archinstall.git
$ pkgctl build archinstall
```

**Comment by codefiles** [comment]
This exception occurs during generation of documentation with Sphinx:

```
Running Sphinx v8.0.2
loading translations [en]... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 12 added, 0 changed, 0 removed
reading sources... [  8%] archinstall/Installer
reading sources... [ 17%] archinstall/plugins
reading sources... [ 25%] cli_parameters/config/custom_commands
reading sources... [ 33%] cli_parameters/config/disk_config
reading sources... [ 42%] cli_parameters/config/disk_encryption
reading sources... [ 50%] examples/python
reading sources... [ 58%] help/discord
reading sources... [ 67%] help/known_issues
reading sources... [ 75%] help/report_bug
reading sources... [ 83%] index
reading sources... [ 92%] installing/guided
reading sources... [100%] installing/python

WARNING: autodoc: failed to import function 'Installer' from module 'archinstall'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/sphinx/ext/autodoc/importer.py", line 144, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/__init__.py", line 12, in <module>
    from .lib import disk
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/lib/disk/device_handler.py", line 788, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/lib/disk/device_handler.py", line 41, in __init__
    self.load_devices()
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/lib/disk/device_handler.py", line 50, in load_devices
    SysCommand('udevadm settle')
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/build/archinstall/src/archinstall-2.8.6/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/udevadm', 'settle'] exited with abnormal exit code [1]: systemd-udevd is not running.

 [autodoc.import_object]
```

The [documentation](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) for the autodoc extension contains the following warning:

> [!WARNING]
> [autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#module-sphinx.ext.autodoc) **imports** the modules to be documented. If any modules have side effects on import, these will be executed by `autodoc` when `sphinx-build` is run.
>
> If you document scripts (as opposed to library modules), make sure their main routine is protected by a `if __name__ == '__main__'` condition.
