### ISSUE TITLE
Crashes on mirrors region select

### ISSUE THREAD

**Issue by cucumber-sp** [archlinux/archinstall#2716]
### Which ISO version are you using?

archlinux-2024.10.01-x86_64

### The installation log

```json
Hardware model detected: innotek GmbH VirtualBox; UEFI mode: False
Processor model detected: Intel(R) Core(TM) Ultra 7 155U
Memory statistics: 23231904 available out of 23814904 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": true,
        "size": "794 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0xb",
                "partuuid": "9c4b9e28-01",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "9c4b9e28",
                "rota": true,
                "size": "1024 MiB",
                "tran": null,
                "type": "part",
                "uuid": "A83E-6994"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext4",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0x83",
                "partuuid": "9c4b9e28-02",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "9c4b9e28",
                "rota": true,
                "size": "23549 MiB",
                "tran": null,
                "type": "part",
                "uuid": "67e97648-c379-453d-9833-c0f11dd92cbf"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "9c4b9e28",
        "rota": true,
        "size": "24576 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "iso9660",
        "fsuse_percentage": "100%",
        "fsver": "Joliet Extension",
        "log_sec": 2048,
        "mountpoint": "/run/archiso/bootmnt",
        "mountpoints": [
            "/run/archiso/bootmnt"
        ],
        "name": "sr0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sr0",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "f9f63ac3",
        "rota": true,
        "size": "1119 MiB",
        "tran": "ata",
        "type": "rom",
        "uuid": "2024-10-01-04-30-02-00"
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 224, in <module>
    ask_user_questions()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 97, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 58, in <lambda>
    lambda preset: self._mirror_configuration(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 455, in _mirror_configuration
    mirror_configuration = MirrorMenu(data_store, preset=preset).run()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 235, in run
    super().run(allow_reset=allow_reset)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 210, in <lambda>
    lambda preset: select_mirror_regions(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 259, in select_mirror_regions
    mirrors = list_mirrors()
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/mirrors.py", line 335, in list_mirrors
    mirrorlist = fetch_data_from_url(url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/networking.py", line 134, in fetch_data_from_url
    data = response.read().decode('UTF-8')
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(146841 bytes read, 361541 more expected)

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

### describe the problem

Installing arch inside VirtualBox. Select Mirrors, Mirrors from Region > program crashes constantly

**Comment by svartkanin** [comment]
I can't say what the problem exactly is as there is no further logging, but it seems that calling the endpoint didn't go well. We can add more logging and a retry as well to it

**Comment by Torxed** [comment]
Correct, server unexpectedly closed the connection or there was a network/routing issue between you and server making the connection very momentarily hickup.
