### ISSUE TITLE
Boot loader crash 

### ISSUE THREAD

**Issue by chunkbanned** [archlinux/archinstall#2723]
### Which ISO version are you using?

2024.10.01

### The installation log

```json

Could not determine the filesystem: None
Hardware model detected: System manufacturer System Product Name; UEFI mode: True
Processor model detected: AMD Ryzen 5 2600X Six-Core Processor
Memory statistics: 31221652 available out of 32793424 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['NVIDIA Corporation TU102 [GeForce RTX 2080 Ti] (rev a1)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "794 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "f0b475c3-29b9-11ec-955d-0c9d92c726e4",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "549 MiB",
                "tran": null,
                "type": "part",
                "uuid": "B28639628639286D"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "3868fb86-a410-45ac-b39c-ceb2bcd6b9bf",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "100 MiB",
                "tran": null,
                "type": "part",
                "uuid": "F8C4-2BC5"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda3",
                "partn": 3,
                "parttype": "e3c9e316-0b5c-4db8-817d-f92df00215ae",
                "partuuid": "acf82dbd-f579-4bdd-8c23-fdb54e213d42",
                "path": "/dev/sda3",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "16 MiB",
                "tran": null,
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda4",
                "partn": 4,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "2f2f07e2-287b-4b74-86db-ae7479f37d1c",
                "path": "/dev/sda4",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "100 MiB",
                "tran": null,
                "type": "part",
                "uuid": "BCF0-F612"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda5",
                "partn": 5,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "8dc80e28-5346-4c3c-897d-31e7239d5991",
                "path": "/dev/sda5",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "226377 MiB",
                "tran": null,
                "type": "part",
                "uuid": "BC6CF9966CF94BA0"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda6",
                "partn": 6,
                "parttype": "de94bba4-06d1-4d40-a16a-bfd50179d6ac",
                "partuuid": "5b697fbb-87b9-4083-bb9a-426ce33d53fe",
                "path": "/dev/sda6",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "517 MiB",
                "tran": null,
                "type": "part",
                "uuid": "FA96E4AC96E46B19"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda7",
                "partn": 7,
                "parttype": "de94bba4-06d1-4d40-a16a-bfd50179d6ac",
                "partuuid": "263be2d4-02c3-401a-8965-66022b22061f",
                "path": "/dev/sda7",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "644 MiB",
                "tran": null,
                "type": "part",
                "uuid": "5C64CA3F64CA1BA0"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda8",
                "partn": 8,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "f0b475c5-29b9-11ec-955d-0c9d92c726e4",
                "path": "/dev/sda8",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "100 MiB",
                "tran": null,
                "type": "part",
                "uuid": "1830-EE95"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda9",
                "partn": 9,
                "parttype": "de94bba4-06d1-4d40-a16a-bfd50179d6ac",
                "partuuid": "f0b475c6-29b9-11ec-955d-0c9d92c726e4",
                "path": "/dev/sda9",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
                "rota": false,
                "size": "527 MiB",
                "tran": null,
                "type": "part",
                "uuid": "744297024296C7EE"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "f0b475c7-29b9-11ec-955d-0c9d92c726e4",
        "rota": false,
        "size": "228936 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "ac9b97e9-e8da-4d36-8efe-f797889b282a",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "693511e2-98d0-4f27-b8d6-0e9a842f4d3b",
                "rota": true,
                "size": "1000 MiB",
                "tran": null,
                "type": "part",
                "uuid": "4561-896A"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb2",
                "partn": 2,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "8d57f0f1-048a-4a7c-9cc2-a2fb9fef82b1",
                "path": "/dev/sdb2",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "693511e2-98d0-4f27-b8d6-0e9a842f4d3b",
                "rota": true,
                "size": "304242 MiB",
                "tran": null,
                "type": "part",
                "uuid": "6CAA53BCAA53820E"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "693511e2-98d0-4f27-b8d6-0e9a842f4d3b",
        "rota": true,
        "size": "305245 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [
                    {
                        "children": [],
                        "fsavail": null,
                        "fsroots": [],
                        "fstype": "iso9660",
                        "fsuse_percentage": null,
                        "fsver": "Joliet Extension",
                        "log_sec": 512,
                        "mountpoint": null,
                        "mountpoints": [],
                        "name": "ventoy",
                        "partn": null,
                        "parttype": null,
                        "partuuid": null,
                        "path": "/dev/mapper/ventoy",
                        "pkname": "sdc1",
                        "pttype": "dos",
                        "ptuuid": "f9f63ac3",
                        "rota": true,
                        "size": "1119 MiB",
                        "tran": null,
                        "type": "dm",
                        "uuid": "2024-10-01-04-30-02-00"
                    }
                ],
                "fsavail": null,
                "fsroots": [],
                "fstype": "exfat",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdc1",
                "partn": 1,
                "parttype": "0x7",
                "partuuid": "df02f3dd-01",
                "path": "/dev/sdc1",
                "pkname": "sdc",
                "pttype": "dos",
                "ptuuid": "df02f3dd",
                "rota": true,
                "size": "58641 MiB",
                "tran": null,
                "type": "part",
                "uuid": "4E21-0000"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT16",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdc2",
                "partn": 2,
                "parttype": "0xef",
                "partuuid": "df02f3dd-02",
                "path": "/dev/sdc2",
                "pkname": "sdc",
                "pttype": "dos",
                "ptuuid": "df02f3dd",
                "rota": true,
                "size": "32 MiB",
                "tran": null,
                "type": "part",
                "uuid": "223C-F3F8"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdc",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdc",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "df02f3dd",
        "rota": true,
        "size": "58674 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p1",
                "partn": 1,
                "parttype": "e3c9e316-0b5c-4db8-817d-f92df00215ae",
                "partuuid": "d7201292-e64b-4115-b439-b89bfd503780",
                "path": "/dev/nvme0n1p1",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "6bdb6f98-e23e-43d3-8e89-5600e6344111",
                "rota": false,
                "size": "15 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p2",
                "partn": 2,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "859815b6-e97f-44c0-b128-443dd0eda2f4",
                "path": "/dev/nvme0n1p2",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "6bdb6f98-e23e-43d3-8e89-5600e6344111",
                "rota": false,
                "size": "488369 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "BEC0231DC022DB81"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "6bdb6f98-e23e-43d3-8e89-5600e6344111",
        "rota": false,
        "size": "488386 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Password strength: weak
Password strength: weak
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cosmic.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pulseaudio"
    },
    "bootloader": "Systemd-boot",
    "config_version": "2.8.6",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/sdb",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "83497455-f67d-4121-8dc6-ce39044354d6",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [
                            {
                                "mountpoint": "/",
                                "name": "@"
                            },
                            {
                                "mountpoint": "/home",
                                "name": "@home"
                            },
                            {
                                "mountpoint": "/var/log",
                                "name": "@log"
                            },
                            {
                                "mountpoint": "/var/cache/pacman/pkg",
                                "name": "@pkg"
                            },
                            {
                                "mountpoint": "/.snapshots",
                                "name": "@.snapshots"
                            }
                        ],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": null,
                        "obj_id": "424e27ce-3521-460c-9112-3f4326e914a2",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 318997094400
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1074790400
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "arch",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "uk",
        "sys_enc": "UTF-8",
        "sys_lang": "en_GB"
    },
    "mirror_config": null,
    "network_config": {
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "Nvidia (open kernel module for newer GPUs, Turing+)",
        "greeter": "sddm",
        "profile": {
            "custom_settings": {
                "Hyprland": {
                    "seat_access": "polkit"
                }
            },
            "details": [
                "Hyprland"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Europe/London",
    "uki": false,
    "version": "2.8.6"
}
Unmounting all existing partitions: /dev/sdb
Unmounting: /dev/sdb1
Unmounting: /dev/sdb2
Wiping partitions and metadata: /dev/sdb
Creating partitions: /dev/sdb
	Type: primary
	Filesystem: fat32
	Geometry: 2048 start sector, 2097152 length
	Type: primary
	Filesystem: btrfs
	Geometry: 2099200 start sector, 623041200 length
Formatting filesystem: mkfs.fat -F 32 /dev/sdb1
partition information found: {'name': 'sdb1', 'path': '/dev/sdb1', 'pkname': 'sdb', 'size': '1024 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': '9550212b-31f9-43ef-af81-28407a8d0b35', 'rota': True, 'tran': None, 'partn': 1, 'partuuid': '68f1aa1f-7d39-43e1-abb8-a9965e3bd9f3', 'parttype': 'c12a7328-f81f-11d2-ba4b-00a0c93ec93b', 'uuid': 'AC8B-7855', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Formatting filesystem: mkfs.btrfs -f /dev/sdb2
partition information found: {'name': 'sdb2', 'path': '/dev/sdb2', 'pkname': 'sdb', 'size': '304219 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': '9550212b-31f9-43ef-af81-28407a8d0b35', 'rota': True, 'tran': None, 'partn': 2, 'partuuid': '1aac260a-c8e4-46c7-9cd1-896a4fc3129d', 'parttype': '4f68bce3-e8cd-4db1-96e7-fbcaf984b709', 'uuid': '0692c6ee-bea4-461d-b7e8-7005a1d1ca4e', 'fstype': 'btrfs', 'fsver': None, 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Creating subvolumes: /dev/sdb2
Mounting /dev/sdb2: mount -o compress=zstd /dev/sdb2 /mnt/arch_btrfs
Creating subvolume: @
Creating subvolume: @home
Creating subvolume: @log
Creating subvolume: @pkg
Creating subvolume: @.snapshots
Partition /dev/sdb2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Starting installation...
Mounting ordered layout
No lvm config defined to be mounted
Mounting partition layout
Mounting /dev/sdb2: mount -o compress=zstd,subvol=@ /dev/sdb2 /mnt/archinstall
Mounting /dev/sdb2: mount -o compress=zstd,subvol=@,subvol=@home /dev/sdb2 /mnt/archinstall/home
Mounting /dev/sdb2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log /dev/sdb2 /mnt/archinstall/var/log
Mounting /dev/sdb2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log,subvol=@pkg /dev/sdb2 /mnt/archinstall/var/cache/pacman/pkg
Mounting /dev/sdb2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log,subvol=@pkg,subvol=@.snapshots /dev/sdb2 /mnt/archinstall/.snapshots
Mounting /dev/sdb1: mount /dev/sdb1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'btrfs-progs', 'amd-ucode']
Setting keyboard language to uk
Keyboard language for this installation is now set to: uk
Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Systemd-boot to /dev/sdb1
Installing systemd bootloader
Installing packages: ['efibootmgr']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', 'install'] exited with abnormal exit code [126]: chroot: failed to run command 'bootctl': Input/output error

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 1075, in _add_systemd_bootloader
    SysCommand(f"/usr/bin/arch-chroot {self.target} bootctl {' '.join(bootctl_options)} install")
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', 'install'] exited with abnormal exit code [126]: chroot: failed to run command 'bootctl': Input/output error


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 153, in perform_installation
    installation.add_bootloader(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 1460, in add_bootloader
    self._add_systemd_bootloader(boot_partition, root, efi_partition, uki_enabled)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 1078, in _add_systemd_bootloader
    SysCommand(f"/usr/bin/arch-chroot {self.target} bootctl --no-variables {' '.join(bootctl_options)} install")
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', 'install'] exited with abnormal exit code [126]: chroot: failed to run command 'bootctl': Input/output error


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 246, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 116, in perform_installation
    with Installer(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 104, in __exit__
    self.sync_log_to_install_medium()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 429, in sync_log_to_install_medium
    os.makedirs(f"{self.target}/{os.path.dirname(absolute_logfile)}")
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 5] Input/output error: '/mnt/archinstall//var/log/archinstall'

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st

```

#### Description of the issue

I was installing on my AMD Ryzen 2600X & Nvidia 2080ti system 

Then a bunch of red stuff popped up and archinstall crashed 

i’m not really sure what happened tbh

#### Virtual machine config:

```xml
<domain type="kvm">
  <name>my-arch-machine</name>
  ...
  </devices>
</domain>
```

```console
/usr/bin/qemu-system-x86_64 -name guest=my-arch-machine,debug-threads=on -object ...
```

**Comment by svartkanin** [comment]
I'll close this for now as it is quite old and may be fixed by now
