### ISSUE TITLE
ArchInstall crashes when attempting to add a network interface when out of interfaces

### ISSUE THREAD

**Issue by sapsicle** [archlinux/archinstall#2740]
### Which ISO version are you using?

2024-10-01

### The installation log

```json
Mounting /dev/sda2: mount /dev/sda2 /mnt/arch_btrfs
Partition /dev/sda2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Hardware model detected: LENOVO 20BSCTO1WW; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
Memory statistics: 6700620 available out of 8027156 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation HD Graphics 5500 (rev 09)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "794 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "15d1a2c0-9cba-4a92-8d73-66dc146f3f79",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "fbc40049-0e44-4ad6-8a20-ad127835692f",
                "rota": false,
                "size": "1024 MiB",
                "tran": null,
                "type": "part",
                "uuid": "91EE-BCDC"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "btrfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "partuuid": "9574fd3a-c760-4e34-8efc-1861ddf917e0",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "fbc40049-0e44-4ad6-8a20-ad127835692f",
                "rota": false,
                "size": "243173 MiB",
                "tran": null,
                "type": "part",
                "uuid": "e70fa7b8-be63-4ddc-95cb-90bf47972e67"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "fbc40049-0e44-4ad6-8a20-ad127835692f",
        "rota": false,
        "size": "244198 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "iso9660",
                "fsuse_percentage": null,
                "fsver": "Joliet Extension",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "0x0",
                "partuuid": "f9f63ac3-01",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "dos",
                "ptuuid": "f9f63ac3",
                "rota": true,
                "size": "953 MiB",
                "tran": null,
                "type": "part",
                "uuid": "2024-10-01-04-30-02-00"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb2",
                "partn": 2,
                "parttype": "0xef",
                "partuuid": "f9f63ac3-02",
                "path": "/dev/sdb2",
                "pkname": "sdb",
                "pttype": "dos",
                "ptuuid": "f9f63ac3",
                "rota": true,
                "size": "165 MiB",
                "tran": null,
                "type": "part",
                "uuid": "66FB-7ACA"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": "iso9660",
        "fsuse_percentage": null,
        "fsver": "Joliet Extension",
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "f9f63ac3",
        "rota": true,
        "size": "29600 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": "2024-10-01-04-30-02-00"
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Password strength: weak
Password strength: weak
Password strength: very weak
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cosmic.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 224, in <module>
    ask_user_questions()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 97, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 328, in run
    if not self._process_selection(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 345, in _process_selection
    return self.exec_option(config_name, selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/abstract_menu.py", line 366, in exec_option
    result = selector.func(cur_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/global_menu.py", line 153, in <lambda>
    lambda preset: ask_to_configure_network(preset),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/interactions/network_menu.py", line 155, in ask_to_configure_network
    nics = ManualNetworkConfig('Configure interfaces', preset_nics).run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/list_manager.py", line 81, in run
    self._data = self.handle_action(choice.value, None, self._data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/interactions/network_menu.py", line 50, in handle_action
    iface = self._select_iface(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/interactions/network_menu.py", line 68, in _select_iface
    choice = Menu(str(_('Select interface to add')), list(available), skip=True).run()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/menu/menu.py", line 138, in __init__
    raise RequirementError('Menu.__init__() requires at least one option to proceed.')
archinstall.lib.exceptions.RequirementError: Menu.__init__() requires at least one option to proceed.

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

### describe the problem

I accidentally selected "add another interface" in the network connectivity section after already adding both interfaces from that list. I would think this just shows me an empty list or does nothing, but the archinstall program crashed immediately.

**Comment by svartkanin** [comment]
Thanks for reporting, fix is up
