### ISSUE TITLE
Reporting installation failure

### ISSUE THREAD

**Issue by vash909** [archlinux/archinstall#2800]
### Which ISO version are you using?

latest ISO

### The installation log

```json
Could not determine the filesystem: None
Hardware model detected: CHUWI Innovation And Technology(ShenZhen)co.,Ltd GemiBook XPro; UEFI mode: True
Processor model detected: Intel(R) N100
Memory statistics: 6424920 available out of 7866012 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation Alder Lake-N [UHD Graphics]'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "810 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "iso9660",
                "fsuse_percentage": null,
                "fsver": "Joliet Extension",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0x0",
                "partuuid": "211019da-01",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "211019da",
                "rota": true,
                "size": "978 MiB",
                "tran": null,
                "type": "part",
                "uuid": "2024-11-01-10-09-22-00"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0xef",
                "partuuid": "211019da-02",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "211019da",
                "rota": true,
                "size": "175 MiB",
                "tran": null,
                "type": "part",
                "uuid": "6724-A8D2"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": "iso9660",
        "fsuse_percentage": null,
        "fsver": "Joliet Extension",
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "211019da",
        "rota": true,
        "size": "59136 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": "2024-11-01-10-09-22-00"
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT16",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "820a532a-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p1",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "260 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "CA3A-120D"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p2",
                "partn": 2,
                "parttype": "83bd6b9d-7f41-11dc-be0b-001560b84f0f",
                "partuuid": "820cab39-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p2",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "0 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p3",
                "partn": 3,
                "parttype": "516e7cb5-6ecf-11d6-8ff8-00022d09712b",
                "partuuid": "8210c1d5-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p3",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "2048 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "zfs_member",
                "fsuse_percentage": null,
                "fsver": "5000",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p4",
                "partn": 4,
                "parttype": "516e7cba-6ecf-11d6-8ff8-00022d09712b",
                "partuuid": "82137fdb-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p4",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "241889 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "3548196187716839844"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
        "rota": false,
        "size": "244198 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed to perform version check: ['/usr/bin/pacman', '-Sy'] exited with abnormal exit code [1]: ed retrieving file 'core.db' from mirror.kirbee.tech : Could not resolve host: mirror.kirbee.tech
warning: fatal error from mirror.kirbee.tech, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirrors.nguyenhoang.cloud : Could not resolve host: mirrors.nguyenhoang.cloud
warning: fatal error from mirrors.nguyenhoang.cloud, skipping for the remainder of this transaction
error: failed to synchronize all databases (failed to retrieve some files)
[?25h
Arch Linux mirrors are not reachable. Please check your internet connection
Could not determine the filesystem: None
Hardware model detected: CHUWI Innovation And Technology(ShenZhen)co.,Ltd GemiBook XPro; UEFI mode: True
Processor model detected: Intel(R) N100
Memory statistics: 6409152 available out of 7866012 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation Alder Lake-N [UHD Graphics]'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "810 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "iso9660",
                "fsuse_percentage": null,
                "fsver": "Joliet Extension",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0x0",
                "partuuid": "211019da-01",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "211019da",
                "rota": true,
                "size": "978 MiB",
                "tran": null,
                "type": "part",
                "uuid": "2024-11-01-10-09-22-00"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0xef",
                "partuuid": "211019da-02",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "211019da",
                "rota": true,
                "size": "175 MiB",
                "tran": null,
                "type": "part",
                "uuid": "6724-A8D2"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": "iso9660",
        "fsuse_percentage": null,
        "fsver": "Joliet Extension",
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "211019da",
        "rota": true,
        "size": "59136 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": "2024-11-01-10-09-22-00"
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT16",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "820a532a-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p1",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "260 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "CA3A-120D"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p2",
                "partn": 2,
                "parttype": "83bd6b9d-7f41-11dc-be0b-001560b84f0f",
                "partuuid": "820cab39-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p2",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "0 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p3",
                "partn": 3,
                "parttype": "516e7cb5-6ecf-11d6-8ff8-00022d09712b",
                "partuuid": "8210c1d5-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p3",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "2048 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "zfs_member",
                "fsuse_percentage": null,
                "fsver": "5000",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p4",
                "partn": 4,
                "parttype": "516e7cba-6ecf-11d6-8ff8-00022d09712b",
                "partuuid": "82137fdb-a274-11ef-8e9e-1fb810877f3b",
                "path": "/dev/nvme0n1p4",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
                "rota": false,
                "size": "241889 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "3548196187716839844"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "820978e5-a274-11ef-8e9e-1fb810877f3b",
        "rota": false,
        "size": "244198 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Password strength: very weak
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pulseaudio"
    },
    "bootloader": "Systemd-boot",
    "config_version": "2.8.6",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/nvme0n1",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "6a9297cc-b22e-4a7e-bf26-b68fe1c318d4",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "ext4",
                        "mount_options": [],
                        "mountpoint": "/",
                        "obj_id": "cebf2912-db4d-49fd-ba15-8120e88eebfa",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 254984675328
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1074790400
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "archvash",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "us",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": null,
    "network_config": {},
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile_config": null,
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "UTC",
    "uki": false,
    "version": "2.8.6"
}
Unmounting all existing partitions: /dev/nvme0n1
Unmounting: /dev/nvme0n1p1
Unmounting: /dev/nvme0n1p2
Unmounting: /dev/nvme0n1p3
Unmounting: /dev/nvme0n1p4
Wiping partitions and metadata: /dev/nvme0n1
Creating partitions: /dev/nvme0n1
	Type: primary
	Filesystem: fat32
	Geometry: 2048 start sector, 2097152 length
	Type: primary
	Filesystem: ext4
	Geometry: 2099200 start sector, 498016944 length
Formatting filesystem: mkfs.fat -F 32 /dev/nvme0n1p1
partition information found: {'name': 'nvme0n1p1', 'path': '/dev/nvme0n1p1', 'pkname': 'nvme0n1', 'size': '1024 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': '3c092f15-022d-4297-b169-d1ece5acfc39', 'rota': False, 'tran': 'nvme', 'partn': 1, 'partuuid': 'bf69ce98-1cca-4233-b11d-157477e52270', 'parttype': 'c12a7328-f81f-11d2-ba4b-00a0c93ec93b', 'uuid': 'D4B9-B745', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Formatting filesystem: mkfs.ext4 -F /dev/nvme0n1p2
partition information found: {'name': 'nvme0n1p2', 'path': '/dev/nvme0n1p2', 'pkname': 'nvme0n1', 'size': '243172 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': '3c092f15-022d-4297-b169-d1ece5acfc39', 'rota': False, 'tran': 'nvme', 'partn': 2, 'partuuid': 'a12ac212-5a05-46c0-8a89-24bf4fc952b5', 'parttype': '4f68bce3-e8cd-4db1-96e7-fbcaf984b709', 'uuid': 'dafcc604-ca7d-4720-b8c3-d1f8c6b4e54f', 'fstype': 'ext4', 'fsver': '1.0', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Starting installation...
Mounting ordered layout
No lvm config defined to be mounted
Mounting partition layout
Mounting /dev/nvme0n1p2: mount /dev/nvme0n1p2 /mnt/archinstall
Mounting /dev/nvme0n1p1: mount /dev/nvme0n1p1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'intel-ucode']
Enabling periodic TRIM
Enabling service fstrim.timer
Setting keyboard language to us
Keyboard language for this installation is now set to: us
Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Systemd-boot to /dev/nvme0n1p1
Installing systemd bootloader
Installing packages: ['efibootmgr']
Identifying root partition by PARTUUID: a12ac212-5a05-46c0-8a89-24bf4fc952b5
kernel parameters: root=PARTUUID=a12ac212-5a05-46c0-8a89-24bf4fc952b5 zswap.enabled=0 rw rootfstype=ext4
Creating user vash
Setting password for vash
Enabling sudo permissions for vash
Installing audio server: Pulseaudio
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'vash', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to bus: No medium found[0m


Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 246, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 116, in perform_installation
    with Installer(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 173, in perform_installation
    audio_config.install_audio_config(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/models/audio_configuration.py", line 46, in install_audio_config
    PipewireProfile().install(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 40, in install
    self._enable_pipewire_for_all(install_session)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 35, in _enable_pipewire_for_all
    install_session.arch_chroot('systemctl enable --user pipewire-pulse.service', run_as=user.username)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 632, in arch_chroot
    return self.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 626, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'vash', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to bus: No medium found[0m



Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

### describe the problem

Installing on CHUWI GemiBook XPro Intel

**Comment by svartkanin** [comment]
Duplicate https://github.com/archlinux/archinstall/issues/2764
