### ISSUE TITLE
3.0: If the user is not specified, installation fails

### ISSUE THREAD

**Issue by darkblaze69** [archlinux/archinstall#2860]
### Which ISO version are you using?

2024-11-01

### The installation log

```
Mounting /dev/sda2: mount /dev/sda2 /mnt/arch_btrfs
Partition /dev/sda2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Hardware model detected: QEMU Standard PC (Q35 + ICH9, 2009); UEFI mode: True
Processor model detected: Intel(R) Core(TM) Ultra 9 185H
Memory statistics: 7630804 available out of 8127244 total installed
Virtualization detected: kvm; is VM: True
Graphics devices detected: dict_keys(['Red Hat, Inc. Virtio 1.0 GPU (rev 01)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "810 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "0f3b3fb5-046b-4d87-9df5-a8baa0fdc0e3",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "1c4d0700-0eeb-4ea2-8b3d-d4983095eeae",
                "rota": true,
                "size": "1024 MiB",
                "tran": null,
                "type": "part",
                "uuid": "4422-73CB"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "btrfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "4f68bce3-e8cd-4db1-96e7-fbcaf984b709",
                "partuuid": "6f84bb65-a9ba-4522-b7d7-4e59dbe27571",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "1c4d0700-0eeb-4ea2-8b3d-d4983095eeae",
                "rota": true,
                "size": "24574 MiB",
                "tran": null,
                "type": "part",
                "uuid": "fa9a34bf-383e-49f2-9885-f932884c978e"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "1c4d0700-0eeb-4ea2-8b3d-d4983095eeae",
        "rota": true,
        "size": "25600 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "iso9660",
        "fsuse_percentage": "100%",
        "fsver": "Joliet Extension",
        "log_sec": 2048,
        "mountpoint": "/run/archiso/bootmnt",
        "mountpoints": [
            "/run/archiso/bootmnt"
        ],
        "name": "sr0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sr0",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "211019da",
        "rota": false,
        "size": "1154 MiB",
        "tran": "sata",
        "type": "rom",
        "uuid": "2024-11-01-10-09-22-00"
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cosmic.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
Saving configuration files to /root
 -- Chosen configuration --
{
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Systemd-boot",
    "config_version": "3.0.0",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/sda",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "6141475d-e009-4ff2-af08-0ef3e6846ba8",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [
                            {
                                "mountpoint": "/",
                                "name": "@"
                            },
                            {
                                "mountpoint": "/home",
                                "name": "@home"
                            },
                            {
                                "mountpoint": "/var/log",
                                "name": "@log"
                            },
                            {
                                "mountpoint": "/var/cache/pacman/pkg",
                                "name": "@pkg"
                            },
                            {
                                "mountpoint": "/.snapshots",
                                "name": "@.snapshots"
                            }
                        ],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": null,
                        "obj_id": "0187b037-7ddc-4e6d-befe-1e898d99723d",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 25767706624
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1074790400
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "archlinux",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "us",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": null,
    "network_config": {
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "Intel (open-source)",
        "greeter": "gdm",
        "profile": {
            "custom_settings": {
                "Gnome": {}
            },
            "details": [
                "Gnome"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Asia/Yekaterinburg",
    "uki": true,
    "version": "3.0.0"
}
Unmounting all existing partitions: /dev/sda
Unmounting: /dev/sda1
Unmounting: /dev/sda2
Wiping partitions and metadata: /dev/sda
Creating partitions: /dev/sda
	Type: primary
	Filesystem: fat32
	Geometry: 2048 start sector, 2097152 length
	Type: primary
	Filesystem: btrfs
	Geometry: 2099200 start sector, 50327552 length
Formatting filesystem: mkfs.fat -F 32 /dev/sda1
partition information found: {'name': 'sda1', 'path': '/dev/sda1', 'pkname': 'sda', 'size': '1024 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': '33a3aac1-2591-4df3-bd88-a23ec2f1c604', 'rota': True, 'tran': None, 'partn': 1, 'partuuid': '96c0a0bd-2168-40c3-90c5-592cb07d1d34', 'parttype': 'c12a7328-f81f-11d2-ba4b-00a0c93ec93b', 'uuid': '661C-900A', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Formatting filesystem: mkfs.btrfs -f /dev/sda2
partition information found: {'name': 'sda2', 'path': '/dev/sda2', 'pkname': 'sda', 'size': '24574 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': '33a3aac1-2591-4df3-bd88-a23ec2f1c604', 'rota': True, 'tran': None, 'partn': 2, 'partuuid': '89dd3c90-b89d-4bbf-a12f-960a5d06f9ff', 'parttype': '4f68bce3-e8cd-4db1-96e7-fbcaf984b709', 'uuid': '01724b42-f690-4e7f-9434-d6f724b8ea5c', 'fstype': 'btrfs', 'fsver': None, 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Creating subvolumes: /dev/sda2
Mounting /dev/sda2: mount -o compress=zstd /dev/sda2 /mnt/arch_btrfs
Creating subvolume: @
Creating subvolume: @home
Creating subvolume: @log
Creating subvolume: @pkg
Creating subvolume: @.snapshots
Partition /dev/sda2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Starting installation...
Mounting ordered layout
No lvm config defined to be mounted
Mounting partition layout
Mounting /dev/sda2: mount -o compress=zstd,subvol=@ /dev/sda2 /mnt/archinstall
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home /dev/sda2 /mnt/archinstall/home
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log /dev/sda2 /mnt/archinstall/var/log
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log,subvol=@pkg /dev/sda2 /mnt/archinstall/var/cache/pacman/pkg
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log,subvol=@pkg,subvol=@.snapshots /dev/sda2 /mnt/archinstall/.snapshots
Mounting /dev/sda1: mount /dev/sda1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
Archinstall will not install any ucode.
The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'btrfs-progs']
Setting keyboard language to us
Keyboard language for this installation is now set to: us
Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Systemd-boot to /dev/sda1
Identifying root partition by PARTUUID: 89dd3c90-b89d-4bbf-a12f-960a5d06f9ff
kernel parameters: root=PARTUUID=89dd3c90-b89d-4bbf-a12f-960a5d06f9ff zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs
Installing systemd bootloader
Installing packages: ['efibootmgr']
Installing packages: ['networkmanager']
Installing packages: ['network-manager-applet']

Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt/archinstall', 'network-manager-applet', '--noconfirm'] exited with abnormal exit code [None]: -1:0.8+r194...     0.0   B  0.00   B/s --:-- [----------------------]   0%
[1E pango-1:1.54.0-1...     0.0   B  0.00   B/s --:-- [----------------------]   0%
[1E libsoup3-3.6.0-1...     0.0   B  0.00   B/s --:-- [----------------------]   0%
[1E fontconfig-2:2.1...     0.0   B  0.00   B/s --:-- [----------------------]   0%
[1E libglvnd-1.7.0-1...     0.0   B  0.00   B/s --:-- [----------------------]   0%
[1E libdrm-2.4.123-1...     0.0   B  0.00   B/s --:-- [----------------------]   0%
Enabling service NetworkManager.service
Installing audio server: Pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 337, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 330, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 193, in <module>
    guided()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 190, in guided
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 59, in perform_installation
    with Installer(
         ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 114, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 116, in perform_installation
    audio_config.install_audio_config(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/models/audio_configuration.py", line 43, in install_audio_config
    PipewireProfile().install(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 49, in install
    self._enable_pipewire_for_all(install_session)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 36, in _enable_pipewire_for_all
    service_dir = install_session.target / "home" / user.username / ".config" / "systemd" / "user" / "default.target.wants"
                                                    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st

```

#### Description of the issue

Since 3.0 if the user is not specified, installation fails: `AttributeError: 'NoneType' object has no attribute 'username'`

For GNOME OEM installation (a.k.a. gnome-initial-setup) I only need root password specified without any users. (the first user is created during gnome-initial-setup dialog).

#### Virtual machine config:

```console
qemu-system-x86_64 -enable-kvm -M q35 -drive if=pflash,format=raw,unit=0,file=/usr/share/edk2-ovmf/x64/OVMF.4m.fd,readonly=on -cpu host -device virtio-vga-gl,xres=800,yres=600 -m 8G -smp 4 -display dbus,gl=on -cdrom /opt/iso/archlinux-2024.11.01-x86_64.iso -drive file=/var/lib/libvirt/images/arch.qcow2 -boot d
```

**Comment by svartkanin** [comment]
thanks for reporting, I'll have a look at it

**Comment by svartkanin** [comment]
gotcha thanks

**Comment by svartkanin** [comment]
Pushed a fix for this

**Comment by darkblaze69** [comment]
Thanks, checked this and I was able to install with this change.
