### ISSUE TITLE
Failed to connect to user scope bus via local transport: Medium not found

### ISSUE THREAD

**Issue by xyproto** [archlinux/archinstall#2904]
### Which ISO version are you using?

2024-11-01

### The installation log

```json
Hardware model detected: QEMU Standard PC (Q35 + ICH9, 2009); UEFI mode: True
Processor model detected: QEMU Virtual CPU version 2.5+
Memory statistics: 3572076 available out of 4008280 total installed
Virtualization detected: qemu; is VM: True
Graphics devices detected: dict_keys([])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "810 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": true,
        "size": "98304 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "iso9660",
        "fsuse_percentage": "100%",
        "fsver": "Joliet Extension",
        "log_sec": 2048,
        "mountpoint": "/run/archiso/bootmnt",
        "mountpoints": [
            "/run/archiso/bootmnt"
        ],
        "name": "sr0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sr0",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "211019da",
        "rota": false,
        "size": "1154 MiB",
        "tran": "sata",
        "type": "rom",
        "uuid": "2024-11-01-10-09-22-00"
    }
]
Checking version...
New version available: [?25larchinstall 2.8.6-1 -> 3.0.0-1
[?25h
    score: 2
Loaded mirror mirror.aarnet.edu.au with current score of 2
    score: 5
[... redacted ...]
Loaded mirror f.matthieul.dev with current score of 1
    score: 3
Loaded mirror mirrors.nepalicloud.com with current score of 3
    score: 3
Loaded mirror mirrors.nepalicloud.com with current score of 3
Checking download speed of mirror.archlinux.no[2] by fetching: http://mirror.archlinux.no/core/os/x86_64/core.db
    speed: 2753906.9962177854 (2.62MiB/s)
Checking download speed of mirror.archlinux.no[2] by fetching: https://mirror.archlinux.no/core/os/x86_64/core.db
    speed: 3963060.490490807 (3.77MiB/s)
Checking download speed of archlinux.uib.no[5] by fetching: http://archlinux.uib.no/core/os/x86_64/core.db
    speed: 3040942.964051137 (2.9MiB/s)
Checking download speed of mirror.neuf.no[1] by fetching: http://mirror.neuf.no/archlinux/core/os/x86_64/core.db
    speed: 5914713.9528897805 (5.64MiB/s)
Checking download speed of mirror.neuf.no[1] by fetching: https://mirror.neuf.no/archlinux/core/os/x86_64/core.db
    speed: 10615076.67062214 (10.12MiB/s)
Checking download speed of mirror.terrahost.no[14] by fetching: http://mirror.terrahost.no/linux/archlinux/core/os/x86_64/core.db
    speed: 4382774.112109467 (4.17MiB/s)
Password strength: very weak
Password strength: weak
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cosmic.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [
        "multilib"
    ],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Limine",
    "config_version": "2.8.6",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/sda",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "56c4506a-f39b-4338-a259-9115a5b9d4d0",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [
                            {
                                "mountpoint": "/",
                                "name": "@"
                            },
                            {
                                "mountpoint": "/home",
                                "name": "@home"
                            },
                            {
                                "mountpoint": "/var/log",
                                "name": "@log"
                            },
                            {
                                "mountpoint": "/var/cache/pacman/pkg",
                                "name": "@pkg"
                            },
                            {
                                "mountpoint": "/.snapshots",
                                "name": "@.snapshots"
                            }
                        ],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": null,
                        "obj_id": "5a0bd4fe-dcd3-4561-9813-8580e88ce83c",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 102003376128
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1074790400
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "vega",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "no",
        "sys_enc": "UTF-8",
        "sys_lang": "nb_NO.UTF-8"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Norway": [
                "http://mirror.neuf.no/archlinux/$repo/os/$arch",
                "https://mirror.neuf.no/archlinux/$repo/os/$arch",
                "http://mirror.archlinux.no/$repo/os/$arch",
                "https://mirror.archlinux.no/$repo/os/$arch",
                "http://archlinux.uib.no/$repo/os/$arch",
                "http://mirror.terrahost.no/linux/archlinux/$repo/os/$arch"
            ]
        }
    },
    "network_config": {
        "type": "iso"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "orbiton",
        "bat",
        "fish",
        "zsh",
        "the_silver_searcher",
        "xterm",
        "zutty",
        "konsole",
        "odin",
        "git",
        "go",
        "docker"
    ],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "All open-source",
        "greeter": "ly",
        "profile": {
            "custom_settings": {
                "Hyprland": {
                    "seat_access": "polkit"
                }
            },
            "details": [
                "Hyprland"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Europe/Oslo",
    "uki": false,
    "version": "2.8.6"
}
Unmounting all existing partitions: /dev/sda
Wiping partitions and metadata: /dev/sda
Creating partitions: /dev/sda
	Type: primary
	Filesystem: fat32
	Geometry: 2048 start sector, 2097152 length
	Type: primary
	Filesystem: btrfs
	Geometry: 2099200 start sector, 199225344 length
Formatting filesystem: mkfs.fat -F 32 /dev/sda1
partition information found: {'name': 'sda1', 'path': '/dev/sda1', 'pkname': 'sda', 'size': '1024 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': 'fde489ec-c0bb-4d58-a5b4-a1ffad2e4a06', 'rota': True, 'tran': None, 'partn': 1, 'partuuid': '600641f0-c600-4d5d-a996-c85858a67c0f', 'parttype': 'c12a7328-f81f-11d2-ba4b-00a0c93ec93b', 'uuid': 'C37E-A896', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Formatting filesystem: mkfs.btrfs -f /dev/sda2
partition information found: {'name': 'sda2', 'path': '/dev/sda2', 'pkname': 'sda', 'size': '97278 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': 'fde489ec-c0bb-4d58-a5b4-a1ffad2e4a06', 'rota': True, 'tran': None, 'partn': 2, 'partuuid': '6d322182-e99a-4f6d-b8c9-f1d0fabebd19', 'parttype': '4f68bce3-e8cd-4db1-96e7-fbcaf984b709', 'uuid': '5b79593b-48f0-4a3f-9c4b-c0662c08db17', 'fstype': 'btrfs', 'fsver': None, 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Creating subvolumes: /dev/sda2
Mounting /dev/sda2: mount -o compress=zstd /dev/sda2 /mnt/arch_btrfs
Creating subvolume: @
Creating subvolume: @home
Creating subvolume: @log
Creating subvolume: @pkg
Creating subvolume: @.snapshots
Partition /dev/sda2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Starting installation...
Mounting ordered layout
No lvm config defined to be mounted
Mounting partition layout
Mounting /dev/sda2: mount -o compress=zstd,subvol=@ /dev/sda2 /mnt/archinstall
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home /dev/sda2 /mnt/archinstall/home
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log /dev/sda2 /mnt/archinstall/var/log
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log,subvol=@pkg /dev/sda2 /mnt/archinstall/var/cache/pacman/pkg
Mounting /dev/sda2: mount -o compress=zstd,subvol=@,subvol=@home,subvol=@log,subvol=@pkg,subvol=@.snapshots /dev/sda2 /mnt/archinstall/.snapshots
Mounting /dev/sda1: mount /dev/sda1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
Setting mirrors
Mirrorlist: 

## Norway
Server = http://mirror.neuf.no/archlinux/$repo/os/$arch


## Norway
Server = https://mirror.neuf.no/archlinux/$repo/os/$arch


## Norway
Server = http://mirror.archlinux.no/$repo/os/$arch


## Norway
Server = https://mirror.archlinux.no/$repo/os/$arch


## Norway
Server = http://archlinux.uib.no/$repo/os/$arch


## Norway
Server = http://mirror.terrahost.no/linux/archlinux/$repo/os/$arch

Archinstall will not install any ucode.
The multilib flag is set. This system will be installed with the multilib repository enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'btrfs-progs']
Setting keyboard language to no
Keyboard language for this installation is now set to: no
Setting mirrors
Mirrorlist: 

## Norway
Server = http://mirror.neuf.no/archlinux/$repo/os/$arch


## Norway
Server = https://mirror.neuf.no/archlinux/$repo/os/$arch


## Norway
Server = http://mirror.archlinux.no/$repo/os/$arch


## Norway
Server = https://mirror.archlinux.no/$repo/os/$arch


## Norway
Server = http://archlinux.uib.no/$repo/os/$arch


## Norway
Server = http://mirror.terrahost.no/linux/archlinux/$repo/os/$arch

Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Limine to /dev/sda1
Installing limine bootloader
Installing packages: ['limine']
Limine boot partition: /dev/sda1
Limine EFI partition: /dev/sda1
Identifying root partition by PARTUUID: 6d322182-e99a-4f6d-b8c9-f1d0fabebd19
kernel parameters: root=PARTUUID=6d322182-e99a-4f6d-b8c9-f1d0fabebd19 zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs
Enabling service systemd-networkd
Enabling service systemd-resolved
Creating user alexander
Setting password for alexander
Enabling sudo permissions for alexander
Installing audio server: Pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'alexander', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to user scope bus via local transport: Medium ikke funnet[0m


Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 246, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 116, in perform_installation
    with Installer(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 173, in perform_installation
    audio_config.install_audio_config(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/models/audio_configuration.py", line 46, in install_audio_config
    PipewireProfile().install(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 40, in install
    self._enable_pipewire_for_all(install_session)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 35, in _enable_pipewire_for_all
    install_session.arch_chroot('systemctl enable --user pipewire-pulse.service', run_as=user.username)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 632, in arch_chroot
    return self.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 626, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'alexander', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to user scope bus via local transport: Medium ikke funnet[0m



Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

#### Description of the issue

I downloaded the latest ISO and tried installing it on macOS in the UTM application, which uses QEMU for emulation.

After running "archinstall" and selecting options, it worked for a while and then crashed.

There were also errors that mentioned `epoll_wait` and systemd.

Here's a screenshot:

<img width="1278" alt="bilde" src="https://github.com/user-attachments/assets/f8c02c26-39de-40d3-a13a-975b09d22bfa">

#### Virtual machine config (UTM):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Backend</key>
	<string>QEMU</string>
	<key>ConfigurationVersion</key>
	<integer>4</integer>
	<key>Display</key>
	<array>
		<dict>
			<key>DownscalingFilter</key>
			<string>Linear</string>
			<key>DynamicResolution</key>
			<true/>
			<key>Hardware</key>
			<string>virtio-gpu-pci</string>
			<key>NativeResolution</key>
			<false/>
			<key>UpscalingFilter</key>
			<string>Nearest</string>
		</dict>
	</array>
	<key>Drive</key>
	<array>
		<dict>
			<key>Identifier</key>
			<string>CDFE03DB-50CE-428F-A5E5-A12228F634E6</string>
			<key>ImageType</key>
			<string>CD</string>
			<key>Interface</key>
			<string>IDE</string>
			<key>InterfaceVersion</key>
			<integer>1</integer>
			<key>ReadOnly</key>
			<true/>
		</dict>
		<dict>
			<key>Identifier</key>
			<string>6A128B6E-BD07-4F1B-A2F1-5826181716A7</string>
			<key>ImageName</key>
			<string>6A128B6E-BD07-4F1B-A2F1-5826181716A7.qcow2</string>
			<key>ImageType</key>
			<string>Disk</string>
			<key>Interface</key>
			<string>IDE</string>
			<key>InterfaceVersion</key>
			<integer>1</integer>
			<key>ReadOnly</key>
			<false/>
		</dict>
	</array>
	<key>Information</key>
	<dict>
		<key>Icon</key>
		<string>linux</string>
		<key>IconCustom</key>
		<false/>
		<key>Name</key>
		<string>Arch Linux</string>
		<key>UUID</key>
		<string>DDFF38C4-5D77-4631-9BDC-747344EB5E46</string>
	</dict>
	<key>Input</key>
	<dict>
		<key>MaximumUsbShare</key>
		<integer>3</integer>
		<key>UsbBusSupport</key>
		<string>3.0</string>
		<key>UsbSharing</key>
		<false/>
	</dict>
	<key>Network</key>
	<array>
		<dict>
			<key>Hardware</key>
			<string>e1000</string>
			<key>IsolateFromHost</key>
			<false/>
			<key>MacAddress</key>
			<string>C2:2A:77:11:55:C7</string>
			<key>Mode</key>
			<string>Shared</string>
			<key>PortForward</key>
			<array/>
		</dict>
	</array>
	<key>QEMU</key>
	<dict>
		<key>AdditionalArguments</key>
		<array/>
		<key>BalloonDevice</key>
		<false/>
		<key>DebugLog</key>
		<false/>
		<key>Hypervisor</key>
		<false/>
		<key>PS2Controller</key>
		<false/>
		<key>RNGDevice</key>
		<true/>
		<key>RTCLocalTime</key>
		<false/>
		<key>TPMDevice</key>
		<false/>
		<key>TSO</key>
		<false/>
		<key>UEFIBoot</key>
		<true/>
	</dict>
	<key>Serial</key>
	<array/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
		<key>DirectoryShareMode</key>
		<string>VirtFS</string>
		<key>DirectoryShareReadOnly</key>
		<false/>
	</dict>
	<key>Sound</key>
	<array>
		<dict>
			<key>Hardware</key>
			<string>intel-hda</string>
		</dict>
	</array>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>x86_64</string>
		<key>CPU</key>
		<string>default</string>
		<key>CPUCount</key>
		<integer>0</integer>
		<key>CPUFlagsAdd</key>
		<array/>
		<key>CPUFlagsRemove</key>
		<array/>
		<key>ForceMulticore</key>
		<false/>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>MemorySize</key>
		<integer>4096</integer>
		<key>Target</key>
		<string>q35</string>
	</dict>
</dict>
</plist>
```

In UTM, I selected everything to be as "default" as possible: emulate, use settings for Linux, a bit more ram, a bit more disk and then "play".

**Comment by svartkanin** [comment]
Resolved already
