### ISSUE TITLE
lvm luks error

### ISSUE THREAD

**Issue by Goosegit11** [archlinux/archinstall#2924]
### Which ISO version are you using?

2024-08-01

### The installation log

```json
https://0x0.st/X51j.log
```

#### Description of the issue

I was installing on X hardware ...

Then X Y Z happened and archinstall crashed ...

#### Virtual machine config:

```xml
<domain type="kvm">
  <name>my-arch-machine</name>
  ...
  </devices>
</domain>
```

```console
/usr/bin/qemu-system-x86_64 -name guest=my-arch-machine,debug-threads=on -object ...
```

**Comment by Torxed** [comment]
New version available: archinstall 2.8.6-1 -> 3.0.1-1

Could you try `pacman -Sy archinstall` and see if that solves the issue?

**Comment by Goosegit11** [comment]
no

**Comment by Goosegit11** [comment]
```
Setting up LVM config...





^CTraceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 395, in _lvm_info_with_retry
    return self._lvm_info(cmd, info_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 367, in _lvm_info
    raise ValueError('Report does not contain any entry')
ValueError: Report does not contain any entry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 337, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 330, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 186, in <module>
    guided()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 182, in guided
    fs_handler.perform_filesystem_operations()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 81, in perform_filesystem_operations
    self.perform_lvm_operations()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 152, in perform_lvm_operations
    self._setup_lvm_encrypted(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 164, in _setup_lvm_encrypted
    self._setup_lvm(lvm_config, enc_mods)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 228, in _setup_lvm
    lv_info = device_handler.lvm_vol_info(lv.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 406, in lvm_vol_info
    return self._lvm_info_with_retry(cmd, 'lv')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 397, in _lvm_info_with_retry
    time.sleep(3)
KeyboardInterrupt
```

**Comment by NderCh** [comment]
Que tal amigo , pregunto si arreglaste el error que te genera, yo también tengo el mismo error al tratar de instalar en mi portátil y ahora me da en la maquina virtual VirtualBox que tengo instalado en Windows, si encontraste la solución me informas por favor , que tengas un lindo día
![mi error](https://github.com/user-attachments/assets/652b84f7-d6a7-4d56-beba-bad8aa80c66b)

**Comment by svartkanin** [comment]
As part of https://github.com/archlinux/archinstall/issues/2687 there was a infinite wait implemented that is expecting for the volumes to be ready eventually. 

After it gets stuck for a while (maybe 5min) could you terminate it and then run 
```
lvs --reportformat json --unit B
```
and post the output?

**Comment by teslamania31** [comment]
Hi,

I faced the same issue with a 32GiB disk in a virtual machine.
I used the "best-effort default partition layout" and the "default layout" in LVM. All in ext4.
So by default, it creates a 1GiB /boot and the lvm part will have what's left : 33282850816B (we also have an offset of 3MiB)
There will be two partition in the vg : /root : 20GiB and /home : 11808014336B

When it is created the vg has a size of 33281802240B (less than 33282850816B, it is 1MiB less). 

It is taken account in the file archinstall/lib/disk/filesystem.py (around line 208) and an update of the size of the max partition is done.
In our case the root partition is reduce by 1Mib.
But the PE size of the pv and the vg is 4Mib, so when the lvcreate for the root lvm partition is done, the command rounds up the sector by 1Mib.

And for the second partition : the /home, there is not enough space to create it and it gets stuck here...

As a quick workaround I changed the line 219 in archinstall/lib/disk/filesystem.py : max_vol = max(vg.volumes, key=lambda x: x.length) by last_vol = vg.volumes[-1]
and in line 222 the max_vol by last_vol
In order to reduce the last partition which is the one that will not be a multiple of 4MiB.
