### ISSUE TITLE
Archinstall crashing on install - Failed to connect to user scope bus via local transport: No medium found

### ISSUE THREAD

**Issue by tihsamikah** [archlinux/archinstall#2957]
### Which ISO version are you using?

archlinux-2024.11.01-x86_64

### The installation log

```json
Mounting /dev/sda2: mount /dev/sda2 /mnt/arch_btrfs
Partition /dev/sda2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Hardware model detected: innotek GmbH VirtualBox; UEFI mode: False
Processor model detected: AMD Ryzen 7 5800X 8-Core Processor
Memory statistics: 3566500 available out of 4010612 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "810 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0xb",
                "partuuid": "54fc6a8b-01",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "54fc6a8b",
                "rota": true,
                "size": "1024 MiB",
                "tran": null,
                "type": "part",
                "uuid": "0F15-58C4"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "btrfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0x83",
                "partuuid": "54fc6a8b-02",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "54fc6a8b",
                "rota": true,
                "size": "31741 MiB",
                "tran": null,
                "type": "part",
                "uuid": "80b643f5-1d14-47eb-a36a-dd66eb723611"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "54fc6a8b",
        "rota": true,
        "size": "32768 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "iso9660",
        "fsuse_percentage": "100%",
        "fsver": "Joliet Extension",
        "log_sec": 2048,
        "mountpoint": "/run/archiso/bootmnt",
        "mountpoints": [
            "/run/archiso/bootmnt"
        ],
        "name": "sr0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sr0",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "211019da",
        "rota": false,
        "size": "1154 MiB",
        "tran": "ata",
        "type": "rom",
        "uuid": "2024-11-01-10-09-22-00"
    }
]
Checking version...
New version available: [?25larchinstall 2.8.6-1 -> 3.0.1-1

    score: 1
Loaded mirror mirror.server.net with current score of 1
    score: 1
Loaded mirror mirror.server.net with current score of 1
    score: 1
Loaded mirror arch-mirror.marcusspencer.xyz with current score of 1
    score: 1
Loaded mirror arch-mirror.marcusspencer.xyz with current score of 1
    score: 3
Loaded mirror arch-mirror.marcusspencer.xyz with current score of 3
    score: 5
Loaded mirror mirrors.xhosts.co.uk with current score of 5
    score: 1
Loaded mirror at-vie.soulharsh007.dev with current score of 1
    score: 1
Loaded mirror us-mnz.soulharsh007.dev with current score of 1
    score: 1
Loaded mirror mirrors.saswata.cc with current score of 1
    score: 1
Loaded mirror mirrors.saswata.cc with current score of 1
    score: 4
Loaded mirror mirrors.saswata.cc with current score of 4
    score: 1
Loaded mirror archlinux.gay with current score of 1
    score: 2
Loaded mirror archlinux.gay with current score of 2
    score: 3
Loaded mirror repo.c48.uk with current score of 3
    score: 3
Loaded mirror repo.c48.uk with current score of 3
    score: 5
Loaded mirror repo.c48.uk with current score of 5
    score: 1
Loaded mirror f.matthieul.dev with current score of 1
    score: 3
Loaded mirror mirrors.nepalicloud.com with current score of 3
    score: 3
Loaded mirror mirrors.nepalicloud.com with current score of 3
    score: 4
Loaded mirror mirror.hakimi-soft.ir with current score of 4
    score: 1
Loaded mirror arch.mirror.hyperbit.it with current score of 1
Checking download speed of mirror.aarnet.edu.au[2] by fetching: https://mirror.aarnet.edu.au/pub/archlinux/core/os/x86_64/core.db
    speed: 8347049.655486376 (7.96MiB/s)
Checking download speed of ftp.iinet.net.au[3] by fetching: http://ftp.iinet.net.au/pub/archlinux/core/os/x86_64/core.db
    speed: 1405639.595421633 (1.34MiB/s)
Checking download speed of mirror.internode.on.net[4] by fetching: http://mirror.internode.on.net/pub/archlinux/core/os/x86_64/core.db
    speed: 1279516.031977669 (1.22MiB/s)
Checking download speed of ftp.swin.edu.au[2] by fetching: http://ftp.swin.edu.au/archlinux/core/os/x86_64/core.db
    speed: 529346.4497029111 (0.5MiB/s)
Checking download speed of syd.mirror.rackspace.com[4] by fetching: http://syd.mirror.rackspace.com/archlinux/core/os/x86_64/core.db
    speed: 2301906.36180102 (2.19MiB/s)
Checking download speed of syd.mirror.rackspace.com[4] by fetching: https://syd.mirror.rackspace.com/archlinux/core/os/x86_64/core.db
    speed: 2716662.796282779 (2.59MiB/s)
Checking download speed of archlinux.mirror.digitalpacific.com.au[4] by fetching: http://archlinux.mirror.digitalpacific.com.au/core/os/x86_64/core.db
    speed: 3288838.8473753626 (3.13MiB/s)
Checking download speed of archlinux.mirror.digitalpacific.com.au[5] by fetching: https://archlinux.mirror.digitalpacific.com.au/core/os/x86_64/core.db
    speed: 4918435.499871792 (4.69MiB/s)
Checking download speed of au.mirrors.cicku.me[2] by fetching: http://au.mirrors.cicku.me/archlinux/core/os/x86_64/core.db
    speed: 27582518.821746584 (26.3MiB/s)
Checking download speed of au.mirrors.cicku.me[2] by fetching: https://au.mirrors.cicku.me/archlinux/core/os/x86_64/core.db
    speed: 26090479.875281192 (24.88MiB/s)
Checking download speed of gsl-syd.mm.fcix.net[1] by fetching: http://gsl-syd.mm.fcix.net/archlinux/core/os/x86_64/core.db
    speed: 2647609.031438795 (2.52MiB/s)
Checking download speed of gsl-syd.mm.fcix.net[2] by fetching: https://gsl-syd.mm.fcix.net/archlinux/core/os/x86_64/core.db
    speed: 4301568.262758865 (4.1MiB/s)
Checking download speed of sydney.mirror.pkgbuild.com[1] by fetching: https://sydney.mirror.pkgbuild.com/core/os/x86_64/core.db
    speed: 4533566.558333182 (4.32MiB/s)
Checking download speed of au.arch.niranjan.co[1] by fetching: https://au.arch.niranjan.co/core/os/x86_64/core.db
    speed: 4925041.208113606 (4.69MiB/s)
Password strength: weak
Password strength: weak
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cosmic.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/plasma.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Grub",
    "config_version": "2.8.6",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/sda",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "44515858-ed9c-4374-97f2-76b8af296975",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 3
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": "/",
                        "obj_id": "dc9491f7-7efb-493a-b4bb-9a425d5ea97f",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 33282850816
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1076887552
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "vmlinux",
    "kernels": [
        "linux-zen"
    ],
    "locale_config": {
        "kb_layout": "us",
        "sys_enc": "UTF-8",
        "sys_lang": "en_AU"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Australia": [
                "http://gsl-syd.mm.fcix.net/archlinux/$repo/os/$arch",
                "https://sydney.mirror.pkgbuild.com/$repo/os/$arch",
                "https://au.arch.niranjan.co/$repo/os/$arch",
                "http://ftp.swin.edu.au/archlinux/$repo/os/$arch",
                "https://gsl-syd.mm.fcix.net/archlinux/$repo/os/$arch",
                "https://mirror.aarnet.edu.au/pub/archlinux/$repo/os/$arch",
                "https://au.mirrors.cicku.me/archlinux/$repo/os/$arch",
                "http://au.mirrors.cicku.me/archlinux/$repo/os/$arch",
                "http://ftp.iinet.net.au/pub/archlinux/$repo/os/$arch",
                "http://mirror.internode.on.net/pub/archlinux/$repo/os/$arch",
                "http://syd.mirror.rackspace.com/archlinux/$repo/os/$arch",
                "https://syd.mirror.rackspace.com/archlinux/$repo/os/$arch",
                "http://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch",
                "https://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch"
            ]
        }
    },
    "network_config": {
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "All open-source",
        "greeter": "sddm",
        "profile": {
            "custom_settings": {
                "KDE Plasma": {}
            },
            "details": [
                "KDE Plasma"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Australia/Sydney",
    "uki": false,
    "version": "2.8.6"
}
Unmounting all existing partitions: /dev/sda
Unmounting: /dev/sda1
Unmounting: /dev/sda2
Wiping partitions and metadata: /dev/sda
Creating partitions: /dev/sda
	Type: primary
	Filesystem: fat32
	Geometry: 6144 start sector, 2097152 length
	Type: primary
	Filesystem: btrfs
	Geometry: 2103296 start sector, 65005568 length
Formatting filesystem: mkfs.fat -F 32 /dev/sda1
partition information found: {'name': 'sda1', 'path': '/dev/sda1', 'pkname': 'sda', 'size': '1024 MiB', 'log_sec': 512, 'pttype': 'dos', 'ptuuid': 'd2c6e7cc', 'rota': True, 'tran': None, 'partn': 1, 'partuuid': 'd2c6e7cc-01', 'parttype': '0xb', 'uuid': '37B8-1F0F', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Formatting filesystem: mkfs.btrfs -f /dev/sda2
partition information found: {'name': 'sda2', 'path': '/dev/sda2', 'pkname': 'sda', 'size': '31741 MiB', 'log_sec': 512, 'pttype': 'dos', 'ptuuid': 'd2c6e7cc', 'rota': True, 'tran': None, 'partn': 2, 'partuuid': 'd2c6e7cc-02', 'parttype': '0x83', 'uuid': '45c68889-8a53-4278-917b-fe39121ac270', 'fstype': 'btrfs', 'fsver': None, 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Creating subvolumes: /dev/sda2
Mounting /dev/sda2: mount -o compress=zstd /dev/sda2 /mnt/arch_btrfs
Partition /dev/sda2 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Starting installation...
Mounting ordered layout
No lvm config defined to be mounted
Mounting partition layout
Mounting /dev/sda2: mount -o compress=zstd /dev/sda2 /mnt/archinstall
Mounting /dev/sda1: mount /dev/sda1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
Setting mirrors
Mirrorlist: 

## Australia
Server = http://gsl-syd.mm.fcix.net/archlinux/$repo/os/$arch


## Australia
Server = https://sydney.mirror.pkgbuild.com/$repo/os/$arch


## Australia
Server = https://au.arch.niranjan.co/$repo/os/$arch


## Australia
Server = http://ftp.swin.edu.au/archlinux/$repo/os/$arch


## Australia
Server = https://gsl-syd.mm.fcix.net/archlinux/$repo/os/$arch


## Australia
Server = https://mirror.aarnet.edu.au/pub/archlinux/$repo/os/$arch


## Australia
Server = https://au.mirrors.cicku.me/archlinux/$repo/os/$arch


## Australia
Server = http://au.mirrors.cicku.me/archlinux/$repo/os/$arch


## Australia
Server = http://ftp.iinet.net.au/pub/archlinux/$repo/os/$arch


## Australia
Server = http://mirror.internode.on.net/pub/archlinux/$repo/os/$arch


## Australia
Server = http://syd.mirror.rackspace.com/archlinux/$repo/os/$arch


## Australia
Server = https://syd.mirror.rackspace.com/archlinux/$repo/os/$arch


## Australia
Server = http://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch


## Australia
Server = https://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch

Archinstall will not install any ucode.
The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux-zen', 'btrfs-progs', 'grub']
Setting keyboard language to us
Keyboard language for this installation is now set to: us
Setting mirrors
Mirrorlist: 

## Australia
Server = http://gsl-syd.mm.fcix.net/archlinux/$repo/os/$arch


## Australia
Server = https://sydney.mirror.pkgbuild.com/$repo/os/$arch


## Australia
Server = https://au.arch.niranjan.co/$repo/os/$arch


## Australia
Server = http://ftp.swin.edu.au/archlinux/$repo/os/$arch


## Australia
Server = https://gsl-syd.mm.fcix.net/archlinux/$repo/os/$arch


## Australia
Server = https://mirror.aarnet.edu.au/pub/archlinux/$repo/os/$arch


## Australia
Server = https://au.mirrors.cicku.me/archlinux/$repo/os/$arch


## Australia
Server = http://au.mirrors.cicku.me/archlinux/$repo/os/$arch


## Australia
Server = http://ftp.iinet.net.au/pub/archlinux/$repo/os/$arch


## Australia
Server = http://mirror.internode.on.net/pub/archlinux/$repo/os/$arch


## Australia
Server = http://syd.mirror.rackspace.com/archlinux/$repo/os/$arch


## Australia
Server = https://syd.mirror.rackspace.com/archlinux/$repo/os/$arch


## Australia
Server = http://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch


## Australia
Server = https://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch

Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Grub to /dev/sda1
Installing grub bootloader
Installing packages: ['grub']
kernel parameters: zswap.enabled=0 rootfstype=btrfs
GRUB boot partition: /dev/sda1
GRUB boot partition: /dev/sda1
Installing packages: ['networkmanager']
Installing packages: ['network-manager-applet']
Enabling service NetworkManager.service
Creating user tihsamikah
Setting password for tihsamikah
Enabling sudo permissions for tihsamikah
Installing audio server: Pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'tihsamikah', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to user scope bus via local transport: No medium found[0m


Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 246, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 116, in perform_installation
    with Installer(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 173, in perform_installation
    audio_config.install_audio_config(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/models/audio_configuration.py", line 46, in install_audio_config
    PipewireProfile().install(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 40, in install
    self._enable_pipewire_for_all(install_session)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 35, in _enable_pipewire_for_all
    install_session.arch_chroot('systemctl enable --user pipewire-pulse.service', run_as=user.username)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 632, in arch_chroot
    return self.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 626, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'tihsamikah', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to user scope bus via local transport: No medium found[0m



Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

### describe the problem

Good Morning / Afternoon All,

Trying to install on Virtualbox, Archinstall crashes  with "Failed to connect to user scope bus via local transport: No medium found".

it happens around when the script goes to install Pipewire.

I've replicated it twice - I'm going to try again with selecting no audio.

**Comment by tihsamikah** [comment]
I got the installer to install with no audio, but not with pulseaudio.

so to reference the log files - 

Pipewire crash
https://0x0.st/XRWK.log

Pulseaudio crash
https://0x0.st/XRWa.log

the installer seems to step into pipewire install code, even when you install pulseaudio?

**Comment by svartkanin** [comment]
Solved in the latest release
