### ISSUE TITLE
trying to dual boot arch

### ISSUE THREAD

**Issue by Realrubr2** [archlinux/archinstall#3003]
### Which ISO version are you using?

Dec 1st

### The installation log

```json
Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Grub to /dev/nvme0n1p5
Installing grub bootloader
Installing packages: ['grub']
kernel parameters: zswap.enabled=0 rootfstype=ext4
GRUB boot partition: /dev/nvme0n1p5
GRUB boot partition: /dev/nvme0n1p5
Failed to install GRUB boot on /dev/nvme0n1p5: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-install', '--debug', '--target=i386-pc', '--recheck', '/dev/nvme0n1'] exited with abnormal exit code [1]:  guessed root_dev `hostdisk//dev/nvme0n1' from dir `/boot/grub/i386-pc'.
grub-install: info: setting the root device to `hostdisk//dev/nvme0n1,gpt5'.
grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 1226, in _add_grub_bootloader
    SysCommand(command + add_options, peek_output=True)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 368, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 417, in create_session
    with SysCommandWorker(
         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-install', '--debug', '--target=i386-pc', '--recheck', '/dev/nvme0n1'] exited with abnormal exit code [1]:  guessed root_dev `hostdisk//dev/nvme0n1' from dir `/boot/grub/i386-pc'.
grub-install: info: setting the root device to `hostdisk//dev/nvme0n1,gpt5'.
grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 337, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 330, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 186, in <module>
    guided()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 183, in guided
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 52, in perform_installation
    with Installer(
         ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 113, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 89, in perform_installation
    installation.add_bootloader(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 1472, in add_bootloader
    self._add_grub_bootloader(boot_partition, root, efi_partition)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 1228, in _add_grub_bootloader
    raise DiskError(f"Failed to install GRUB boot on {boot_partition.dev_path}: {err}")
archinstall.lib.exceptions.DiskError: Failed to install GRUB boot on /dev/nvme0n1p5: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-install', '--debug', '--target=i386-pc', '--recheck', '/dev/nvme0n1'] exited with abnormal exit code [1]:  guessed root_dev `hostdisk//dev/nvme0n1' from dir `/boot/grub/i386-pc'.
grub-install: info: setting the root device to `hostdisk//dev/nvme0n1,gpt5'.
grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
```

#### Description of the issue

I was installing on arch linux on my windows pc, 
I made some partitions before running the arch linux installer
nvme0n1p5 efi system mount /boot
partitioned it to fat32
nvme0n1p6 swap
nvme0n1p7 filesystem mount /
partition to ext4

runned the arch installer and got the error of not being albe to install grub,
because it does not contain a bios boot partition

what should i do to fix it because in my eyes the boot partition is set

**Comment by svartkanin** [comment]
Did you follow these instructions for dual boot https://github.com/archlinux/archinstall?tab=readme-ov-file#how-to-dual-boot-with-windows

**Comment by Joel101y** [comment]
i do have the same issue and i couldn't find any fix for that

**Comment by Realrubr2** [comment]
I did follow the steps i reformatted the whole disk removing the windows partition. Then it eorked, seems arch is having trouble with the windows boot on the same disk

**Comment by Joel101y** [comment]
you reformatted the whole disk from arch? because i fucked up my system and im now with ubuntu, it should work right?

**Comment by Realrubr2** [comment]
Yeah the full format worked when i didn't try to dual boot windows.
Now i installed windows onto a different disk. And wil implement it into grub

**Comment by Joel101y** [comment]
yeah, that happened to me either but when i install arch in the other disk it runs so slow(i think that is bc of the disk itself) so for now i give up on arch and installed kali :v

**Comment by lazysixoeight** [comment]
did you install grub on windows' boot partition, cause it won't install properly if it's too small

**Comment by abhimangs** [comment]
It seems GRUB is trying to install on the wrong partition. Make sure /boot is a FAT32 partition (at least 512 MB) and properly mounted during installation. Use this to reinstall GRUB:
`
mount /dev/nvme0n1p7 /mnt  
mount /dev/nvme0n1p5 /mnt/boot  
arch-chroot /mnt  
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB  
grub-mkconfig -o /boot/grub/grub.cfg  
exit  
`
Ensure your system is in UEFI mode, and GRUB targets the EFI system partition.
