### ISSUE TITLE
Could not determine the filesystem: None

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [archlinux/archinstall#3027]
### Which ISO version are you using?

2024.12.01

### The installation log

```json
Could not determine the filesystem: None
Could not determine the filesystem: parted.FileSystem instance --
  type: linux-swap(v1)  geometry: <parted.geometry.Geometry object at 0x76c87589eba0>  checked: False
  PedFileSystem: <_ped.FileSystem object at 0x76c875876d80>
Could not determine the filesystem: None
```
https://0x0.st/XCM6.log or https://0x0.st/XCuP.log or https://0x0.st/XCub.log

### describe the problem

[log.txt](https://github.com/user-attachments/files/18188593/log.txt)

Hardware model detected: Gigabyte Technology Co., Ltd. B650 GAMING X; UEFI mode: True
Processor model detected: AMD Ryzen 5 7600X 6-Core Processor
Memory statistics: 30701756 available out of 32463564 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] (rev c1)'])

**Comment by pitastrudl** [comment]
Is the error at the end related to the first? 

```
Unmounting all existing partitions: /dev/nvme0n1
Unmounting: /dev/nvme0n1p1
Wiping partitions and metadata: /dev/nvme0n1
Creating partitions: /dev/nvme0n1
	Type: primary
	Filesystem: fat32
	Geometry: 2048 start sector, 2097152 length
	Type: primary
	Filesystem: btrfs
	Geometry: 2099200 start sector, 3904927920 length
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 337, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 330, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 186, in <module>
    guided()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 182, in guided
    fs_handler.perform_filesystem_operations()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 70, in perform_filesystem_operations
    device_handler.partition(mod, partition_table=partition_table)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 712, in partition
    disk.commit()
  File "/usr/lib/python3.12/site-packages/parted/decorators.py", line 28, in new
    ret = fn(*args, **kwds)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/parted/disk.py", line 208, in commit
    return self.__disk.commit()
           ^^^^^^^^^^^^^^^^^^^^
_ped.IOException: Partition(s) 2, 3 on /dev/nvme0n1 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.


```
