### ISSUE TITLE
Crash when trying to use disk_layouts argument

### ISSUE THREAD

**Issue by hkaancaliskan** [archlinux/archinstall#743]
![VirtualBox_Arch_19_11_2021_23_40_02](https://user-images.githubusercontent.com/17825767/142689807-d1ca16e6-c4c2-4d2c-a874-6967c188a92b.png)

```
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MiB",
                "start": "5MiB",
                "type": "primary"
            },
            {
                "btrfs": {
                    "subvolumes": {
                        "@.snapshots": "/.snapshots",
                        "@home": "/home",
                        "@log": "/var/log",
                        "@pkgs": "/var/cache/pacman/pkg"
                    }
                },
                "encrypted": true,
                "filesystem": {
                    "format": "btrfs",
                    "options": "compress=zstd:1"
                },
                "format": true,
                "mountpoint": "/",
                "size": "100%",
                "start": "518MiB",
                "type": "primary"
            }
        ],
        "wipe": true
    }
}
```

**Comment by Torxed** [comment]
Is it requiring `=` between the arguments? `--creds=creed.json`?

**Comment by hkaancaliskan** [comment]
@Torxed nope, if i remove disk_layouts, others working and filling out

**Comment by Torxed** [comment]
> @Torxed nope, if i remove disk_layouts, others working and filling out

Ah thank you! Couldn't test it or bother reading the source on my phone.
I'll investigate! : )

**Comment by wllacer** [comment]
Try change to --disk_layouts=/var/log/archinstall/user_disk_layout.json
This inconsistency is being worked out by now (see PR725)
In my case it fails afterward with 
```
[werner@xerneas archinstall]$ sudo python -m archinstall --config /var/log/archinstall/user_configuration.json --disk_layouts=/var/lib/archinstall/user_disk_layout.json
Testing connectivity to the Arch Linux mirrors ...
Traceback (most recent call last):
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 62, in load_config
    archinstall.storage['disk_layouts'] = json.loads(archinstall.arguments['disk_layouts'])
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/werner/projects/archinstall/archinstall/__main__.py", line 4, in <module>
    archinstall.run_as_a_module()
  File "/home/werner/projects/archinstall/archinstall/__init__.py", line 111, in run_as_a_module
    script.execute()
  File "/home/werner/projects/archinstall/archinstall/lib/profiles.py", line 180, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 371, in <module>
    load_config()
  File "/home/werner/projects/archinstall/archinstall/examples/guided.py", line 64, in load_config
    raise ValueError("--disk_layouts=<json> needs either a JSON file or a JSON string given with a valid disk layout.")
ValueError: --disk_layouts=<json> needs either a JSON file or a JSON string given with a valid disk layout.
```
Looks like an Json encoding error at the file (?). Can you reproduce it?

**Comment by hkaancaliskan** [comment]
Oh.... If i add `=` just for `--disk_layouts`, it works perfectly. @wllacer I'm not able to reproduce that, works great for me.
@Torxed `=` just required for `--disk_layouts`

Final command is: `python -m archinstall --config /mnt/wm/user_configuration.json --creds /mnt/wm/user_credentials.json --disk_layouts=/mnt/wm/user_disk_layout.json`

**Comment by hkaancaliskan** [comment]
@Torxed Also i've added compress option like this
```
"encrypted": true,
                "filesystem": {
                    "format": "btrfs",
                    "options": "compress=zstd:1"
                },
                "format": true,
                "mountpoint": "/",
```
Is this where it should be?
Because i can't see in cmd_history
![VirtualBox_Arch_20_11_2021_16_01_29](https://user-images.githubusercontent.com/17825767/142727270-e4bcb63b-b3b6-4461-b3d1-b918cf146e9b.png)

**Comment by wllacer** [comment]
@hkaancaliskan Many thanks for the feedback. Now I have to check where i do have the problem :-(

**Comment by hkaancaliskan** [comment]
@wllacer `--config /var/log/archinstall/user_configuration.json --disk_layouts=/var/lib/archinstall/user_disk_layout.json`
You're using /var/log for --config but also using /var/lib for --disk_layouts. Maybe problem is related to that

**Comment by wllacer** [comment]
@hkaancaliskan 
I don't know  if to cry or to ROTFL. It was it. You've saved me a lot of swearing and typing ...
Thanks a lot. 
I think this issue can be closed, don't you think ?

**Comment by hkaancaliskan** [comment]
@wllacer glad it's solved lol
