### ISSUE TITLE
Error when using generated disk layout

### ISSUE THREAD

**Issue by asininemonkey** [archlinux/archinstall#789]
Getting the following error when using dry run generated configuration files:

```
$ sudo archinstall --dry-run --config user_configuration.json --disk_layouts user_disk_layout.json
Testing connectivity to the Arch Linux mirrors ...
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 33, in <module>
    sys.exit(load_entry_point('archinstall==2.3.0', 'console_scripts', 'archinstall')())
  File "/usr/lib/python3.9/site-packages/archinstall/__init__.py", line 111, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.9/site-packages/archinstall/lib/profiles.py", line 180, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 383, in <module>
    load_config()
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 54, in load_config
    if (dl_path := pathlib.Path(archinstall.arguments['disk_layouts'])).exists() and str(dl_path).endswith('.json'):
  File "/usr/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not bool
```

Not really seeing anything that stands out:

```
{
    "audio": "pipewire",
    "bootloader": "systemd-bootctl",
    "disk_layout": true,
    "dry-run": true,
    "harddrives": [
        "/dev/nvme0n1"
    ],
    "hostname": "intel-nuc",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "uk",
    "mirror-region": {
        "United Kingdom": {
            "https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch": true,
            "https://lon.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://mirror.bytemark.co.uk/archlinux/$repo/os/$arch": true,
            "https://mirror.cov.ukservers.com/archlinux/$repo/os/$arch": true,
            "https://mirror.netweaver.uk/archlinux/$repo/os/$arch": true,
            "https://mirrors.melbourne.co.uk/archlinux/$repo/os/$arch": true,
            "https://www.mirrorservice.org/sites/ftp.archlinux.org/$repo/os/$arch": true
        }
    },
    "nic": {
        "NetworkManager": true,
        "nic": "Use NetworkManager (necessary to configure internet graphically in GNOME and KDE)"
    },
    "ntp": false,
    "packages": [
        "git"
    ],
    "profile": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "Europe/London"
}
```

```
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MB",
                "start": "5MB",
                "type": "primary"
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "mountpoint": "/",
                "size": "20GB",
                "start": "518MB",
                "type": "primary"
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "mountpoint": "/home",
                "size": "100%",
                "start": "20.5GB",
                "type": "primary"
            }
        ],
        "wipe": true
    }
}
```

**Comment by wllacer** [comment]
Your the time being command line MUST have this syntax
--disk_layouts=filename.json
