### ISSUE TITLE
Could not get PARTUUID

### ISSUE THREAD

**Issue by remLse** [archlinux/archinstall#824]
Hi there, I'm having some trouble on my desktop. (laptop works fine.) The install seems to fail during partitioning. I'll post the full terminal output below. In my opinion, there isn't anything useful in `/var/log/archinstall/install.log`, since the output stops at "Getting mount information for device path /dev/nvme1n1p1"

The output might have typos in it because I took a photo, used text recognition and tried to clean it up as much as possible. (Is there a better way to grab terminal output from a live environment?)

I also included the output of `lsblk -J -o+PARTUUID` which seems to work fine on its own.

I'd be happy to work on this myself and get to know the project at the same time. Maybe someone has a tip on how and where to start digging first?

Terminal output right after the final configuration was printed for confirmation:
```
Press Enter to continue.
 ? Formatting [BlockDevice(/deu/nvme1n1, size=119.2GB, free_space=5225kB+128GB, bus_type-nvme)I in 5....4....3....2....1....
Creating a new partition label on /dev/nvme1n1
Adding partition....
Adding partition to BlockDevice(/dew/nvme1n1, size=119.2GB, free_space=128GB, bus_type=nvme), 5MB-›513MB
Getting mount information for device path /dev/nvme1n1p1
Traceback (most recent call last):
  File "usr/bin/archinstall" line 33, in <module>
    sys.exit(load_entry_point('archinstall==2.3.0', 'console scripts', 'archinstall')())
  File "usr/lib/python3.10/site-packages/archinstall/__init__.py", line 111, in run as_a_module
    script.execute()
  File "usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 180, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 387, in <module>
    perform_filesystem_operations()
  File "usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 244, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line32, in __exit__
    raise args[1]
  File "usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 245, in perform_filesystem_operations
    fs.load_layout(archinstall.storage['disk_layouts'][drive.path])
  File "usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 69, in load_layout
    partition['device_instance'] = self.add_partition(partition.get('type', 'primary'),
  File "usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 157, in add_partition
    previous_partition_uuids = {partition.uuid for partition in self.blockdevice.partitions.values()}
  File "usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 157, in <setcomp>
    previous_partition_uuids = {partition.uuid for partition in self.blockdevice.partitions.values()}
  File "usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 170, in uuid
    raise DiskError(f"Could not get PARTUUID for {self.path} using 'lsblk -J -o+PARTUUID {self.path}'")
archinstall.lib.exceptions.DiskError: Could not get PARTUUID for /dev/nvme1n1p1 using 'lsblk -J -o+PARTUUID deu/nvme1n1p1'
archinstall -config $CFG 2.39s user 4.37s system 4% cpu 2:15.76 total
1 root@archiso ~ # lsblk -J -o+PARTUUID/dev/nvme1n1p1
{
  "blockdevices": [
    {
      "name": "nvme1n1p1",
      "maj:min": "259:9",
      "rm": false,
      "size": "484M",
      "ro": false,
      "type": "part",
      "mountpoints": [
        null
      ],
      "partuuid": "ec6BaZef-c036-419d-b/17-eBf551900810"
    }
  ]
}
root@archiso ~ #
```

**Comment by Torxed** [comment]
This has been fixed in `v2.3.1` and in `master`.
In `master` we're now using `blkid` instead which is more reliable.
And in `v2.3.1` we've tweaked the `partprobe` calls and timers to be more reliable.
I'm there for closing this issue but I'd like to thank you for reporting issues and wish you a happy new year : )

**Comment by remLse** [comment]
Thanks for the fast response! I'm sorry, I assumed the new arch ISO from 1.1.2022 would have the latest version of archinstall. I tried installing the latest version in the live ISO and it worked :-)

**Comment by Torxed** [comment]
> I'm sorry

No worries :) Glad it worked!
