### ISSUE TITLE
Readme - Testing using a live cd - pip uninstall archinstall 

### ISSUE THREAD

**Issue by quentincaffeino** [archlinux/archinstall#840]
I was patching this repo and testing it in a vm. `Testing using a live cd` in readme it helped me to start. But point number 3 (`pip uninstall archinstall`) didn't work on arch live cd. I was getting this error

```
$ pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip')())
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pip
```

Was I the only one facing this issue? Solution I found is to not to use pip and remove package using regular rm

```
# find / -name archinstall | grep -v archiso | xargs rm -rf
```

If I wasn't only one maybe readme could be updated?

**Comment by wllacer** [comment]
I had the same issue with the December Live cd.  It was only one of several python problems, Did you happen to do a *pacman -S" for python related packages?.
December Live CD still comes with python 3.9, but if you pacman some python packages from the mirrors it already gets them for the python 3.10 (somewhere in /usr/lib/python3.10/site-packages). I had no space available to pull python 3.10. A bloody "zugzwang" ...
I did make it work. IIRC I did the Pacman -S, and copied the 3.10/site-packages directory into the 3.9 one, and went away with it. But don't take my word as I never noted it down
Maybe the January CD (just released) comes already with python 3.10.

**Comment by quentincaffeino** [comment]
> I had the same issue with the December Live cd. It was only one of several python problems, Did you happen to do a *pacman -S" for python related packages?.

No, I haven't

If works your solution is definitely better in case you care about using pip in live env. I didn't really care about it because I only wanted to test a patch and it can't be done unless current version is uninstalled.

> Maybe the January CD (just released) comes already with python 3.10.

Thanks, I have been playing with arch in vm a lot lately so I might give a new live cd a try

**Comment by Torxed** [comment]
> No, I haven't

You have to have done `pacman -S python-pip` because `pip` is as far as I know not standard in the Arch Linux ISO. So I suspect a [partial upgrade](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported) some where.

**Comment by wllacer** [comment]
From the README.md
> Install the build requirements with pacman -Sy; pacman -S git python-pip

So you, as me, almost for sure, did ;-) . I spent about an hour swearing and headscratching where that f* pip (and a couple of other packages) was, till i browsed the site-packages directories

**Comment by quentincaffeino** [comment]
Yeah both of you are right, I forgot about it not being included :D

**Comment by Torxed** [comment]
I'll go ahead and close this as I think it's a isolated incident related to Arch Linux and not archinstall per sae :)
