### ISSUE TITLE
Problem on master startup

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#847]
After the last merges (the typing one) start fail with following error
```
werner@xerneas archinstall]$ sudo python -m archinstall 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/werner/projects/archinstall/archinstall/__init__.py", line 11, in <module>
    from .lib.installer import __packages__, Installer, accessibility_tools_in_use
  File "/home/werner/projects/archinstall/archinstall/lib/installer.py", line 9, in <module>
    from typing import Union, Dict, Any, List, ModuleType, Optional, Iterator, Mapping
ImportError: cannot import name 'ModuleType' from 'typing' (/usr/lib/python3.10/typing.py)

```

**Comment by Torxed** [comment]
A s*** it's [types.ModuleType](https://docs.python.org/3/library/types.html#types.ModuleType) and not `typing.ModuleType`.. I'll fix a PR right away.

**Comment by Torxed** [comment]
Done.
Also fixed the following error after that:
```
ImportError: cannot import name 'Interator' from 'typing' (/usr/lib/python3.10/typing.py)
```

**Comment by wllacer** [comment]
After such an update ... is small change
