### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by tttffff** [archlinux/archinstall#984]
When running from the [latest commit on master](https://github.com/archlinux/archinstall/commit/d9118a33b3a25839fde8626cde313115ddb79376) in VirtualBox, I am getting errors by selecting on certain menu options. I have installed with `python setup.py install` and ran with `python -m archinstall`.

The error comes straight away when clicking on "Configure network" and also on every outcome of "Specify Profile" apart from "minimal" and "server".

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/archinstall/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/root/archinstall/./archinstall/__init__.py", line 266, in run_as_a_module
    script.execute()
  File "/root/archinstall/archinstall/lib/profiles.py", line 194, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/archinstall/archinstall/examples/guided.py", line 264, in <module>
    ask_user_questions()
  File "/root/archinstall/archinstall/examples/guided.py", line 92, in ask_user_questions
    global_menu.run()
  File "/root/archinstall/archinstall/lib/menu/selection_menu.py", line 270, in run
    if not self._process_selection(selection):
  File "/root/archinstall/archinstall/lib/menu/selection_menu.py", line 287, in _process_selection
    return self.exec_option(selector_name,selector)
  File "/root/archinstall/archinstall/lib/menu/selection_menu.py", line 307, in exec_option
    result = selector.func()
  File "/root/archinstall/archinstall/lib/menu/selection_menu.py", line 510, in <lambda>
    lambda: ask_to_configure_network(),
  File "/root/archinstall/archinstall/lib/user_interaction.py", line 441, in ask_to_configure_network
    nic = Menu(_('Select one network interface to configure'), list(interfaces.values())).run()
  File "/root/archinstall/archinstall/lib/menu/menu.py", line 87, in __init__
    super().__init__(
  File "/root/archinstall/archinstall/lib/menu/simple_menu.py", line 665, in __init__
    ) = extract_shortcuts_menu_entries_and_preview_arguments(menu_entries)
  File "/root/archinstall/archinstall/lib/menu/simple_menu.py", line 602, in extract_shortcuts_menu_entries_and_preview_arguments
    unit_separated_entry = escaped_separator_pattern.sub("|", separator_pattern.sub("\\1\x1F", entry))
TypeError: expected string or bytes-like object
```

**Comment by svartkanin** [comment]
@tttffff we just merged a fix for this and the problem should be resolved now. 
Please feel free to give it another go with the latest master

**Comment by tttffff** [comment]
Works great now. Thank you so much!
